feat(suite-native): retrieving balances takes longer
trezor/trezor-suite pull request #10238
Opened 2023-12-07 10:16 UTC by juriczech

## Description

## Related Issue

Resolve 

## Screenshots:

2023-12-07 14:46 UTC, Nodonisko requested changes

2023-12-07 14:46 UTC, Nodonisko commented on suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
> +            return () => clearInterval(interval);
You shouldn't have cleanup function inside of `if`

2023-12-07 14:49 UTC, Nodonisko commented on suite-native/module-home/src/components/PortfolioGraph.tsx
> +    const loadingTakesLongerThanExpected = useIsDiscoveryDurationTooLong();
Can you please verify that this component doesn't rerender every second now?

2023-12-07 19:49 UTC, juriczech commented on suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
> +            return () => clearInterval(interval);
Good point. Should be fixed now @Nodonisko

2023-12-08 10:22 UTC, juriczech commented on suite-native/module-home/src/components/PortfolioGraph.tsx
> +    const loadingTakesLongerThanExpected = useIsDiscoveryDurationTooLong();
Verified. It doesn't rerender every second

2023-12-08 12:38 UTC, Nodonisko approved these changes

2023-12-11 08:09 UTC, juriczech commented
/rebase

2023-12-11 10:46 UTC, Nodonisko approved these changes

2023-12-11 10:51 UTC, merged