fix(suite): allow bigger width to fit spanish in
trezor/trezor-suite pull request #10318
Opened 2023-12-13 10:39 UTC by peter-sanderson

## Description

Adds a space for Spanish in the QR code description.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10313

## Screenshots:
![image](https://github.com/trezor/trezor-suite/assets/152899911/da32dd73-49b2-423c-9528-ed48bb32b1b4)

2024-01-02 11:58 UTC, tomasklim requested changes

2024-01-02 11:58 UTC, tomasklim commented on packages/suite/src/components/suite/QrCode.tsx
> +                <span style={{ whiteSpace: 'normal' }}>
Please use `styled-components`

2024-01-02 12:08 UTC, tomasklim commented
@Hermez-cz the info icon under QR code next to text looks like that there is some tooltip, but there is not. Should it be there? Or maybe it should be at the begging of the text and not at the end? <img width="666" alt="Screenshot 2024-01-02 at 6 05 22" src="https://github.com/trezor/trezor-suite/assets/33235762/3f126dab-b002-41f1-a884-d43b62af2ae7">

2024-01-03 11:13 UTC, Hermez-cz commented
> @Hermez-cz the info icon under QR code next to text looks like that there is some tooltip, but there is not. Should it be there? Or maybe it should be at the begging of the text and not at the end? <img alt="Screenshot 2024-01-02 at 6 05 22" width="666" src="https://private-user-images.githubusercontent.com/33235762/293688375-3f126dab-b002-41f1-a884-d43b62af2ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODA1OTcsIm5iZiI6MTcwNDI4MDI5NywicGF0aCI6Ii8zMzIzNTc2Mi8yOTM2ODgzNzUtM2YxMjZkYWItYjAwMi00MWYxLWE4ODQtZDQzYjYyYWYyYWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDExMTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDhmMjYzYjllMDExNGViNTU0Zjk1MmFlMWRkYTJkMGUzN2E0NmJlNWJmYWQ5ZDE0YTMyMGIxOTlhNWUyMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vNycyLQF3RpISmKJ-TuJpZw2cgMrdUX9-u3idzgILy4">

We should add a tooltip explaining why you shouldn't do that. Something roughly like "Please confirm the receiving address on device first, as its trusted display can't be hacked unlike this one".

2024-01-04 15:57 UTC, peter-sanderson commented on packages/suite/src/components/suite/QrCode.tsx
> +                <span style={{ whiteSpace: 'normal' }}>
:heavy_check_mark:

2024-01-04 16:11 UTC, peter-sanderson commented
![image](https://github.com/trezor/trezor-suite/assets/152899911/6fe5657c-1a02-41a1-af32-77247fe2b306)
![image](https://github.com/trezor/trezor-suite/assets/152899911/e6d29d0d-f4c6-4345-affd-9441f7b2997b)
![image](https://github.com/trezor/trezor-suite/assets/152899911/0426e244-8346-441f-900d-da95f09283b8)
![image](https://github.com/trezor/trezor-suite/assets/152899911/600ac330-385e-47e5-9460-37d8bd2245cb)

2024-01-08 17:30 UTC, dahaca approved these changes

2024-01-09 15:36 UTC, tomasklim approved these changes

2024-01-09 15:41 UTC, merged