feat(connect): add changeWipeCode method
trezor/trezor-suite pull request #10407
Opened 2023-12-20 16:45 UTC by mroz22

use with caution. 
cc @hynek-jina

2023-12-27 10:41 UTC, tomasklim requested changes, later dismissed
Could you please explain what it does?

2023-12-27 10:41 UTC, tomasklim commented on packages/connect/src/api/changeWipeCode.ts
> +
```suggestion
```

2023-12-29 09:26 UTC, mroz22 commented
@tomasklim edited PR description

2023-12-29 09:29 UTC, mroz22 commented on packages/connect/src/api/changeWipeCode.ts
> +
[084a57a](https://github.com/trezor/trezor-suite/pull/10407/commits/084a57a2bc65936dc323902d5f03406af64bedf1)

2023-12-29 09:30 UTC, hynek-jina approved these changes
LGTM

2023-12-29 09:31 UTC, mroz22 commented
/rebase

2023-12-29 09:51 UTC, merged