Feat(suite):wipe code WIP
trezor/trezor-suite pull request #10434
Opened 2023-12-27 10:44 UTC by hynek-jina

2023-12-27 10:48 UTC, hynek-jina commented on packages/suite/src/actions/settings/deviceSettingsActions.ts
> +    (params: Parameters<typeof TrezorConnect.changeWipeCode>[0] = {}, skipSuccessToast?: boolean) =>
@mroz22 
I'm trying to build on changePin "template".. however don't know why `TrezorConnect.changeWipeCode` is not reachable?

2023-12-29 10:18 UTC, mroz22 requested changes

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDevice/WipeCode.tsx
> +interface ChangePinProps {
maybe rename ChangePinProps to WipeCodeProps or maybe event better only `Props`

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDevice/WipeCode.tsx
> +        });
analytics, remove or update

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDevice/WipeCode.tsx
> +                buttonLink="https://trezor.io/learn/a/create-wipe-code-to-erase-device"
this should be listed here https://github.com/trezor/trezor-suite/blob/fix/connect-webexplorer-to-allow-more-than-one-request/packages/urls/src/urls.ts#L0-L1

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDevice/WipeCode.tsx
> +                    // TODO: Disable when pin is not set
some pin remnant in comment

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/actions/settings/deviceSettingsActions.ts
> +        } else if (result.payload.code === 'Failure_PinMismatch') {
please test mismatch when setting up wipe code on model One. imho it does not return `Failure_PinMismatch` but something like WipeCodeMismatch maybe?

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/actions/settings/deviceSettingsActions.ts
> +        } else if (result.payload.code === 'Failure_PinMismatch') {
could be that this branch (else if) is intended to handle something that will never happen here

2023-12-29 10:18 UTC, mroz22 commented on packages/suite/src/actions/settings/deviceSettingsActions.ts
> +        } else if (result.payload.error.includes('string overflow')) {
this else if maybe never happens (my gut feeling).

2023-12-29 11:35 UTC, mroz22 approved these changes
lgtm

coverage still low https://github.com/trezor/trezor-suite/actions/runs/7356090421/job/20025702378?pr=10434#step:19:877

2023-12-29 11:35 UTC, mroz22 commented on packages/suite/src/actions/settings/deviceSettingsActions.ts
>              dispatch(modalActions.openModal({ type: 'pin-mismatch' }));
pin-mismatch is imho ok, if I remember correctly, it is a static modal, maybe it would require some copy changes. I am not sure.

2023-12-29 11:48 UTC, hynek-jina commented on packages/suite/src/actions/settings/deviceSettingsActions.ts
>              dispatch(modalActions.openModal({ type: 'pin-mismatch' }));
This way it was already defined in messages

2023-12-29 17:18 UTC, merged