fix: no backup modal
trezor/trezor-suite pull request #10650
Opened 2024-01-15 10:42 UTC by AdamSchinzel

## Description

Display no backup message in `DialogModal` instead of classic `Modal`.

Didn't want to introduce `DialogRenderer` again so counting with this component in #10601.

## Related Issue

Resolve #10615

## Screenshots:
![5A6E7E2B-8BF2-4111-B241-E1B07F92DD3B](https://github.com/trezor/trezor-suite/assets/66002635/76e70f0b-1707-4cbe-bbfb-bb693f58d237)

2024-01-15 14:42 UTC, komret approved these changes

2024-01-15 14:45 UTC, komret requested changes
All good except type check.

2024-01-16 09:49 UTC, AdamSchinzel commented
> All good except type check.

Fixed

2024-01-16 09:53 UTC, komret approved these changes

2024-01-16 09:54 UTC, merged