Feat/passwords edit
trezor/trezor-suite pull request #10661
Opened 2024-01-15 20:01 UTC by mroz22

very very very rough and unfinished implementation of passwords saving. more or less all the functionality is now in palce and now it ONLY needs some finetuning :D 

![image](https://github.com/trezor/trezor-suite/assets/30367552/d7e769d1-7dc9-471f-84ed-a99e36417590)

2024-06-25 11:05 UTC, komret requested changes

2024-06-25 11:05 UTC, komret commented on suite-common/metadata-types/src/metadataTypes.ts
> +    // legacy value, not used
```suggestion
```

2024-06-25 11:05 UTC, komret commented on packages/suite/src/hooks/suite/usePasswords.ts
>      const [selectedTags, setSelectedTags] = useState<Record<string, boolean>>({});
These should work like radio buttons, i.e. only one tag selected at a time.
_All_ should be graphically different from tags.
When now tag is selected, _All_ should be highlighted.

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/Tag.tsx
Please add an option to add a tag to a record, otherwise this functionality doesn't make sense.

2024-06-25 11:05 UTC, komret commented on packages/suite/src/actions/suite/metadataLabelingActions.ts
> +        const fetchIntervalTrackingId: FetchIntervalTrackingId = `labels-${selectedProvider.clientId}-${device.state}`;
This is repeated. Perhaps turn it into a util?

2024-06-25 11:05 UTC, komret commented on packages/suite/src/actions/suite/metadataPasswordsActions.ts
> +    const fetchIntervalTrackingId: FetchIntervalTrackingId = `passwords-${selectedProvider.clientId}-${device.state}`;
Repeated again.

2024-06-25 11:05 UTC, komret commented on packages/suite/src/actions/suite/metadataPasswordsActions.ts
> +        // const device = selectDevice(getState());
```suggestion
```

2024-06-25 11:05 UTC, komret commented on packages/suite/src/actions/suite/metadataProviderActions.ts
> +        Object.keys(fetchIntervals).forEach((id: FetchIntervalTrackingId) => {
Better than turning the check of IMO:

```suggestion
        (Object.keys(fetchIntervals) as FetchIntervalTrackingId[]).forEach((id: FetchIntervalTrackingId) => {
```

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordEntry.tsx
> +                {/* <img src={`https://logo.clearbit.com/${title}`} alt="logo" width="16" height="16" /> */}
```suggestion

```

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordManager.tsx
> +    const [formActive, setFormActive] = useState<undefined | number>();
I think this should use `null` rather than `undefined`, as you are actively setting it.

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordEntry.tsx
> +    gap: 4px;
Please use `spacingsPx`.

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordEntry.tsx
> +    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
```suggestion
    grid-template-columns: repeat(5, 1fr);
```

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/EntryForm.tsx
> +    gap: 16px;
Please use `spacingsPx`.

2024-06-25 11:05 UTC, komret commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/TagsList.tsx
> +    gap: 4px;
Please use `spacingsPx`.

2024-06-25 11:05 UTC, komret commented on suite-common/wallet-core/src/device/deviceConstants.ts
Don't forget to add migration.

2024-06-25 13:33 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/EntryForm.tsx
> +    gap: 16px;
7c7216a654ddd70caa8d0067f15af728b3ed8a17

2024-06-25 13:33 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordEntry.tsx
> +    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
efb082740c2c5352b976c7a3ec01c38c656471f8

2024-06-25 13:33 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordEntry.tsx
> +    gap: 4px;
77492ebe15336c70e422e27c3f4843a443e366ef

2024-06-25 13:33 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/TagsList.tsx
> +    gap: 4px;
77492ebe15336c70e422e27c3f4843a443e366ef

2024-06-25 13:33 UTC, mroz22 commented on suite-common/metadata-types/src/metadataTypes.ts
> +    // legacy value, not used
e0853d65f82765dfc5f813e7bd41006d7268c9a7

2024-06-25 14:56 UTC, mroz22 commented on packages/suite/src/hooks/suite/usePasswords.ts
>      const [selectedTags, setSelectedTags] = useState<Record<string, boolean>>({});
signle select here 7f3125156d5196878428c6724611cb4978842e36

2024-06-25 14:57 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/Tag.tsx
editable tags here 899ec247948306cd0b137ede4cb2194e1472255e

2024-06-26 09:25 UTC, mroz22 commented on packages/suite/src/actions/suite/metadataPasswordsActions.ts
> +        // const device = selectDevice(getState());
31249b2b8385d5a5ee805af1be9b1cf40e003cc2

2024-06-26 09:25 UTC, mroz22 commented on packages/suite/src/actions/suite/metadataProviderActions.ts
> +        Object.keys(fetchIntervals).forEach((id: FetchIntervalTrackingId) => {
2d8f7ea575b1f7104f5c7213d7ffd1825698a501

2024-06-26 09:25 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordEntry.tsx
> +                {/* <img src={`https://logo.clearbit.com/${title}`} alt="logo" width="16" height="16" /> */}
40a5fac5a530a6c075cb12d94165d5f6ee849de5

2024-06-26 09:25 UTC, mroz22 commented on packages/suite/src/views/settings/SettingsDebug/PasswordManager/PasswordManager.tsx
> +    const [formActive, setFormActive] = useState<undefined | number>();
2053f856ab7a748f96d5e33de165be86aef5d09d

2024-06-26 09:25 UTC, mroz22 commented on suite-common/wallet-core/src/device/deviceConstants.ts
b5a4c6f38a15817526471075e2120333067cfb01

2024-06-26 09:25 UTC, mroz22 commented on packages/suite/src/actions/suite/metadataPasswordsActions.ts
> +    const fetchIntervalTrackingId: FetchIntervalTrackingId = `passwords-${selectedProvider.clientId}-${device.state}`;
4759e0f377d9639e7770e0477951d9fe5238acf9

2024-06-26 09:25 UTC, mroz22 commented on packages/suite/src/actions/suite/metadataLabelingActions.ts
> +        const fetchIntervalTrackingId: FetchIntervalTrackingId = `labels-${selectedProvider.clientId}-${device.state}`;
4759e0f377d9639e7770e0477951d9fe5238acf9

2024-06-26 12:02 UTC, komret approved these changes

2024-06-26 13:23 UTC, merged