fix: UI bugs
trezor/trezor-suite pull request #10691
Opened 2024-01-17 11:56 UTC by AdamSchinzel

## Description

Addresses several issues with Suite empower.

## Related Issue

Resolve #10587
Resolve #10522
Resolve #10587
Resolve #10108

## Screenshots:
![ED0400C8-17B2-46DD-A5BB-6E1C6727080F](https://github.com/trezor/trezor-suite/assets/66002635/d3bd0eef-df45-43b0-9137-511491deb340)
(Will add more)

2024-01-17 17:45 UTC, dahaca requested changes

2024-01-17 17:45 UTC, dahaca commented on packages/components/src/components/Card/Card.tsx
[The issue](https://github.com/trezor/trezor-suite/issues/10383) was not about _removing_ the `small` padding type but simply making `large` the default 🙏  As it seemed to me there were more instances of cards with `paddingType="large"` than `paddingType="small"`

2024-01-17 17:45 UTC, dahaca commented on packages/suite/src/components/suite/WebUsbButton.tsx
> +        <Tooltip content={<Translation id="TR_CHECK_FOR_DEVICES" />}>
As we discussed, feel free to update the `IconButton` component in this PR, so that the `Tooltip` is rendered if a `label` prop passed, rename the existing `label` prop to `bottomLabel` :)  And please include [the delay](https://github.com/trezor/trezor-suite/blob/89834958042c4e046a0d8faf4e316b3ca37066e7/packages/suite/src/components/suite/Preloader/SuiteLayout/NavigationBar/NavigationActions/ActionItem.tsx#L196)

2024-01-17 17:45 UTC, dahaca commented on packages/components/src/components/Timerange/Timerange.tsx
I would close [the issue](https://github.com/trezor/trezor-suite/issues/10529) as a part of the PR but the story is far from being over, as many other places which have not been mentioned should be updated. I do not think it's time to update it all now. I have already asked for more clarification regarding the `secondary` type usage. 🫡

2024-01-17 17:45 UTC, dahaca commented on packages/components/src/components/Card/Card.tsx
Also, there are type errors now in [some components](https://github.com/trezor/trezor-suite/blob/035475f84f436d349811ecb81709ac069dc17aa3/packages/suite/src/views/wallet/send/components/TotalSent.tsx#L73), since `large` is gone. 

I'd say, you can keep `default = spacings.lg` and `small = spacings.sm`.

2024-01-18 09:33 UTC, AdamSchinzel commented on packages/components/src/components/Timerange/Timerange.tsx
Okey makes sense

2024-01-18 09:43 UTC, AdamSchinzel commented on packages/components/src/components/Card/Card.tsx
535dca1a5f88c85c40427e4bb45aeb0cd76be6e3

2024-01-18 09:43 UTC, AdamSchinzel commented on packages/components/src/components/Timerange/Timerange.tsx
34ee63187ec5953d80d909960decadf84f39c217

2024-01-18 09:56 UTC, AdamSchinzel commented on packages/suite/src/components/suite/WebUsbButton.tsx
> +        <Tooltip content={<Translation id="TR_CHECK_FOR_DEVICES" />}>
1672076e0dfc442f8263f2e18885918a3c17d9ff

2024-01-20 16:52 UTC, dahaca commented on packages/components/src/components/Timerange/Timerange.tsx
Just for clarity, I did not mean to revert the changes, but that the aforementioned issue should be linked _(already done!)_ and that we should not care much about all the other buttons in this PR but create appropriate issues later! ;)

2024-01-20 19:29 UTC, dahaca approved these changes
I have rebased and added a couple commits as well, feel free to check before squashing :)

2024-01-20 19:29 UTC, dahaca commented on packages/suite/src/components/suite/CoinList/Coin.tsx
🔥 ❗

2024-01-20 19:29 UTC, dahaca commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AdvancedCoinSettingsModal/CustomBackends/CustomBackends.tsx
> +                )}
IMO wasn't as smooth, so I changed slightly 🙏 279dfe50ee88fca1c6f108c828373222351a7ac6

2024-01-20 19:29 UTC, dahaca commented on packages/suite/src/components/suite/WebUsbButton.tsx
> +        <Tooltip content={<Translation id="TR_CHECK_FOR_DEVICES" />}>
Thanks! Definitely a useful addition. I have also adjusted storybook a tiny bit 4fd17646c8040d2b842b688e2a244bf23ee72ef5

2024-01-22 11:53 UTC, merged