Test/enable maestro in ci
trezor/trezor-suite pull request #10829
Opened 2024-01-26 01:27 UTC by ondracja

testing a separate github flow

2024-01-26 06:58 UTC, juriczech commented on .github/workflows/suite-native_develop_ci.yml
Why are these workflows deleted?

2024-01-29 19:55 UTC, ondracja commented on .github/workflows/suite-native_develop_ci.yml
Pls ignore this PR for now, it is not to be merged at all, I only use it as an isolated env to test out the maestro gha flow.

2024-01-29 19:55 UTC, ondracja commented on .github/workflows/suite-native_develop_ci.yml
I deleted the rest in order to not trigger them all the time and to waste gh minutes.

2024-01-29 20:39 UTC, Nodonisko commented on .github/workflows/maestro-dev.yaml
> +        script: ./gradlew assembleDebug && adb install ./app/build/outputs/apk/dev/debug/app-dev-debug.apk && maestro test .maestro/importBTCviaText.yaml
this will work 
```
script: adb install ./testAPKFolder/app-dev-debug.apk && maestro test .maestro/importBTCviaText.yaml
```

2024-01-31 08:00 UTC, mroz22 requested changes
please follow jobs naming convention 
<img width="317" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/57421f27-59ae-41c3-8c13-f00d4a1d5d5a">

2024-01-31 08:15 UTC, PeKne commented
@mroz22 Sorry did not know about this convention. Fixed.

2024-01-31 22:19 UTC, vdovhanych commented
Why are you using macos runner?

2024-02-01 08:16 UTC, PeKne commented on .github/workflows/maestro-dev.yaml
> +name: Run maestro tests
```suggestion
name: "[Test] Run maestro tests"
```

2024-04-02 11:41 UTC, ondracja commented
Obsolete PR.

2024-04-02 11:41 UTC, closed without merging