WIP
trezor/trezor-suite pull request #10901
Opened 2024-01-30 10:24 UTC by peter-sanderson

## Description

## Related Issue

Resolve 

## Screenshots:

2024-01-30 18:00 UTC, dahaca requested changes
* the incorrect spacings mentioned in the issue are still there
* acc name `font-weight` 
* search corner rounding

<img width="257" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/14f5cff6-bb06-43c4-9f02-1ba1b89e5875">

2024-01-30 18:00 UTC, dahaca commented on packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountItem.tsx
<img width="848" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/b4491bc5-31d7-4907-af0d-3ac953bba43e">

2024-01-30 18:00 UTC, dahaca commented on packages/components/src/components/animations/AnimationPrimitives.tsx
for the future, when changing something global, it's always a good idea to scope all the changes to a separate commit 🙏

2024-01-30 18:00 UTC, dahaca commented on packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
<img width="688" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/c1002b81-9ca4-46b1-bbfc-94144617cc33">

2024-01-30 18:00 UTC, dahaca commented on packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
Probably because of this: 
<img width="127" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/dd5996bf-6fc0-40f3-86b3-d4e1fbee2cbb">

2024-01-30 18:00 UTC, dahaca commented on packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountItem.tsx
[Figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31386&mode=design&t=elWpjqeJQMRQOqd9-1)

2024-01-31 09:42 UTC, peter-sanderson commented on packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
Good catch! https://github.com/trezor/trezor-suite/pull/10901/commits/d16a7cc333f78f7f61d84c50c7d3abbdede1b9e8

2024-01-31 09:43 UTC, peter-sanderson commented on packages/components/src/components/animations/AnimationPrimitives.tsx
Yea, its kinda hard to separate when I am falling down the rabbit hole as I work on the issue, but ill try

2024-01-31 09:50 UTC, peter-sanderson commented on packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountItem.tsx
![image](https://github.com/trezor/trezor-suite/assets/152899911/18405e3a-170c-4e23-86e3-d131c9f0e599)

2024-01-31 12:53 UTC, dahaca commented on packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
Any did you leave `size` in `LottieAnimation`? The other 2 animations components have `width` and `height`, right?

2024-01-31 16:31 UTC, dahaca commented
More improvements pushed, as promised!

2024-01-31 16:40 UTC, dahaca approved these changes

2024-02-01 10:23 UTC, merged