chore(suite): hide polygon trade in trade section
trezor/trezor-suite pull request #11087
Opened 2024-02-07 13:50 UTC by tomasklim

## Description

- hide polygon missing MATIC banner when not in debug mode
- hide add polygon account when not in debug mode

## Screenshots:

**debug mode**
![Screenshot 2024-02-07 at 14 49 13](https://github.com/trezor/trezor-suite/assets/33235762/79f71b9b-077b-4c56-8e44-93829503d462)
![Screenshot 2024-02-07 at 14 48 58](https://github.com/trezor/trezor-suite/assets/33235762/92d1b232-d862-4a33-9bb6-94c8a1fdeb74)

**no debug mode** 
![Screenshot 2024-02-07 at 14 49 38](https://github.com/trezor/trezor-suite/assets/33235762/93b1358f-35c9-42ba-8c72-1d996c15f720)
![Screenshot 2024-02-07 at 14 49 26](https://github.com/trezor/trezor-suite/assets/33235762/1eee0244-c376-4486-897a-c1734f57c44d)

2024-02-07 14:07 UTC, komret requested changes

2024-02-07 14:07 UTC, komret commented on packages/suite/src/hooks/wallet/useCoinmarketExchangeOffers.ts
> +    const isDebug = useSelector(state => state.suite.settings.debug.showDebugMenu);
```suggestion
    const isDebug = useSelector(selectIsDebugModeActive);
```

2024-02-07 14:07 UTC, komret commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
> +    const isDebug = useSelector(state => state.suite.settings.debug.showDebugMenu);
```suggestion
    const isDebug = useSelector(selectIsDebugModeActive);
```

2024-02-08 10:09 UTC, tomasklim commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
> +    const isDebug = useSelector(state => state.suite.settings.debug.showDebugMenu);
f131005898b5bc0d6fd743150cfc7ed0552f25e6

2024-02-08 10:09 UTC, tomasklim commented on packages/suite/src/hooks/wallet/useCoinmarketExchangeOffers.ts
> +    const isDebug = useSelector(state => state.suite.settings.debug.showDebugMenu);
f131005898b5bc0d6fd743150cfc7ed0552f25e6

2024-02-08 10:22 UTC, komret commented
/rebase

2024-02-08 10:22 UTC, komret approved these changes

2024-02-08 10:29 UTC, merged