feat(suite): change language on keyboard shortcut
trezor/trezor-suite pull request #11091
Opened 2024-02-07 14:22 UTC by tomasklim

## Description

- Allows to change languages by keyboard shortcut when in debug mode `Control + F7` and `Control + F9`. You have to use `fn` on mac to access function keys

## Related Issue

Resolves @MiroslavProchazka 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/33235762/389331bd-8b81-47dc-aeaa-56289862b3f3

2024-02-08 16:53 UTC, komret requested changes

2024-02-08 16:53 UTC, komret commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +    const language = useSelector(state => state.suite.settings.language);
```suggestion
    const language = useSelector(selectLanguage);
```

2024-02-08 16:53 UTC, komret commented on packages/suite/src/support/suite/Shortcuts.tsx
> +export const Shortcuts = () => {
I think there is no point in this component and the hook can be in `Main`.

2024-02-08 16:53 UTC, komret commented on packages/components/src/constants/keyboardEvents.ts
> +    FUNCTION_KEY_NINE = 'F9',
Why are these not next to each other?

2024-02-08 16:53 UTC, komret commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +        }
```suggestion
        if (isDebug) {
            document.addEventListener('keydown', onLanguageKeys);
        } else {
             // removeEventListener method will do nothing if the specified listener does not exist on the target element
             document.removeEventListener('keydown', onLanguageKeys);
        }

```

2024-02-08 16:53 UTC, komret commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +            if (isDebug) {
Not sure about this but I think the condition shouldn't be here.

2024-02-12 11:35 UTC, tomasklim commented on packages/components/src/constants/keyboardEvents.ts
> +    FUNCTION_KEY_NINE = 'F9',
F7 is <|<| and F9 is |>|> 😆

2024-02-12 11:35 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +            if (isDebug) {
it can be there, but yea it does make sense

2024-02-12 11:57 UTC, tomasklim commented on packages/suite/src/support/suite/Shortcuts.tsx
> +export const Shortcuts = () => {
I wanted to prepare it for a future 😬 and push us little bit

2024-02-12 11:58 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +    const language = useSelector(state => state.suite.settings.language);
omg, I always copy those things from other places. When someone creates new selector, he should refactor it on other places

2024-02-12 12:10 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +            if (isDebug) {
69bedd1c220779a23617182b7a5e96c26187d02e

2024-02-12 12:10 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +        }
69bedd1c220779a23617182b7a5e96c26187d02e

2024-02-12 12:10 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +    const language = useSelector(state => state.suite.settings.language);
21a68a83517e7a001f92e4b24ed3e70aa91a1375

2024-02-12 12:11 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +    const language = useSelector(state => state.suite.settings.language);
https://github.com/trezor/trezor-suite/pull/11152 and PR changing all occurences of language

2024-02-12 12:56 UTC, komret commented on packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
> +    const language = useSelector(state => state.suite.settings.language);
Yeah, let's talk about it on code improvements.

2024-02-12 12:57 UTC, komret commented on packages/components/src/constants/keyboardEvents.ts
> +    FUNCTION_KEY_NINE = 'F9',
Not on my keyboard, but ok.

2024-02-12 13:00 UTC, komret commented on packages/suite/src/support/suite/Shortcuts.tsx
> +export const Shortcuts = () => {
In that case... it should be wrapped in `useShortcuts` instead as it is not affect the DOM. 🤓

2024-02-13 11:46 UTC, tomasklim commented on packages/suite/src/support/suite/Shortcuts.tsx
> +export const Shortcuts = () => {
😡 
12797ba63711a9ac9dcc13a68c0ba23613ce5278

2024-02-13 11:54 UTC, komret commented on packages/suite/src/support/suite/Shortcuts.tsx
> +export const Shortcuts = () => {
🙏

2024-02-13 11:54 UTC, komret approved these changes

2024-02-14 09:48 UTC, merged