fix: fiat input
trezor/trezor-suite pull request #11347
Opened 2024-02-27 12:15 UTC by AdamSchinzel

## Description

Various fixes to fiat input in send form and exchange section.

- Show fiat input next to crypto amount only if rates are available
- Refactored tokens fiat rates in trade section
- Send form fiat calculation when currency select inside changed

2024-02-27 17:07 UTC, tomasklim requested changes

2024-02-27 17:07 UTC, tomasklim commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/FiatSelect/index.tsx
>  const FiatSelect = () => {
This component is never visible for Ethereum in Exchange tab. Could you please check why?

2024-02-27 17:07 UTC, tomasklim commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
>  import styled, { css } from 'styled-components';
Would be nice to see fiat rate for tokens in exchange tab
![Screenshot 2024-02-27 at 17 51 52](https://github.com/trezor/trezor-suite/assets/33235762/10a7aa21-8d8c-4c2b-98f3-2e3451781c29)

2024-02-28 09:33 UTC, AdamSchinzel commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/FiatSelect/index.tsx
>  const FiatSelect = () => {
That is the inner addon for fiat input and it's visible for me.

<img width="645" alt="Screenshot 2024-02-28 at 10 33 03 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/72dfd170-48eb-4ce8-83a5-b9fae7cc0202">

2024-02-29 12:37 UTC, AdamSchinzel commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
>  import styled, { css } from 'styled-components';
dc58eeda11835004d72cd01148c33b83c37b237c

2024-02-29 12:37 UTC, AdamSchinzel commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/FiatSelect/index.tsx
>  const FiatSelect = () => {
Should be now fixed

2024-03-05 12:52 UTC, tomasklim approved these changes

2024-03-05 12:52 UTC, merged