feat(suite-desktop): Remove unused permission descriptions from Info.plist
trezor/trezor-suite pull request #11607
Opened 2024-03-15 14:29 UTC by matejkriz

## Description

Electron add those by default https://github.com/electron/electron/blob/3759e59bbda0ea9fe0660288b2f3e6ff8d139c56/shell/browser/resources/mac/Info.plist#L49 It doesn't mean that app requests for those permissions. But it can confuse some people if they check the source code.

Notes for @trezor/qa:
Please test Mac version, scanning QR code

2024-03-15 14:32 UTC, prusnak requested changes, later dismissed

2024-03-15 14:32 UTC, prusnak commented on packages/suite-desktop/electron-builder-config.js
> +            NSCameraUsageDescription: 'Trezor Suite needs access to the camera to scan QR code.',
Nitpick about wording:

```suggestion
            NSCameraUsageDescription: 'Trezor Suite requires camera access for QR code scanning.',
```

2024-03-15 14:32 UTC, prusnak commented on packages/suite-desktop/electron-builder-config.js
> +            // Delete those keys from Info.plist, Electron add them by default but Suite don't need those permissions
grammar:

```suggestion
            // Delete those keys from Info.plist, Electron adds them by default but Trezor Suite does not need these permissions
```

2024-03-15 14:34 UTC, matejkriz commented on packages/suite-desktop/electron-builder-config.js
> +            // Delete those keys from Info.plist, Electron add them by default but Suite don't need those permissions
thank you!

2024-03-15 14:35 UTC, matejkriz commented on packages/suite-desktop/electron-builder-config.js
> +            // Delete those keys from Info.plist, Electron add them by default but Suite don't need those permissions
ee313843ab

2024-03-15 14:35 UTC, matejkriz commented on packages/suite-desktop/electron-builder-config.js
> +            NSCameraUsageDescription: 'Trezor Suite needs access to the camera to scan QR code.',
ee313843ab

2024-03-15 14:38 UTC, matejkriz commented
@szymonlesisz I am removing NSBluetoothAlwaysUsageDescription and NSBluetoothPeripheralUsageDescription here, but we might soon need those descriptions. If so, please add the appropriate messages to the bluetooth branch.

2024-03-19 09:56 UTC, komret approved these changes
Thanks!

2024-03-19 11:36 UTC, matejkriz commented
/rebase

2024-03-19 12:09 UTC, merged

2024-03-25 12:31 UTC, bosomt commented
**QA OK**

<img width="270" alt="Screenshot 2024-03-25 at 13 30 59" src="https://github.com/trezor/trezor-suite/assets/31506317/df2b2805-4dbb-406d-a013-f1f8699655a9">

**Info:**
 - Suite version: desktop 24.3.3 (1b6b0c29ca5982930ac65e23be9014d76d6b8478)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.3 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33