Feat/everstake modal
trezor/trezor-suite pull request #11637
Opened 2024-03-19 11:16 UTC by shotgunofdeath

## Description

1. The waiting period in the "Confirm staking period" modal is now dynamic. (NB! Do not forget to switch to the prod API before release)
2. The Everstake modal is added.

## Related Issue

Resolve 
https://github.com/trezor/trezor-suite/issues/9267
https://github.com/trezor/trezor-suite/issues/11256

## Screenshots:
<img width="872" alt="Знімок екрана 2024-03-19 о 12 02 15" src="https://github.com/trezor/trezor-suite/assets/42133844/70b24c8a-3e70-4d8a-a299-4147558df1df">
<img width="872" alt="Знімок екрана 2024-03-19 о 12 01 25" src="https://github.com/trezor/trezor-suite/assets/42133844/4680f565-2588-4dac-b189-b2d8b52bce3e">

2024-03-19 11:24 UTC, sime commented
> NB! Do not forget to switch to the prod API before release)
@shotgunofdeath @tomasklim https://github.com/trezor/trezor-suite/issues/11407#issuecomment-1999236771

Can we have both staging and production endpoints in the app?

2024-03-19 11:39 UTC, shotgunofdeath commented
Yes, we can. The staging API might be used for Goerli/Holesky and the prod one for real ETH

2024-03-19 11:50 UTC, sime commented
@shotgunofdeath Can that be included in this PR? Or is it off-topic ?

2024-03-19 12:04 UTC, shotgunofdeath commented
@sime I surely can. Just not sure when exactly

2024-03-19 15:42 UTC, tomasklim requested changes

2024-03-19 15:42 UTC, tomasklim commented on packages/suite/src/support/messages.ts
> +    },
Please merge those separated strings into one and use similar logic to e.g. translation `TR_MOBILE_APP_PROMO_TEXT_FOOTER`

```
  <Translation
      values={{ h: text => <HeadingAccent>{text}</HeadingAccent> }}
      id="TR_STAKE_YOUR_FUNDS_MANAGED"
  />

    TR_STAKE_YOUR_FUNDS_MANAGED: {
        id: 'TR_STAKE_YOUR_FUNDS_MANAGED',
        defaultMessage: 'Your staked funds are <h>managed by Everstake<h>',
    },
```

2024-03-19 15:47 UTC, tomasklim commented
@sime does it makes sense to have staging url for testnets? I think we do not care about APY there and validator's queue, but I dont know

but sure it is easy to change it to use staging for testnets only, and prod for mainnet, i can do that right away

2024-03-19 16:14 UTC, tomasklim commented
efb62547a051a06b034bf765e8fcd3587c01b660 @shotgunofdeath does this make sense?

2024-03-19 18:10 UTC, sime commented
@tomasklim thinking about the staking delay etc. not just apy

2024-03-20 09:06 UTC, tomasklim commented on packages/suite/src/support/messages.ts
> +    },
@shotgunofdeath i will fix it

2024-03-20 09:19 UTC, tomasklim approved these changes

2024-03-20 09:48 UTC, shotgunofdeath commented
> [efb6254](https://github.com/trezor/trezor-suite/commit/efb62547a051a06b034bf765e8fcd3587c01b660) @shotgunofdeath does this make sense?

Yes, totally

2024-03-20 10:00 UTC, merged