feat(suite): add Debug Color mode (theme) to debug elevation
trezor/trezor-suite pull request #11646
Opened 2024-03-19 14:35 UTC by peter-sanderson

This PR adds a special color mode (hidden behind debug) for Elevation debugging.

2024-03-19 15:58 UTC, peter-sanderson commented on packages/suite/src/components/suite/layouts/LoggedOutLayout.tsx
> +        <ElevationContext baseElevation={-2}>
Top level of the app is `-2` so it next `useElevation` returns `-1` which is lowest visible level

2024-03-19 15:59 UTC, peter-sanderson commented on packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx
> +    const { elevation } = useElevation();
Because base level of the app is `-2` now, this will naturally return `-1`

2024-03-20 08:34 UTC, matejkriz requested changes
Upon a cursory review, it appears that we may need to implement some migration on suite-native and also update it within the settings.

2024-03-20 16:55 UTC, matejkriz commented
Confirmed, it really breaks the mobile app because of missing migration. Of course we can do the migration if there is a reason, but why do you change the name of the theme?

2024-03-21 09:14 UTC, peter-sanderson commented
@matejkriz My motivation was to unify it in the code. Where `light` was more predominant and I also feel its a better name for it.

2024-03-22 13:52 UTC, peter-sanderson commented on packages/components/src/components/ElevationContext/ElevationContext.stories.tsx
> +                                Elevation 2
![image](https://github.com/trezor/trezor-suite/assets/152899911/ee399322-f79f-4668-8641-eceddf81c1cc)

![image](https://github.com/trezor/trezor-suite/assets/152899911/724ca3e4-ba38-4f80-98a0-93253eb7100b)

2024-03-25 17:15 UTC, peter-sanderson commented
- [ ] Todo: test the welcome and logout screens

2024-03-26 12:18 UTC, matejkriz approved these changes

2024-03-26 12:19 UTC, matejkriz commented
suite-native part approved, I haven't checked the rest

2024-03-26 13:29 UTC, jvaclavik approved these changes
Good job 🎖️

🚢 it

2024-03-26 16:05 UTC, merged