(fix)Adjust support link in onboarding
trezor/trezor-suite pull request #11911
Opened 2024-04-05 20:59 UTC by MiroslavProchazka

Resolves [#3944](https://github.com/trezor/trezor-suite/issues/3944)

Please check and confirm that newly created parameter `TREZOR_SUPPORT_DEVICE_URL` could be used like this.

2024-04-05 21:12 UTC, komret reviewed
You'll need to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to pass the commit message check.

2024-04-05 22:24 UTC, MiroslavProchazka commented
I will fix the commit message on the second commit, however I can't crack why the `nx format:check`  is failing

2024-04-06 06:16 UTC, jvaclavik commented
> I will fix the commit message on the second commit, however I can't crack why the `nx format:check` is failing

It's not formatted properly. Just run `  yarn nx format` 

It should look like this:
```
export const TREZOR_SUPPORT_DEVICE_URL =
    'https://trezor.io/support/a/trezor-suite-doesn-t-see-my-device';
```

(Btw you can set it in your editor to do it automatically.)

2024-04-06 06:16 UTC, jvaclavik approved these changes

2024-04-06 11:10 UTC, tomasklim requested changes, later dismissed
please squash commits into one

2024-04-06 18:01 UTC, merged