Chore/token definitions move state
trezor/trezor-suite pull request #12250
Opened 2024-05-03 09:25 UTC by tomasklim

## Description

## Related Issue

closes #11506

## Screenshots:
![Screenshot 2024-05-03 at 11 24 57](https://github.com/trezor/trezor-suite/assets/33235762/f9d57069-bbbf-4485-9292-748641569eca)
![Screenshot 2024-05-03 at 11 25 26](https://github.com/trezor/trezor-suite/assets/33235762/5d50f7f9-7530-41b9-ab67-5b95d798e106)

2024-05-03 09:26 UTC, tomasklim commented
@trezor/suite-mobile would be nice if you check that it still works on mobile. Mainly because of this https://github.com/trezor/trezor-suite/pull/12250/commits/46ed9800ad381f6a26e0f0e40df677eec4cddb49

2024-05-06 08:18 UTC, PeKne requested changes
Looks good. Just a few malformed imports.

2024-05-06 08:18 UTC, PeKne commented on suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts
> +import { selectIsSpecificCoinDefinitionKnown } from '@suite-common/token-definitions/src/tokenDefinitionsSelectors';
```suggestion
import { selectIsSpecificCoinDefinitionKnown } from '@suite-common/token-definitions';
```

2024-05-06 08:18 UTC, PeKne commented on suite-common/wallet-core/src/transactions/transactionsReducer.ts
> +import { selectNetworkTokenDefinitions } from '@suite-common/token-definitions/src/tokenDefinitionsSelectors';
```suggestion
import { selectNetworkTokenDefinitions } from '@suite-common/token-definitions';
```

2024-05-06 08:18 UTC, PeKne commented on suite-common/wallet-core/src/transactions/transactionsThunks.ts
> +import { selectNetworkTokenDefinitions } from '@suite-common/token-definitions/src/tokenDefinitionsSelectors';
```suggestion
import { selectNetworkTokenDefinitions } from '@suite-common/token-definitions';
```

2024-05-06 08:18 UTC, PeKne commented on suite-native/discovery/src/discoverySelectors.ts
>  } from '@suite-common/wallet-core/src/accounts/accountsReducer';
this import is wrong. I know it is not your mistake, but could you fix it aswell please?
```suggestion
} from '@suite-common/wallet-core';
```

2024-05-06 11:24 UTC, tomasklim commented on suite-native/discovery/src/discoverySelectors.ts
>  } from '@suite-common/wallet-core/src/accounts/accountsReducer';
@PeKne All imports fixed, I unfortunately squashed it

2024-05-06 12:22 UTC, PeKne approved these changes

2024-05-07 11:18 UTC, merged