fix(suite): Fix tooltip on hover
trezor/trezor-suite pull request #12285
Opened 2024-05-06 13:15 UTC by jvaclavik

## Description

## Related Issue

Resolve 

## Screenshots:

2024-05-06 13:17 UTC, peter-sanderson approved these changes

2024-05-06 13:19 UTC, peter-sanderson requested changes
we need to figure out why this can be undefined and also verify that it is actually undefined

2024-05-06 16:02 UTC, peter-sanderson commented on packages/suite/src/views/view-only/ViewOnlyTooltip.tsx
> +        <>
is this fragment needed?

2024-05-06 16:05 UTC, peter-sanderson approved these changes

2024-05-06 20:11 UTC, merged

2024-05-07 13:38 UTC, bosomt commented
**QA OK**

**Info:**
 - Suite version: desktop 24.5.1 (a94f65e0a34ae30fc78759aabec64c0f99055a1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33