Hide older backup types onboarding 2
trezor/trezor-suite pull request #12652
Opened 2024-05-30 11:16 UTC by peter-sanderson

Design: 
![image](https://github.com/trezor/trezor-suite/assets/152899911/2ced5ce0-4ca3-406f-a73a-bd8dc52e98ee)

Screenshots from app:

**without collapsable legacy section:**
<img width="926" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/451b1fb6-1c2b-43ad-9a63-f667fbc5273d">

**with collapsable legacy section:**
<img width="927" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/8b4d2f7e-6574-48ab-b31a-08535b753a0e">

<img width="929" alt="image" src="https://github.com/trezor/trezor-suite/assets/858321/de9268ca-5da9-4182-8f55-4ded56f0e85c">

2024-05-30 12:32 UTC, peter-sanderson commented on packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx
> +    variant: 'none' | 'small' | 'large'; // @TODO: use `size` instead of `variant`
use `CollapsibleBoxVariant`

2024-05-30 12:34 UTC, peter-sanderson commented on packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx
> +            onToggle?.(!!isCollapsed); // !!, one for change of the state, the other for isCollapsed => isOpen
- make isOpen optional, 
- create managed and unmanaged mode for this component, 
- unify it as isOpen (`isCollapsed` is negative and unintuitive in combination with isOpen)

2024-05-30 12:34 UTC, peter-sanderson commented on packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx
> +                            onToggle?.(!!isCollapsed); // !!, one for change of the state, the other for isCollapsed => isOpen
tame this beast

2024-05-31 15:26 UTC, jvaclavik commented on suite-common/icons/src/webComponents/Icon.web.tsx
> +            onClick={e => {
TODO: check this

2024-06-03 14:54 UTC, peter-sanderson reviewed
![image](https://github.com/trezor/trezor-suite/assets/152899911/ed989b79-361e-46b9-8b85-7bcba857b60f)

cc @jvaclavik

2024-06-04 12:36 UTC, komret requested changes

2024-06-04 12:36 UTC, komret commented on packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx
> +export const ANIMATION_DURATION = 0.4;
unused export

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/FloatingSelections.tsx
> +const ShamirOptions = ({ defaultType, onSelect, selected }: ShamirOptionsProps) => (
Maybe move this to a separate file?

2024-06-04 12:36 UTC, komret commented on suite-common/icons/src/webComponents/Icon.web.tsx
> +                e.stopPropagation();
Can you add comments to each of these lines as to why it is needed? And possibly move it up to the body?

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/typesToLabelMap.ts
> +    'shamir-advance': 'TR_ONBOARDING_SEED_TYPE_ADVANCED',
Should be `shamir-advanced`?

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/SelectBackupType.tsx
> +    [DeviceModelInternal.T3T1]: 'shamir-default',
This could be a default option as we'll be adding more devices with this default.

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/SelectBackupType.tsx
> +    // Original package of Trezor Safe 3 have a card with just 12 words.
```suggestion
    // Original package of Trezor Safe 3 has a card with just 12 words.
```

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
> +                tags={<>{defaultType === '24-words' && <DefaultTag />}</>}
```suggestion
                tags={defaultType === '24-words' && <DefaultTag />}
```

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
> +                tags={<>{defaultType === '12-words' && <DefaultTag />}</>}
```suggestion
                tags={defaultType === '12-words' && <DefaultTag />}
```

2024-06-04 12:36 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/OptionWithContent.tsx
> +type OptionWithContentProps = {
Better if props are defined right above the component: https://www.notion.so/satoshilabs/Components-9159b639d21b43ef8b66be150854b6b6

2024-06-04 12:58 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
> +                tags={<>{defaultType === '24-words' && <DefaultTag />}</>}
Is this actually ever default? T1 doesn't go to this screen.

2024-06-04 13:12 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
> +                tags={<>{defaultType === '24-words' && <DefaultTag />}</>}
No, its just here for consistency / come crazy future

2024-06-04 13:14 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/OptionWithContent.tsx
> +type OptionWithContentProps = {
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:14 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
> +                tags={<>{defaultType === '12-words' && <DefaultTag />}</>}
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:14 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
> +                tags={<>{defaultType === '24-words' && <DefaultTag />}</>}
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:14 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/SelectBackupType.tsx
> +    // Original package of Trezor Safe 3 have a card with just 12 words.
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:15 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/SelectBackupType.tsx
> +    [DeviceModelInternal.T3T1]: 'shamir-default',
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:15 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/typesToLabelMap.ts
> +    'shamir-advance': 'TR_ONBOARDING_SEED_TYPE_ADVANCED',
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:15 UTC, peter-sanderson commented on suite-common/icons/src/webComponents/Icon.web.tsx
> +                e.stopPropagation();
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:15 UTC, peter-sanderson commented on packages/suite/src/views/onboarding/steps/SelectBackupType/FloatingSelections.tsx
> +const ShamirOptions = ({ defaultType, onSelect, selected }: ShamirOptionsProps) => (
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:15 UTC, peter-sanderson commented on packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx
> +export const ANIMATION_DURATION = 0.4;
https://github.com/trezor/trezor-suite/pull/12652/commits/e427179f62e266efc563e78250f6456935544e6a

2024-06-04 13:19 UTC, komret commented on packages/suite/src/views/onboarding/steps/SelectBackupType/SelectBackupType.tsx
> +    [DeviceModelInternal.T3T1]: 'shamir-default',
It's not done, is it? But optional anyway.

2024-06-04 13:20 UTC, komret approved these changes

2024-06-04 14:17 UTC, merged