feat(suite-native): passphrase form slide up button animation
trezor/trezor-suite pull request #12737
Opened 2024-06-05 08:39 UTC by PeKne

## Description
- ScrollViewContext that exposes the ScrollView ref created. It allows the trigger scroll methods imperatively.
- Passphrase submit button animation changed to slide up.
- Passphrase scrolls down on filling the passphrase input, so the confirm button that entered screen by animation is visible.

## Related Issue

Resolve #12618

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/758c15e4-0c27-45ad-a39f-fb6f5f99c617

2024-06-11 07:19 UTC, juriczech commented
At first glance LGTM. Let's wait for merge of https://github.com/trezor/trezor-suite/pull/12677 and then we'll do rebase. This will have to wait as discussed.

2024-06-12 14:02 UTC, juriczech commented on suite-native/module-passphrase/src/components/PassphraseFormInput.tsx
> +            <VStack style={applyStyle(formStyle)}>
Redundant VStack

2024-06-12 14:03 UTC, juriczech commented on suite-native/module-passphrase/src/components/PassphraseFormScreenWrapper.tsx
> +            <VStack spacing="medium" flex={1} style={{ paddingBottom: isDirty ? 70 : 0 }}>
Please explain why 70

2024-06-12 14:10 UTC, juriczech requested changes
Just some nits, but animation is glitchy on iOS and scrolls all content to the top and displays blank page.

2024-06-17 07:52 UTC, vytick commented on suite-native/module-passphrase/src/components/PassphraseFormInput.tsx
> +    onBlur?: () => void;
should onFocus and onBlur be optional?

2024-06-17 07:52 UTC, vytick commented on suite-native/module-passphrase/src/components/PassphraseFormScreenWrapper.tsx
> +    subtitle?: ReactNode;
optional not needed here

2024-06-17 07:52 UTC, vytick commented on suite-native/module-passphrase/src/components/PassphraseFormScreenWrapper.tsx
> +            <VStack spacing="medium" flex={1} style={{ paddingBottom: isDirty ? 70 : 0 }}>
should this be inline style?

2024-06-17 07:52 UTC, vytick commented on suite-native/module-passphrase/src/screens/PassphraseVerifyEmptyWalletScreen.tsx
> +                    <Text>
is the <text> needed there since AlertBox wraps title with that one already?

2024-07-12 12:42 UTC, closed without merging