fix(suite): change key for translation variable
trezor/trezor-suite pull request #12784
Opened 2024-06-07 10:35 UTC by komret

## Description

Fix key mismatch in translation.

## Screenshots:
![image](https://github.com/trezor/trezor-suite/assets/42465546/8441600d-d826-4005-aacb-2a800fcefd57)

2024-06-07 11:08 UTC, tomasklim requested changes
```
    TR_STAKE_DAYS: {
        id: 'TR_STAKE_DAYS',
        defaultMessage: '{count, plural, one {# day} few {# days} other {# days}}'
},
```

https://github.com/trezor/trezor-suite/pull/12742/files#r1631042071

2024-06-07 11:08 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/PayoutCard.tsx
> +                        <Translation id="TR_STAKE_DAYS" values={{ days: payout }} />
```suggestion
                        <Translation id="TR_STAKE_DAYS" values={{ count: payout }} />
```

2024-06-07 11:09 UTC, tomasklim commented on packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/PayoutCard.tsx
> +                        <Translation id="TR_STAKE_DAYS" values={{ days: payout }} />
Moreover, `TR_STAKE_DAYS` is used on 3 places

2024-06-07 11:27 UTC, peter-sanderson approved these changes

2024-06-10 11:47 UTC, komret commented
Should be resolved by the next Crowdin sync, closing.

2024-06-10 11:48 UTC, closed without merging