fix(suite): adapting automated tests to view-only
trezor/trezor-suite pull request #13188
Opened 2024-07-04 10:24 UTC by ondracja

- adding data-tests for view only
- adjusting tests and utilities to handle view only features

Removing following tests due to obsoleteness:
- tooltip
- passphrase-disabled

2024-07-04 10:25 UTC, jvaclavik approved these changes

2024-07-11 07:15 UTC, mroz22 requested changes

2024-07-11 07:15 UTC, mroz22 commented on packages/suite-web/e2e/tests/suite/passphrase-disabled.test.ts
> -        cy.task('setupEmu', { passphrase_protection: false });
is it obsolete? it can just happen that user connects a device with passphrase protection turned off

2024-07-11 14:23 UTC, ondracja commented on packages/suite-web/e2e/tests/suite/passphrase-disabled.test.ts
> -        cy.task('setupEmu', { passphrase_protection: false });
If `passphrase_protection` is set to false, there is no option to connect a hidden wallet.

2024-07-12 07:11 UTC, mroz22 commented on packages/suite-web/e2e/tests/suite/passphrase-disabled.test.ts
> -        cy.task('setupEmu', { passphrase_protection: false });
right, this test indeed is obsolete as it is. I would still suggest reworking it to testing something like this

1. add a passphrase wallet, 
2. turn off passphrase (need to be done outside of suite, I see that in device settings this option has disappeared once it is turned on). 
3. try to access account of a passphrase wallet and see that this is well handled 
![Uploading image.png…]()

2024-07-12 07:17 UTC, mroz22 commented on packages/components/src/components/Warning/Warning.tsx
> +    'data-test'?: string;
this really works? passing `data-tests` translates to `dataTest` on line 133? is it some react magic I am totally unaware of?

2024-07-12 07:17 UTC, mroz22 commented on packages/suite-web/e2e/support/utils/assertions.ts
> +    cy.getTestElement('@wallet/discovery-progress-bar', { timeout: 45_000 }).should('not.exist');
any reasons for this? is there something causing discovery to take longer?

2024-07-12 07:24 UTC, mroz22 commented on packages/suite-web/e2e/tests/analytics/toggle.test.ts
> +        cy.getTestElement('@viewOnlyTooltip/gotIt', { timeout: 15000 })
btw, why do we need 15 seconds here?

2024-07-12 07:25 UTC, mroz22 commented on packages/suite-web/e2e/tests/dashboard/assets.test.ts
> +    it.skip('checks that BTC and ETH accounts are available', () => {
iz skipped :(

2024-07-12 07:26 UTC, mroz22 commented on packages/suite-web/e2e/tests/dashboard/assets.test.ts
> +            needs_backup: true,
does this affect the test?

2024-07-12 07:29 UTC, mroz22 commented on packages/suite-web/e2e/tests/metadata/interval-fetching.test.ts
> +            cy.getTestElement('@analytics/continue-button', { timeout: 60_000 })
I wonder why such a big timeout. 🤔

2024-07-12 07:30 UTC, mroz22 commented on packages/suite-web/e2e/tests/metadata/wallet-metadata.test.ts
> +const firmwares = ['2.2.0', , '2-main'] as const;
A typo here `, ,`.

2024-07-12 07:32 UTC, mroz22 commented on packages/suite-web/e2e/tests/metadata/wallet-metadata.test.ts
> +const secondHiddenWalletState = 'mkx2Uqi3fmLHh8AHpQvAErTM3MZpzrmFr2@355C817510C0EABF2F147145:3';
interesting. I don't remember changing this in connect and if I remember correctly these are values returned from connect 🤔

2024-07-12 07:36 UTC, ondracja commented on packages/suite-web/e2e/support/utils/assertions.ts
> +    cy.getTestElement('@wallet/discovery-progress-bar', { timeout: 45_000 }).should('not.exist');
I've extended the timeout because some tests (can't remember which one was that atm) was sometimes timing out due to discovery not being finished. There is sometimes a noticeable period of "pre-discovery" where there is account skeleton component loading already but discovery bar is not visible yet.
<img width="1878" alt="image" src="https://github.com/user-attachments/assets/d191955c-ac23-4e46-9999-9418a693ffad">

2024-07-12 07:36 UTC, mroz22 commented on packages/suite-web/e2e/tests/settings/general.test.ts
> +        // cy.getTestElement('@onboarding/welcome', { timeout: 20000 }).should('be.visible');
I really don't like disabling tests to satisfy them with broken code :(

2024-07-12 07:36 UTC, ondracja commented on packages/suite-web/e2e/support/utils/assertions.ts
> +    cy.getTestElement('@wallet/discovery-progress-bar', { timeout: 45_000 }).should('not.exist');
On localhost, I didn't manage to catch it before it started but in CI, it happened.

2024-07-12 07:37 UTC, ondracja commented on packages/suite-web/e2e/tests/analytics/toggle.test.ts
> +        cy.getTestElement('@viewOnlyTooltip/gotIt', { timeout: 15000 })
Since this is a dynamic wait, I tend to use higher max timeouts just to be sure.

2024-07-12 07:37 UTC, mroz22 commented on packages/suite-web/e2e/tests/wallet/send-form-ltc.test.ts
> -        cy.prefixedVisit('/settings/coins');
btw navigating directly to an url doesn't work anymore? I  am seeing so many changes of this type.

2024-07-12 07:38 UTC, mroz22 commented on packages/suite-web/e2e/tests/wallet/send-form-regtest.test.ts
> +        cy.getTestElement('locktime-input').type('500');
btw what is the reason for this? :D

2024-07-12 07:39 UTC, mroz22 commented on packages/suite/src/views/suite/SwitchDevice/CardWithDevice.tsx
> +                    data-test="@testhjea"
testhjea

2024-07-12 07:40 UTC, mroz22 commented on packages/suite-web/e2e/support/utils/assertions.ts
> +    cy.getTestElement('@wallet/discovery-progress-bar', { timeout: 45_000 }).should('not.exist');
ok

2024-07-12 07:41 UTC, ondracja commented on packages/suite-web/e2e/tests/metadata/wallet-metadata.test.ts
> +const secondHiddenWalletState = 'mkx2Uqi3fmLHh8AHpQvAErTM3MZpzrmFr2@355C817510C0EABF2F147145:3';
The values I used are the ones I saw in Suite

2024-07-12 07:42 UTC, ondracja commented on packages/suite-web/e2e/tests/settings/general.test.ts
> +        // cy.getTestElement('@onboarding/welcome', { timeout: 20000 }).should('be.visible');
How would you like to proceed? There is an actual bug and test won't pass so we won't be able to merge anything.

2024-07-12 07:42 UTC, mroz22 commented on packages/suite-web/e2e/tests/settings/general.test.ts
> +        // cy.getTestElement('@onboarding/welcome', { timeout: 20000 }).should('be.visible');
If you really want to do this, ok, go ahead, but please create a new branch and a PR where the first commit would be enabling this again - and then somebody needs to fix it and already has a test-driven setup avaialable

2024-07-12 07:42 UTC, ondracja commented on packages/suite-web/e2e/tests/wallet/send-form-ltc.test.ts
> -        cy.prefixedVisit('/settings/coins');
Not at the moment, it breaks the `view-only` flow. I'll have a discussion with @jvaclavik to remedy this situation.

2024-07-12 07:44 UTC, ondracja commented on packages/suite-web/e2e/tests/wallet/send-form-regtest.test.ts
> +        cy.getTestElement('locktime-input').type('500');
Yes, with 100 value used in locktime, the button did not change to `sign` and stayed on `send`. I also smell something fishy that will need addressing in another issue 😄

2024-07-12 07:46 UTC, ondracja commented on packages/suite/src/views/suite/SwitchDevice/CardWithDevice.tsx
> +                    data-test="@testhjea"
typoo, removed.

2024-07-12 07:54 UTC, ondracja commented on packages/suite-web/e2e/tests/metadata/wallet-metadata.test.ts
> +const firmwares = ['2.2.0', , '2-main'] as const;
typoo, fixed.

2024-07-12 08:16 UTC, ondracja commented on packages/suite-web/e2e/tests/analytics/toggle.test.ts
> +        cy.getTestElement('@viewOnlyTooltip/gotIt', { timeout: 15000 })
lowered the wait to 10s

2024-07-12 08:16 UTC, ondracja commented on packages/suite-web/e2e/tests/dashboard/assets.test.ts
> +    it.skip('checks that BTC and ETH accounts are available', () => {
will discuss this further next week in another PR

2024-07-12 08:17 UTC, ondracja commented on packages/suite-web/e2e/tests/dashboard/assets.test.ts
> +            needs_backup: true,
will discuss this further next week in another PR

2024-07-12 08:18 UTC, ondracja commented on packages/suite-web/e2e/tests/suite/passphrase-disabled.test.ts
> -        cy.task('setupEmu', { passphrase_protection: false });
added a refactor note

2024-07-12 08:19 UTC, ondracja commented on packages/suite-web/e2e/tests/metadata/interval-fetching.test.ts
> +            cy.getTestElement('@analytics/continue-button', { timeout: 60_000 })
lowered to 30s

2024-07-12 08:34 UTC, ondracja commented on packages/suite-web/e2e/tests/wallet/send-form-regtest.test.ts
> +        cy.getTestElement('locktime-input').type('500');
skipped the test due to bug and created a TDD PR

2024-07-12 09:18 UTC, mroz22 approved these changes
left my comments, won't stop this from getting merged so that we are finally green, but please lets not degrade our tests by skipping too much or similar nasties

2024-07-12 11:08 UTC, merged