test(e2e): adjusting test cleanup method for better stability
trezor/trezor-suite pull request #13433
Opened 2024-07-19 11:56 UTC by ondracja

- omitting `Cache` folder from cleanup as there's sometimes an ongoing process that breaks the deletion in CI

2024-07-19 12:23 UTC, mroz22 requested changes

2024-07-19 12:23 UTC, mroz22 commented on packages/suite-desktop-core/e2e/support/common.ts
> +    const filesToDelete = fse.readdirSync(localDataDir);
lets reconcile with line 38-40

2024-07-22 06:46 UTC, ondracja commented on packages/suite-desktop-core/e2e/support/common.ts
> +    const filesToDelete = fse.readdirSync(localDataDir);
Moved to line 38.

2024-07-22 06:59 UTC, mroz22 approved these changes
ok, lets try if it is any better

2024-07-22 07:11 UTC, merged