move brightness settings for ts5 outside debug mode
trezor/trezor-suite pull request #13579
Opened 2024-07-31 15:01 UTC by MiroslavProchazka

Move brightness settings for t3t1 outside debug mode

![image](https://github.com/user-attachments/assets/08ff083e-790a-4216-96a9-4fecdc8836bd)

2024-07-31 17:26 UTC, komret requested changes

2024-07-31 17:26 UTC, komret commented on packages/suite/src/views/settings/SettingsDevice/Brightness.tsx
There is an incorrect `anchorId` from previous changes. If you don't want to create a new one (probably not necessary for this section), use `SectionItem` instead of `SettingsSectionItem`.

2024-07-31 17:31 UTC, komret commented
I am also missing the toast saying _Settings changed successfully_ which other options have, e.g. when changing homescreen.

2024-08-01 08:52 UTC, peter-sanderson commented on packages/suite/src/views/settings/SettingsDevice/Brightness.tsx
> +import { applySettings } from 'src/actions/settings/deviceSettingsActions';
I think its is unused import.

2024-08-01 08:58 UTC, peter-sanderson commented
@MiroslavProchazka that toast is just calling

```ts
dispatch(notificationsActions.addToast({ type: 'settings-applied' }));
```

Normally, settings use `applySettings` thunk (that also pops this toast up). This setting however does not use `applySettings` and I did not noticed the toast is missing.

2024-08-01 11:05 UTC, MiroslavProchazka commented
Unfortunately we cannot get error toast message, since FW is somehow not supporting this action. Se we've decided with @komret to not include toast notification for now, until it will be fixed on FW side.

2024-08-01 11:34 UTC, komret approved these changes

2024-08-01 11:34 UTC, merged

2024-08-01 13:09 UTC, bosomt commented
**QA OK**

T3T1 and T2T1 available
T2B1 unavailable 

**Info:**
 - Suite version: web 24.8.0 (e0f5e835d94b657933b127f232422a7910c87954)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.1 regular (revision 55473a0b4be7b22317cd0c401c938d430d86f29f)
 - Transport: BridgeTransport 2.0.32