Feat/checskum followup
trezor/trezor-suite pull request #13623
Opened 2024-08-02 15:22 UTC by enjojoy

followup for [PR](https://github.com/trezor/trezor-suite/pull/12998)

discussion [here](https://github.com/trezor/trezor-suite/pull/12453)

2024-08-03 12:59 UTC, enjojoy commented on packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
> +                    // const updatedValues = addValue(address); // Get updated values immediately
remove comment

2024-08-03 12:59 UTC, enjojoy commented on packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
> +    const inputState = () => {
change to getInputErrorState

2024-08-05 15:37 UTC, enjojoy commented
@jvaclavik contacted designers, because it seems like the design is not consistent and might be outdated.

2024-08-07 07:26 UTC, enjojoy commented
So it was decided to have there just a simple text with checkmark icon. No need to redesign bottom text, the screenshots I initially got were outdated design.

inputState should be disconnected from icon setting, because now with inputState changes the whole input field color and we don't want that.

2024-08-07 12:50 UTC, enjojoy commented
Blocked by waiting for an article about  EVM address checksum

2024-08-08 09:42 UTC, enjojoy commented
Requested copy review UPD: reviewed and confirmed

2024-08-09 12:13 UTC, tomasklim requested changes
This does not look nice 😢 
![Screenshot 2024-08-09 at 14 11 37](https://github.com/user-attachments/assets/c6b6c81a-6a53-46c6-b2b6-ea75f00614ce)

2024-08-09 12:13 UTC, tomasklim commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +                        icon={'EXTERNAL_LINK'}
It looks weird with this button.

How about using same style as e.g. marking phishing txs

![Screenshot 2024-08-09 at 14 05 13](https://github.com/user-attachments/assets/ea8c1e06-17d2-48a1-a80a-df9afaf4d12f)

(btw because of the link button being bigger than just text, whole form jumps when it is correctly checksummed

2024-08-09 12:13 UTC, tomasklim commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +    };
```suggestion
    const getBottomTextIcon = () => {
        if (hasAddressChecksummed) {
            return 'check';
        }
        
        return undefined;
    };
```

2024-08-09 12:13 UTC, tomasklim commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +                        //2. If the address is not checksummed at all and not found in blockbook.
```suggestion
                    // 1. If the address is used but unchecksummed, then Suite will automatically
                    // convert the address to the correct checksummed form and inform the user as described in the OP.
                    const result = await TrezorConnect.getAccountInfo(params); //TODO handle error
                    if (result.success) {
                        if (result.payload.history.total !== 0 && !checkAddressCheckSum(address)) {
                            setValue(inputName, toChecksumAddress(address), {
                                shouldValidate: true,
                            });
                            setHasAddressChecksummed(true);
                        }

                        // 2. If the address is not checksummed at all and not found in blockbook.
```

2024-08-09 12:13 UTC, tomasklim commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +                        //offer to checksum it with a button
```suggestion
                        // offer to checksum it with a button
```

2024-08-12 07:32 UTC, enjojoy commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +                        icon={'EXTERNAL_LINK'}
I think we've discussed it, now it's nice with this link being the same as the text right?

![image](https://github.com/user-attachments/assets/137f484d-2623-43d9-bda9-090b8a89a629)

2024-08-12 12:54 UTC, tomasklim commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +                                if (address === address.toLowerCase()) {
you can merge those two conditions

2024-08-12 12:55 UTC, tomasklim commented on packages/suite/src/views/wallet/send/Outputs/Address.tsx
> +    const online = useSelector(state => state.suite.online);
nit
```suggestion
    const isOnline = useSelector(state => state.suite.online);
```

2024-08-13 14:35 UTC, tomasklim approved these changes

2024-08-13 15:30 UTC, merged