fix(suite): do not enforce revision-check for install firwmare in settings
trezor/trezor-suite pull request #13727
Opened 2024-08-09 11:35 UTC by peter-sanderson

2024-08-09 11:45 UTC, komret requested changes

2024-08-09 11:45 UTC, komret commented on packages/suite/src/components/suite/Preloader/Preloader.tsx
> +const ROUTES_TO_SKIP_REVISION_CHECK: RouterAppWithParams['app'][] = [
Please add `firmware-type`.

2024-08-09 11:45 UTC, komret commented on packages/suite/src/components/suite/Preloader/Preloader.tsx
> +        (router.route?.app === undefined ||
Nit:

```suggestion
        (router.route?.app !== undefined &&
```

Isn't it more intuitive like this?

2024-08-09 14:18 UTC, komret approved these changes

2024-08-09 14:18 UTC, merged

2024-08-14 06:17 UTC, bosomt commented
**QA OK**

i was able to install custom firmware and install official firmware even app identifies device as compromised

**Info:**
 - Suite version: desktop 24.8.1 (ff36df61a0f4df46dfc9fbff1ac26f00429a00dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.2 regular (revision 4b68431f7cc04f5e0ae041e4bf2ddc82bba79cd3)
 - Transport: BridgeTransport 2.0.33