fix(suite): add missing coinmarket strings to en.json
trezor/trezor-suite pull request #13744
Opened 2024-08-09 17:20 UTC by MiroslavProchazka

Resolves https://github.com/trezor/trezor-suite/issues/13741

2024-08-10 13:43 UTC, tomasklim requested changes

2024-08-10 13:43 UTC, tomasklim commented on packages/suite-data/files/translations/en.json
>    "TR_COINJOIN_TILE_3_TITLE": "Protected by your Trezor",
WIP PR should be draft PR

2024-08-13 07:14 UTC, MiroslavProchazka commented on packages/suite-data/files/translations/en.json
>    "TR_COINJOIN_TILE_3_TITLE": "Protected by your Trezor",
solved

2024-08-13 07:25 UTC, tomasklim approved these changes

2024-08-13 07:25 UTC, merged