fix(staking): fee reserve advice when min amount
trezor/trezor-suite pull request #13797
Opened 2024-08-14 08:16 UTC by dev-pvl

## Description

Implemented a change to ensure the staking fee reserve advice is now shown, even when the minimum amount is typed.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13750

## Screenshots:
![recommendation_banner](https://github.com/user-attachments/assets/33d8b87c-a955-402d-8f78-08006851ff4a)

2024-08-19 15:45 UTC, tomasklim requested changes
Please squash it after change

2024-08-19 15:45 UTC, tomasklim commented on packages/suite/src/hooks/wallet/useStakeEthForm.ts
> +                cryptoValue.isGreaterThanOrEqualTo(MIN_ETH_AMOUNT_FOR_STAKING)
nit:
```suggestion
                cryptoValue.gte(MIN_ETH_AMOUNT_FOR_STAKING)
```

2024-08-20 07:33 UTC, dev-pvl commented on packages/suite/src/hooks/wallet/useStakeEthForm.ts
> +                cryptoValue.isGreaterThanOrEqualTo(MIN_ETH_AMOUNT_FOR_STAKING)
done

2024-08-21 12:34 UTC, tomasklim approved these changes

2024-08-21 12:41 UTC, merged