cypress
trezor/trezor-suite pull request #13857
Opened 2024-08-16 17:25 UTC by MiroslavProchazka

Changing the URL for Device authenticity fail + Firmware revision fail events, which will start dedicated chat-bot flow asking user to fill in several information rightaway.

2024-09-04 11:50 UTC, Lemonexe commented
Looks good to me, but as long as the new URL does not exist, I can't give approve.

2024-09-04 12:05 UTC, peter-sanderson approved these changes

2024-09-04 12:08 UTC, MiroslavProchazka commented
> Looks good to me, but as long as the new URL does not exist, I can't give approve.

The url will live in the upcoming days, the article is in the final phase. I wanted to add it to the upcoming suite release, so we dont need to cherry-pick it later. KB article can be published minutes before production release and it will work just fine,.

2024-09-04 12:45 UTC, komret requested changes
Please prefix the constant name with `TREZOR_SUPPORT_` and move it lower in the file among the other support URLs.

We already have [HELP_CENTER_FIRMWARE_REVISION_CHECK](https://trezor.io/learn/a/trezor-firmware-revision-check), which is used in the banner. Shouldn't it also be replaced with this one?

2024-09-04 14:18 UTC, Lemonexe approved these changes
> The url will live in the upcoming days, the article is in the final phase. I wanted to add it to the upcoming suite release, so we dont need to cherry-pick it later. KB article can be published minutes before production release and it will work just fine,.

Alright, I just wanted to check we don't accidentally merge something not working :slightly_smiling_face:

2024-09-05 15:40 UTC, MiroslavProchazka commented
> We already have [HELP_CENTER_FIRMWARE_REVISION_CHECK](https://trezor.io/learn/a/trezor-firmware-revision-check), which is used in the banner. Shouldn't it also be replaced with this one?

No, The goal is to create a separate article with a step-by-step guide on what users should do if they encounter the Ghost modal. A dedicated chatbot flow will begin as soon as the user lands on this specific URL. We decided not to use the existing article because it might alarm users who are casually browsing the knowledge base. The new article will not be indexed, so users should only access it by clicking the button on the Ghost modal, not through regular internet browsing.

2024-09-05 15:45 UTC, MiroslavProchazka commented
> Please prefix the constant name with `TREZOR_SUPPORT_` and move it lower in the file among the other support URLs.
> 
> We already have [HELP_CENTER_FIRMWARE_REVISION_CHECK](https://trezor.io/learn/a/trezor-firmware-revision-check), which is used in the banner. Shouldn't it also be replaced with this one?

edfbd1374506e705d6f015de7b5e1b675a73a6ad

2024-09-05 16:01 UTC, komret approved these changes

2024-09-05 16:02 UTC, merged