fix(staking): max with low amount
trezor/trezor-suite pull request #13931
Opened 2024-08-22 09:43 UTC by dev-pvl

## Description

Updated the logic to allow the use of the Max button even when the balance is less than 0.13 ETH. Also, the max button is now enabled when the user amount  is >=0.1 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13316

## Screenshots:
![image](https://github.com/user-attachments/assets/8df523ed-858a-4988-9cfd-034da9022886)

2024-10-08 16:23 UTC, tomasklim requested changes
I've clicked `Max`. Amount + fee is not 0.1 so I get error. However, I am getting the info banner that 0.03 ETH was left as reserve
![Screenshot 2024-10-08 at 18 22 28](https://github.com/user-attachments/assets/55dac629-4c68-4679-b575-7531a49a223f)

2024-10-08 16:31 UTC, tomasklim requested changes
I have less than `0.13`.
In normal circumstances we leave `0.03` for unstake and claim fees.
However, in this case we can't leave `0.03` but we leave maximum we can.

We need to modify the message in the banner. @jirih-stsh

![Screenshot 2024-10-08 at 18 24 19](https://github.com/user-attachments/assets/17dc2190-2da5-495c-823e-098918c9c3a2)

Any ideas? 
It is an edge-case so maybe just calculate what we left? (but thats maybe too complicated) 
So another option instead of amount to put there `some reserve`?

2024-10-09 11:51 UTC, tomasklim commented
btw there are type-check errors

2024-10-09 12:46 UTC, jirih-stsh commented
> I have less than `0.13`. In normal circumstances we leave `0.03` for unstake and claim fees. However, in this case we can't leave `0.03` but we leave maximum we can.
> 
> We need to modify the message in the banner. @jirih-stsh
> 
> ![Screenshot 2024-10-08 at 18 24 19](https://private-user-images.githubusercontent.com/33235762/374643881-17dc2190-2da5-495c-823e-098918c9c3a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzgwMDgsIm5iZiI6MTcyODQ3NzcwOCwicGF0aCI6Ii8zMzIzNTc2Mi8zNzQ2NDM4ODEtMTdkYzIxOTAtMmRhNS00OTVjLTgyM2UtMDk4OTE4YzljM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEyNDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjY2YjU4MjIwYTQ5ZDAxYWUxODRlYzU0NWM5Y2YxMmVlMzQwMTJkNDEzNGRmNGNjMWU5NjUxZDY3ZDY1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x_1h8pk3aPJmKcWT3d30pjomuCDHdRH2E7T7MJP72HA)
> 
> Any ideas? It is an edge-case so maybe just calculate what we left? (but thats maybe too complicated) So another option instead of amount to put there `some reserve`?


@tomasklim  since its an edge-case I would just go with the simpler option. 
So write something like: "We've left a small amount of ETH out so you can pay for withdrawal fees."

2024-10-16 09:00 UTC, dev-pvl commented
@tomasklim I hid the info banner when the error appeared. Another info banner is added when the amount is less than 0.13. Also, fixed type-check errors. https://github.com/trezor/trezor-suite/pull/13931/commits/ca67abd5c697d1e039fa6ba75fbfa01237b077dd

2024-10-17 14:20 UTC, tomasklim approved these changes

2024-10-17 14:38 UTC, merged