feat(coinmarket): v3 endpoints
trezor/trezor-suite pull request #14007
Opened 2024-08-28 14:58 UTC by FreeWall

2024-09-02 15:01 UTC, LukasRada requested changes

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/middlewares/wallet/__tests__/coinmarketMiddleware.test.ts
> +    };
No need of async/await
```suggestion
invityAPI.getInfo = () =>
    Promise.resolve({
        coins: {},
        platforms: {},
    });
```

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/middlewares/wallet/coinmarketMiddleware.ts
> +                    console.log(typeof invityAPI.getInfo());
Remove console.log

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/services/suite/invityAPI.ts
> +                trade as any,
We should not need `any` here (or anywhere else 😉)
```suggestion
                trade,
```

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/services/suite/invityAPI.ts
> +                tradeData as any,
We should not need `any` here (or anywhere else 😉)
```suggestion
                trade,
```

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/support/messages.ts
> -        id: 'TR_COINMARKET_CRYPTO_CATEGORY_E',
Is it safe to delete translations like this? (I dimly remeber there was an issue with similar approach @MiroslavProchazka)

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/types/coinmarket/coinmarket.ts
> +    sendCurrency: CryptoId | string | undefined;
If `CryptoId` is "more strict" string then we should not allow `string` here (or am I mistaken?)
```suggestion
    sendCurrency: CryptoId | undefined;
```

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/types/coinmarket/coinmarketOffers.ts
> +    sendCurrency: CryptoId | string | undefined; // TODO: ???
If `CryptoId` is "more strict" string then we should not allow `string` here (or am I mistaken?)
```suggestion
    sendCurrency: CryptoId | undefined;
```
And what should we do with the TODO?

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/utils/wallet/coinmarket/__fixtures__/coinmarketUtils.ts
> +                contract: '0x1234123412341234123412341234123412341234',
Why to update the contract? Was the value incorrect?

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx
> +                        <CoinmarketCoinLogo cryptoId={currency!} size={20} />
`currency!` is potentional bug because it allows to pass undefined to function `parseCryptoId` which would then throw an exception. We should probably not show any logo at all (show just placeholder?)

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx
> +                        <CoinmarketCoinLogo cryptoId={currency!} size={20} />
(Or we should state that currency is non-optional)

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsPrice.tsx
> +                {/*TODO: What is this? <CoinmarketUtilsTooltip quote={quote} />*/}
What should we do about this? Who to ask for help?

2024-09-02 15:01 UTC, LukasRada commented on packages/suite/src/views/wallet/coinmarket/exchange_new/components/ExchangeForm/CoinmarketExchangeOfferInfo.tsx
> +                            <CoinmarketCoinLogo cryptoId={send!} size={20} />
Potentional bug. `send` could be undefined.

2024-09-02 15:07 UTC, FreeWall commented on packages/suite/src/types/coinmarket/coinmarket.ts
> +    sendCurrency: CryptoId | string | undefined;
sendCurrency can be also fiat currency

2024-09-02 15:11 UTC, FreeWall commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsPrice.tsx
> +                {/*TODO: What is this? <CoinmarketUtilsTooltip quote={quote} />*/}
@adderpositive ?

2024-09-02 15:12 UTC, FreeWall commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx
> +                        <CoinmarketCoinLogo cryptoId={currency!} size={20} />
I don't think the curreny can be undefined here, I think this is invity-api typing problem, I mentioned that here: https://invityworkspace.slack.com/archives/C073S5J5E1Z/p1724777812312309

2024-09-02 15:23 UTC, FreeWall commented on packages/suite/src/utils/wallet/coinmarket/__fixtures__/coinmarketUtils.ts
> +                contract: '0x1234123412341234123412341234123412341234',
yes it was incorrect, but it wasn't used for filtering the result before, we used crypto symbols instead of contracts

2024-09-02 15:29 UTC, adderpositive commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsPrice.tsx
> +                {/*TODO: What is this? <CoinmarketUtilsTooltip quote={quote} />*/}
It is a component prepared for fee details. The comment can be deleted.

2024-09-02 15:31 UTC, adderpositive commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx
> +                        <CoinmarketCoinLogo cryptoId={currency!} size={20} />
Can we maybe just check, if the `currency` exists? It is also hard to easily see `currency!`. What do you think?

2024-09-02 15:35 UTC, LukasRada commented on packages/suite/src/views/wallet/coinmarket/exchange_new/components/ExchangeForm/CoinmarketExchangeOfferInfo.tsx
> +                            <CoinmarketCoinLogo cryptoId={send!} size={20} />
Same as https://github.com/trezor/trezor-suite/pull/14007#discussion_r1741053490

2024-09-02 18:03 UTC, MiroslavProchazka commented on packages/suite/src/support/messages.ts
> -        id: 'TR_COINMARKET_CRYPTO_CATEGORY_E',
Deleting is fine, just delete it in `messages.ts` and we will take over. The problem is while adding new strings, they have to be added both to `messages.ts` and `en.json`

2024-09-03 04:28 UTC, LukasRada approved these changes

2024-09-03 06:46 UTC, MiroslavProchazka approved these changes
We need to test this properly and observe that it does not break anything. So I'm approving it with keeping in mind that you will observe develop after merge and react promptly in case of any issues.

2024-09-03 11:07 UTC, merged