feat(suite-native): use enabled networks for msg system settings validation
trezor/trezor-suite pull request #14037
Opened 2024-08-30 09:16 UTC by vytick

Only show coin related messages to users with enabled coin.

I tested this locally.

## Related Issue

Resolve #13470

2024-08-30 14:14 UTC, matejkriz requested changes
It doesn't seem to be working for me.
<img width="322" alt="image" src="https://github.com/user-attachments/assets/6913ecb0-9b79-4725-8f58-10150af7a317">
<img width="373" alt="image" src="https://github.com/user-attachments/assets/c84ec8b3-01fd-43eb-966f-32be3d86158c">
<img width="376" alt="image" src="https://github.com/user-attachments/assets/e1195bf9-21be-4eb7-9700-51b0f0f33963">

2024-08-30 14:18 UTC, matejkriz commented on suite-native/message-system/src/messageSystemMiddleware.ts
>  const isAnyOfMessageSystemAffectingActions = isAnyOf(
This needs to be updated, it is now missing the actions changing enabled coins...

2024-08-30 20:08 UTC, vytick commented on suite-native/message-system/src/messageSystemMiddleware.ts
>  const isAnyOfMessageSystemAffectingActions = isAnyOf(
Good point! I was testing it via changing the message jws and didnt think of this obvious way 🙈 
ca22975ef8


https://github.com/user-attachments/assets/4969b43e-4a96-489c-9c4c-a3a3e27589d4

2024-09-02 14:17 UTC, matejkriz approved these changes

2024-09-02 16:33 UTC, vytick commented
/rebase

2024-09-02 20:01 UTC, vytick commented
/rebase

2024-09-02 21:19 UTC, merged