chore: update socks-proxy-agent from 6.1.1 to 8.0.4
trezor/trezor-suite pull request #14202
Opened 2024-09-09 06:21 UTC by karliatto

## Description
update socks-proxy-agent from 6.1.1 to 8.0.4

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14179

2024-10-15 12:27 UTC, karliatto commented
@marekrjpolak It would be nice if you have a look at this PR. I have made changes keeping in mind not to introduce breaking changes in connect API. Let me know what you think.

2024-10-15 14:11 UTC, mroz22 approved these changes
looks ok, did not test

2024-10-16 09:16 UTC, marekrjpolak requested changes
I repeatedly wasn't able to do a basic all seed discovery with Tor turned on. On current develop it was ok.

Also, do you know why is it necessary to pass the uri to the new SocksProxyAgent constructor as a string instead of object as noted [here](https://github.com/TooTallNate/proxy-agents/blob/main/packages/socks-proxy-agent/CHANGELOG.md#upgrading-from-5x-to-6x)? I've tried it and it required more fields than we have and than is shown in the example, but I have no idea why.

2024-10-17 06:28 UTC, karliatto commented
@marekrjpolak I probably broke it by trying to satisfy the types but I should work now with this latest change https://github.com/trezor/trezor-suite/pull/14202/commits/eb2eeee6dc5a6359b40410b36707575bde7b6f2c

As you mentioned using the other way it requires some fields that we do not use.  But they way I am using is the one they use in their tests https://github.com/TooTallNate/proxy-agents/blob/main/packages/socks-proxy-agent/test/test.ts#L34 and it should work now.

2024-10-17 08:42 UTC, marekrjpolak approved these changes
Ok, I've checked basic Ehtereum (multi-identity) discovery, Electrum backend on onion address and CJ discovery and all seems to be working. :+1: Still, I'm a bit paranoid whether the identities are correctly separated which is kinda hard to verify. But it's probably fine.

2024-10-17 08:49 UTC, karliatto commented
>  Still, I'm a bit paranoid whether the identities are correctly separated which is kinda hard to verify. But it's probably fine.


It is hard to verify in the complex context of suite, but it is quite straight forward using the simple node script below while Tor from suite running:

```javascript
import https from 'https';
import { SocksProxyAgent } from 'socks-proxy-agent';

const socksServerUrl = new URL(`socks://127.0.0.1:36133`);
socksServerUrl.username = 'user';
socksServerUrl.password = 'password';


const agent = new SocksProxyAgent(socksServerUrl);

https.get('https://ipinfo.io', { agent }, (res) => {
	console.log(res.headers);
	res.pipe(process.stdout);
});
```

With that script if you change user or password get different IP in response.

2024-10-17 10:20 UTC, merged