fix formatting of review txs value
trezor/trezor-suite pull request #14200
Opened 2024-09-07 12:02 UTC by ericvalcik

## Description

Fix wrapping of Coin/Token symbol in the `TransactionReviewSummary.tsx`.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13603

## Screenshots:

before:
<img width="864" alt="image" src="https://github.com/user-attachments/assets/1fda6ce6-0a5f-4578-a827-c2de45ce4be9">

after changes:
<img width="865" alt="image" src="https://github.com/user-attachments/assets/d3100cb2-8496-4b7a-ae21-ca78f127cda2">

2024-09-07 12:21 UTC, enjojoy commented
Please squash the commits and use conventional commits style for the commit message

2024-09-08 06:34 UTC, tomasklim requested changes
Hello, thanks for contribution. I suggest you to create branches in your fork instead of commiting to develop

2024-09-08 06:34 UTC, tomasklim commented on packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewSummary.tsx
> +    word-break: normal;
`break-word` would fit better.
Some tokens can have 18 decimals and amount can be also huge
<img width="323" alt="Screenshot 2024-09-08 at 8 17 51" src="https://github.com/user-attachments/assets/b010349e-5402-4f33-9eb0-94641c4cfa1e">

2024-09-08 06:34 UTC, tomasklim commented on packages/suite/src/components/suite/FormattedCryptoAmount.tsx
> +            {formattedSymbol && <BlurUrls text={' ' + formattedSymbol} />}
```suggestion
            {formattedSymbol && <>
              {' '}
              <BlurUrls text={formattedSymbol} />
            </>}
```
Something like that would look better

2024-09-09 13:08 UTC, ericvalcik commented
Thanks for the comments @tomasklim. I implemented the comments and also moved the changes to a different branch, which made me create a new PR, so please let's continue the review process here -> https://github.com/trezor/trezor-suite/pull/14216

2024-09-09 13:08 UTC, closed without merging