fix(coinmarket): send and verify modals
trezor/trezor-suite pull request #14230
Opened 2024-09-09 19:02 UTC by adderpositive

## Describe the bug
Instead of the currently selected Trezor account, the account from the **exchange form** should be selected.

## Expected behavior
You should be able to interact with an ETH account, not a Polygon account in the send modal.

## How to reproduce
1. Choose Polygon account
2. Go to Trade-Exchange
3. Choose `From` ETH
4. Choose `To` USDT and some `Amount` to proceed with the trade
5. Continue to `Confirm on Trezor & send` in the trade

## Screenshot
![image (1)](https://github.com/user-attachments/assets/759595df-11bf-4b35-ac8f-e79cc1004f56)
![image (2)](https://github.com/user-attachments/assets/84d0ca5d-2e63-4be0-aa14-3f3f6d9418b7)
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14218

2024-09-10 07:03 UTC, jvaclavik commented
<img width="801" alt="Screenshot 2024-09-10 at 09 01 53" src="https://github.com/user-attachments/assets/a71aea6b-7c40-493c-b598-92fcc0fdcf22">

Could you please delete this border? 🙏  (it shouldn't be white)

2024-09-10 07:18 UTC, jvaclavik requested changes
Don't understand the logic in detail, but I didn't spot any issues except the border color. Since you fix it I'm approving

2024-09-10 08:37 UTC, jvaclavik approved these changes

2024-09-10 09:11 UTC, LukasRada approved these changes

2024-09-10 10:42 UTC, komret requested changes
I'd prefer to do this without the useEffects, if possible. They are not linked to the modals closely enough and I am afraid that it could lead to future bugs where we expect the reducer value to be cleared while it is not. Perhaps the same result could be achived with props or middlewares.

2024-09-10 10:42 UTC, komret commented on packages/suite/src/reducers/wallet/selectedAccountReducer.ts
> +export const selectAccountIncludedChosenInCoinmarket = (
```suggestion
export const selectAccountIncludingChosenInCoinmarket = (
```

2024-09-10 10:42 UTC, komret commented on packages/suite/src/reducers/wallet/selectedAccountReducer.ts
> +    const storeAccount = selectedAccount.status === 'loaded' ? selectedAccount.account : undefined;
This is some additional logic that is not present in the originally used `selectSelectedAccount`, why did you add it?

Perhaps this selector could be simplified and return earlier:

```
    const { modalAccount } = state.wallet.coinmarket;

    if (modalAccount) {
        return modalAccount;
    }

    const selectedAccount = selectSelectedAccount(state);

    return selectedAccount;
```

2024-09-10 10:42 UTC, komret commented on packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketAccount.ts
> +    useEffect(() => {
Why is this necessary? Maybe it could be done with middleware?

2024-09-10 10:42 UTC, komret commented on packages/suite/src/hooks/wallet/coinmarket/offers/useCoinmarketCommonOffers.ts
> +    useEffect(() => {
This would perhaps be safer to do in middleware when the modal closes?

2024-09-11 08:06 UTC, komret commented
Great improvements and added unit tests 👏 

But note that some unit tests are failing.

2024-09-11 09:53 UTC, adderpositive commented
I have found one more bug. It should be ETH account, not BTC in exchange. 
![obrazek](https://github.com/user-attachments/assets/4042d1a2-f9a7-4a29-a6af-db33bd8fa45a)

2024-09-11 10:44 UTC, adderpositive commented
> I have found one more bug. It should be ETH account, not BTC in exchange. ![obrazek](https://private-user-images.githubusercontent.com/15160619/366401520-4042d1a2-f9a7-4a29-a6af-db33bd8fa45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDg3MjIsIm5iZiI6MTcyNjA0ODQyMiwicGF0aCI6Ii8xNTE2MDYxOS8zNjY0MDE1MjAtNDA0MmQxYTItZjlhNy00YTI5LWE2YWYtZGIzM2JkOGZhNDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5NTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZTBiODY4MDA5OTk4MzFmMjQ5NzY1MGYxNmZkYTk1MTBjOThmOTVlMmIwOTg0NTc5MDEwYzZjYTc5ZjI4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Urt4czYt2Rw8pNnWyfff9Ool8nXLpnp5iAt1uV8wCws)

should be fixed

2024-09-11 12:36 UTC, komret commented
/rebase

2024-09-11 13:11 UTC, komret approved these changes

2024-09-11 13:11 UTC, merged

2024-09-12 08:25 UTC, bosomt commented
**QA OK**

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0