feat(suite): disable tx bumpfee except lowestnonc
trezor/trezor-suite pull request #14395
Opened 2024-09-17 15:52 UTC by enjojoy

## Description

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13529

## Screenshots:

2024-09-18 11:23 UTC, enjojoy commented
Learn more link - https://trezor.io/learn/a/replace-by-fee-rbf-ethereum

2024-09-18 11:38 UTC, MiroslavProchazka commented
What about using "oldest pending transaction", instead of first? Does that make sense?

2024-09-18 15:42 UTC, Lemonexe reviewed
Codewise looks good, just some comments to make it neat.
And please, create the unit test if possible.

I didn't yet get to test it, then I'll finish the CR..

2024-09-18 15:42 UTC, Lemonexe commented on packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx
> +                                        </Tooltip>
I'd extract the tooltipped button to a new component (just here in this file), as the indentation is IMHO getting quite wild (gotta love prettier :smile:  ).

:thought_balloon:  Since the `Button` inside the `Tooltip` is almost the same, only changes are 1) being wrapped by `Tooltip` and 2) `isDisabled`, maybe there could be a wrapper component, which would either render
`<Tooltip ...>{children}</Tooltip>` or just `children`. But it's overkill to do it just to prevent duplication of four lines, so I'll leave that at your discretion :slightly_smiling_face:

2024-09-18 15:42 UTC, Lemonexe commented on suite-common/wallet-utils/src/transactionUtils.ts
> +        transactionGroups[dateKey].forEach(transaction => {
This code is fine, but it could be simplified :slightly_smiling_face: 

1. You can grab `Object.values` instead of `keys`
2. You can flatten the array, and avoid the nested `forEach`

```suggestion
    Object.values(transactionGroups)
        .flat()
        .forEach(transaction => {
```

2024-09-18 15:42 UTC, Lemonexe commented on suite-common/wallet-utils/src/transactionUtils.ts
> +};
Actually now that I played around with it, you could "simplify" it further using `.reduce`, though it's questionable if it makes it better readable :smile:  
This code should do the same. And that being said, **this function could do with tests** (you could use values from the `groupTransactionsByDate` test)

```
export const getTransactionWithLowestNonce = (
    transactionGroups: GroupedTransactionsByDate,
): WalletAccountTransaction | null =>
    Object.values(transactionGroups)
        .flat()
        .reduce<WalletAccountTransaction | null>((lowestNonceTransaction, transaction) => {
            const currentNonce = Number(transaction.ethereumSpecific?.nonce);
            if (
                lowestNonceTransaction === null ||
                currentNonce < Number(lowestNonceTransaction.ethereumSpecific?.nonce)
            ) {
                lowestNonceTransaction = transaction;
            }

            return lowestNonceTransaction;
        }, null);
```

2024-09-18 18:25 UTC, Lemonexe commented on suite-common/wallet-utils/src/transactionUtils.ts
> +            const currentNonce = Number(transaction.ethereumSpecific?.nonce);
:warning:  I just realized a problem here - for non-ethereum, this function returns the first transaction. I think it should return `null`, because it's an ethereum-only feature.
So I would add before this line: `if(!transaction.ethereumSpecific) return`

Or you could do it in `TransactionGroupedList` - don't call this function if `network.networkType !== 'ethereum'`

2024-09-18 18:27 UTC, Lemonexe requested changes
I tested it and it works correctly for ethereum-type networks :heavy_check_mark:
But it also disables button & displays tooltip for **non-ethereum** network txs (bitcoin testnet) :x:
I believe this is undesired, right?

2024-09-18 18:58 UTC, enjojoy commented
> I tested it and it works correctly for ethereum-type networks ✔️ But it also disables button & displays tooltip for **non-ethereum** network txs (bitcoin testnet) ❌ I believe this is undesired, right?

Yes, thank you, will fix that

2024-09-19 01:54 UTC, tomasklim commented
> What about using "oldest pending transaction", instead of first? Does that make sense?

Oldest by nonce, not by time

2024-09-19 09:36 UTC, enjojoy commented on packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx
> +                                        </Tooltip>
I just took it out in a variable so the indentation is not as crazy and It's better readable. If we'd have more occasions of buttons with tooltips, i think it'd be worth it creating a component for that.

2024-09-19 10:21 UTC, enjojoy commented on suite-common/wallet-utils/src/transactionUtils.ts
> +};
Thank you, that's big brain 🧠 Maybe it's a little less readable than using for each, but I like it

2024-09-19 10:33 UTC, enjojoy commented on suite-common/wallet-utils/src/transactionUtils.ts
> +            const currentNonce = Number(transaction.ethereumSpecific?.nonce);
I would do both for safety

2024-09-19 11:43 UTC, Lemonexe approved these changes
Thanks, it's working as expected :heavy_check_mark: 
Codewise looking great :rocket:

~`getTransactionWithLowestNonce` could do with unit tests~

2024-09-19 12:17 UTC, enjojoy commented
> Thanks, it's working as expected ✔️ Codewise looking great 🚀
> 
> `getTransactionWithLowestNonce` could do with unit tests, but oh well, I'm guilty of untested code too 😅 Can be done later 🤷

I pushed the tests 😼

2024-09-19 12:29 UTC, Lemonexe approved these changes
Good job adding the unit tests, now the code is a bit safer :+1:

2024-09-19 12:49 UTC, merged