refactor(coinmarket): replace useActions
trezor/trezor-suite pull request #14575
Opened 2024-09-27 10:29 UTC by adderpositive

## Description
Remove **deprecated** `useActions` from coinmarket hooks .

## Related
Resolve https://github.com/trezor/trezor-suite/issues/14574

2024-09-27 14:05 UTC, tomasklim requested changes
buy e2e tests are failing

2024-10-02 15:20 UTC, adderpositive commented
@tomasklim should be fine 🎉

2024-10-03 11:18 UTC, LukasRada approved these changes

2024-10-03 11:56 UTC, tomasklim approved these changes

2024-10-03 11:56 UTC, merged