chore(components): url icon update
trezor/trezor-suite pull request #14595
Opened 2024-09-27 19:38 UTC by MiroslavProchazka

Resolve: https://github.com/trezor/trezor-suite/issues/14520

<img width="1388" alt="image" src="https://github.com/user-attachments/assets/9a1a4481-b41e-47d9-a2c7-9d1193a67c4e">

2024-09-27 20:17 UTC, MiroslavProchazka commented
btw. don't we want `github` icon in the FW settings section?
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/834ee096-a8b0-479c-aeab-9581035f7efd">

2024-09-30 07:13 UTC, tomasklim requested changes, later dismissed
I think it is not changed everywhere

<img width="331" alt="Screenshot 2024-09-30 at 9 12 14" src="https://github.com/user-attachments/assets/4e60faf7-cb7b-4250-9b11-ca7b4da61810">

Do we really want to change the icon? I am not used to this icon from other apps 
![Screenshot 2024-09-30 at 9 12 58](https://github.com/user-attachments/assets/150bc616-3a90-400c-9908-fd5a53dd1c2c)

2024-09-30 09:53 UTC, MiroslavProchazka commented
> I think it is not changed everywhere
> 
> <img alt="Screenshot 2024-09-30 at 9 12 14" width="331" src="https://private-user-images.githubusercontent.com/33235762/371982099-4e60faf7-cb7b-4250-9b11-ca7b4da61810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTAzMTYsIm5iZiI6MTcyNzY5MDAxNiwicGF0aCI6Ii8zMzIzNTc2Mi8zNzE5ODIwOTktNGU2MGZhZjctY2I3Yi00MjUwLTliMTEtY2E3YjRkYTYxODEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA5NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZjhlODI1YWRmNjJjNGRlY2FmMDY2YjI5MWFjMTIzNGY5Y2IyYTA5ZjhhNTNlM2MxNzcxNDVmZjNmYzAxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EL43jl_PnUGyoHEW6pgmSXm9yZRsJTbK0HXf7erOz6E">
> Do we really want to change the icon? I am not used to this icon from other apps ![Screenshot 2024-09-30 at 9 12 58](https://private-user-images.githubusercontent.com/33235762/371982322-150bc616-3a90-400c-9908-fd5a53dd1c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTAzMTYsIm5iZiI6MTcyNzY5MDAxNiwicGF0aCI6Ii8zMzIzNTc2Mi8zNzE5ODIzMjItMTUwYmM2MTYtM2E5MC00MDBjLTk5MDgtZmQ1YTUzZGQxYzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA5NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NzYwNzYyOWUxOTg5OWFkMzNmZTM5MDg2N2Y3MGUwNjVkMDg4MjcyM2MzYmRlNjdkOTM4NmFlMjJlMzQxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lo6tAMdp1zPoC6ObO65hFIUZ7iSH9o8upGU7COnOeIE)

Resolved in e84af953c8424c24aac93d595f5e6fc5d8d4145e

2024-09-30 10:41 UTC, adamhavel approved these changes

2024-09-30 10:55 UTC, jvaclavik approved these changes

2024-09-30 19:37 UTC, merged