feat(suite): add coin selection prompt to empty passphrase wallet
trezor/trezor-suite pull request #14807
Opened 2024-10-11 08:20 UTC by adamhavel

## Screenshots:

2024-10-14 09:08 UTC, tomasklim requested changes
Networks overflow in case there is a lot of them activated
![Screenshot 2024-10-14 at 11 04 39](https://github.com/user-attachments/assets/6371e39f-5baa-49e4-abd0-4c3bca8924eb)
![Screenshot 2024-10-14 at 11 02 12](https://github.com/user-attachments/assets/bb32a5ec-2ad7-4716-a553-a8a202d87bef)

2024-10-15 08:57 UTC, Hermez-cz commented
> Networks overflow in case there is a lot of them activated ![Screenshot 2024-10-14 at 11 04 39](https://private-user-images.githubusercontent.com/33235762/376174926-6371e39f-5baa-49e4-abd0-4c3bca8924eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODI5MTcsIm5iZiI6MTcyODk4MjYxNywicGF0aCI6Ii8zMzIzNTc2Mi8zNzYxNzQ5MjYtNjM3MWUzOWYtNWJhYS00OWU0LWFiZDAtNGMzYmNhODkyNGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4NTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NDlhN2VkMTc2ODJlN2QyMDA3OWNlMTlkYTZhZTBlYzZkOTY3MTE2Yzk3Y2UxZWZhN2FkZmYwZDIyNjQxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hZZjQpVurG_s0xPk7l8fL_hA0vTvPg-c26XLxq30DVE) ![Screenshot 2024-10-14 at 11 02 12](https://private-user-images.githubusercontent.com/33235762/376174932-bb32a5ec-2ad7-4716-a553-a8a202d87bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODI5MTcsIm5iZiI6MTcyODk4MjYxNywicGF0aCI6Ii8zMzIzNTc2Mi8zNzYxNzQ5MzItYmIzMmE1ZWMtMmFkNy00NzE2LWE1NTMtYThhMjAyZDg3YmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4NTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5Mzg3NWM5ZmY3OTJiMWM5N2RhNGRmOTRhNDYzMDc2MGJiYzY2YmUwYTkzOTRkMzBkOTZjODBlY2JkMGExZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.99xuoBeTUVKPxta2ZYeDxYaW9BFUmNunF97sygEC29A)
> 
> Do we need different string for `Checked coins` and `Checked balances on:`?

Let's have `Checked balances on:` for both case please.

2024-10-16 09:46 UTC, enjojoy approved these changes
You have 2 linter warnings, and I added some nit comments. Other than that tested, previous comments seem to be implemented well.

LGTM🚀

2024-10-16 09:46 UTC, enjojoy commented on packages/components/src/components/Flex/Flex.tsx
> +    as?: string;
What is this needed for?

2024-10-16 09:46 UTC, enjojoy commented on packages/components/src/components/Icon/Icon.tsx
```js
const SVG = styled(ReactSVG)`
    display: flex;
    align-items: center;
    justify-content: center;

    div {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    path {
        transition:
            stroke 0.15s,
            fill 0.15s;
    }
` as typeof ReactSVG; 
```

Is it possible to partially replace it with Row or Column component with flex props?

2024-10-16 09:46 UTC, enjojoy commented on packages/suite/src/views/dashboard/PortfolioCard/PortfolioCard.tsx
>      align-items: center;
Can you replace it with Flex component?

2024-10-16 09:49 UTC, tomasklim approved these changes

2024-10-16 09:53 UTC, adamhavel commented on packages/components/src/components/Flex/Flex.tsx
> +    as?: string;
For semantic reasons, where I want the Row be for example a section or header HTML element.

2024-10-16 09:53 UTC, seibei-iguchi commented on packages/components/src/components/Icon/Icon.tsx
I think it wouldn't work in this case.

2024-10-16 12:42 UTC, merged