fix(suite): protocol
trezor/trezor-suite pull request #14920
Opened 2024-10-17 12:12 UTC by enjojoy

## Description

There was an issue that not all networks had a valid prefix, now typescript will check for each network to have a protocol, and if a new Network will be added, it will throw a type error that it doesn't have a protocol prefix assigned. Also now it's possible to have a list of prefixes for each NetworkSymbol.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14813

2024-10-17 15:15 UTC, tomasklim requested changes

2024-10-17 15:15 UTC, tomasklim commented on suite-common/suite-utils/src/protocol.ts
> +export const PROTOCOL_TO_NETWORK = {} as ProtocolToNetwork;
```ts
export const getNetworkSymbolForProtocol = (protocol: Protocol): NetworkSymbol | undefined => {
    for (const networkSymbol in NETWORK_TO_PROTOCOLS) {
        const protocols = NETWORK_TO_PROTOCOLS[networkSymbol as NetworkSymbol];
        if (protocols.includes(protocol)) {
            return networkSymbol as NetworkSymbol;
        }
    }

    return undefined;
};
```

2024-10-17 15:15 UTC, tomasklim commented on suite-common/suite-constants/src/protocol.ts
> +    tada: ['testcardano'],
same as network symbol

2024-10-18 13:57 UTC, tomasklim requested changes

2024-10-18 13:57 UTC, tomasklim commented on suite-common/suite-constants/src/protocol.ts
> +    dsol: ['solana', 'sol', 'dsol'],
```suggestion
    dsol: ['dsol'],
```

2024-10-18 13:57 UTC, tomasklim commented on suite-common/suite-constants/src/protocol.ts
> +    pol: ['polygon', 'matic'],
```suggestion
    pol: ['polygon', 'matic', 'pol'],
```

2024-10-18 13:57 UTC, tomasklim commented on suite-common/suite-constants/src/protocol.ts
> +    bnb: ['binance', 'bnb'],
```suggestion
    bnb: ['binance', 'bnb', 'bsc'],
```

2024-10-18 13:57 UTC, tomasklim commented on suite-common/suite-constants/src/protocol.ts
> +    tsep: ['sepolia', 'tsep'],
please only symbol for testnets, no sepolia, no holesky,...

2024-10-18 15:20 UTC, enjojoy commented
@trezor/qa To test it you can do few following things: 

### 1
When in web app, go to send section and scan QR code with a prefix of picked network. You can generate QR code in some mobile app and enter the address with network prefix as text. 

For example "binance:0x12312312313" (but the address has to be correct)

If the prefix is unknown, there will be an error toast
If the prefix belongs to another known network, there will be an error toast with the network it belongs to 
If the prefix is known and the network is right it should fill in the address

2024-10-18 20:41 UTC, tomasklim approved these changes

2024-10-18 21:03 UTC, merged