chore(suite): refactor coin market layout
trezor/trezor-suite pull request #15090
Opened 2024-10-28 17:19 UTC by adamhavel

## Screenshots:

2024-10-28 18:43 UTC, tomasklim requested changes
Confirmed on Trezor got broken
![Screenshot 2024-10-28 at 19 41 30](https://github.com/user-attachments/assets/860a203d-92e4-4ce8-9063-c7162e192bed)

2024-10-29 10:09 UTC, adderpositive requested changes
Thanks for deleting a lot of custom styles. I have found only a few small design issues otherwise is ok! 

1. Using InfoRow should be fixed this big padding.
![obrazek](https://github.com/user-attachments/assets/dad8860f-7a93-47e1-a62c-0fe2eea55299)
2. I like this improvement, it looks very good. Could you also add a label aligned with the box below?
![obrazek](https://github.com/user-attachments/assets/93259c4e-9e7c-40dc-a638-5a62e5a64810)
3. Big side spaces in sell
![obrazek](https://github.com/user-attachments/assets/f90dccd3-c42f-440f-b815-82f69dee977a)

2024-10-29 10:09 UTC, adderpositive commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsKyc.tsx
> +        <Banner icon="info" variant="info">
I would rather use the variant `warning` because it is a warning imho.

2024-10-29 10:11 UTC, adamhavel commented
> Thanks for deleting a lot of custom styles. I have found only a few small design issues otherwise is ok!
> 
> 1. Using InfoRow should be fixed this big padding.
>    ![obrazek](https://private-user-images.githubusercontent.com/15160619/381075076-dad8860f-7a93-47e1-a62c-0fe2eea55299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTY4OTcsIm5iZiI6MTczMDE5NjU5NywicGF0aCI6Ii8xNTE2MDYxOS8zODEwNzUwNzYtZGFkODg2MGYtN2E5My00N2UxLWE2MmMtMGZlMmVlYTU1Mjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZTAzZTczNDU5MTdkZDZkNWM1OGQ1ZjU4ODg4YTU2MmU1MmIwM2QyNDE1OTg3OGU0OWEzYTYzYTQ2YTVkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fz4mfnwxdGdBvFfo-knsCk_Tf2kMdJUm1K0KkQKE0JU)
> 2. I like this improvement, it looks very good. Could you also add a label aligned with the box below?
>    ![obrazek](https://private-user-images.githubusercontent.com/15160619/381075181-93259c4e-9e7c-40dc-a638-5a62e5a64810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTY4OTcsIm5iZiI6MTczMDE5NjU5NywicGF0aCI6Ii8xNTE2MDYxOS8zODEwNzUxODEtOTMyNTljNGUtOWU3Yy00MGRjLWE2MzgtNWE2MmU1YTY0ODEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NzUyZmU0YmY0OTU1YzgwNjU5MWRlMjg4NzExY2E5MjFmMmM5NzIxMGMyMjVmNDQwYTA1NWIyOTJlNmU3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LHmVPQRuM2rt2RKH8GwxYV3bq7BaLSI6Mu0GeO-2J0c)
> 3. Big side spaces in sell
>    ![obrazek](https://private-user-images.githubusercontent.com/15160619/381075289-f90dccd3-c42f-440f-b815-82f69dee977a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTY4OTcsIm5iZiI6MTczMDE5NjU5NywicGF0aCI6Ii8xNTE2MDYxOS8zODEwNzUyODktZjkwZGNjZDMtYzQyZi00NDBmLWI4MTUtODJmNjlkZWU5NzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjcyMDQ3YjY3MDI1ZmUwY2ExZGEyZGIxN2U3YWY1OGUwODU5YzBjMWRlNmJlZDFhNjEwZTM5NTlkODRjNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s8DaengUIRON88fCRjE3dLEkEuMOC0uKXM9iJQ7Cy-o)

The big paddings are in the sections I haven't yet managed to refactor, will probably finish it in the next PR, if that's ok:)

2024-10-29 10:12 UTC, adamhavel commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsKyc.tsx
> +        <Banner icon="info" variant="info">
I guess we should then use a different icon?

2024-10-29 11:01 UTC, adderpositive commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsKyc.tsx
> +        <Banner icon="info" variant="info">
@marek-andrsk

2024-10-29 11:03 UTC, adderpositive commented
> > Thanks for deleting a lot of custom styles. I have found only a few small design issues otherwise is ok!
> > 
> > 1. Using InfoRow should be fixed this big padding.
> >    ![obrazek](https://private-user-images.githubusercontent.com/15160619/381075076-dad8860f-7a93-47e1-a62c-0fe2eea55299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTY4OTcsIm5iZiI6MTczMDE5NjU5NywicGF0aCI6Ii8xNTE2MDYxOS8zODEwNzUwNzYtZGFkODg2MGYtN2E5My00N2UxLWE2MmMtMGZlMmVlYTU1Mjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZTAzZTczNDU5MTdkZDZkNWM1OGQ1ZjU4ODg4YTU2MmU1MmIwM2QyNDE1OTg3OGU0OWEzYTYzYTQ2YTVkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fz4mfnwxdGdBvFfo-knsCk_Tf2kMdJUm1K0KkQKE0JU)
> > 2. I like this improvement, it looks very good. Could you also add a label aligned with the box below?
> >    ![obrazek](https://private-user-images.githubusercontent.com/15160619/381075181-93259c4e-9e7c-40dc-a638-5a62e5a64810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTY4OTcsIm5iZiI6MTczMDE5NjU5NywicGF0aCI6Ii8xNTE2MDYxOS8zODEwNzUxODEtOTMyNTljNGUtOWU3Yy00MGRjLWE2MzgtNWE2MmU1YTY0ODEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NzUyZmU0YmY0OTU1YzgwNjU5MWRlMjg4NzExY2E5MjFmMmM5NzIxMGMyMjVmNDQwYTA1NWIyOTJlNmU3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LHmVPQRuM2rt2RKH8GwxYV3bq7BaLSI6Mu0GeO-2J0c)
> > 3. Big side spaces in sell
> >    ![obrazek](https://private-user-images.githubusercontent.com/15160619/381075289-f90dccd3-c42f-440f-b815-82f69dee977a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTY4OTcsIm5iZiI6MTczMDE5NjU5NywicGF0aCI6Ii8xNTE2MDYxOS8zODEwNzUyODktZjkwZGNjZDMtYzQyZi00NDBmLWI4MTUtODJmNjlkZWU5NzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjcyMDQ3YjY3MDI1ZmUwY2ExZGEyZGIxN2U3YWY1OGUwODU5YzBjMWRlNmJlZDFhNjEwZTM5NTlkODRjNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s8DaengUIRON88fCRjE3dLEkEuMOC0uKXM9iJQ7Cy-o)
> 
> The big paddings are in the sections I haven't yet managed to refactor, will probably finish it in the next PR, if that's ok:)

If you can make it before the freeze... 😄

2024-10-29 15:01 UTC, enjojoy commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsKyc.tsx
> +        <Banner icon="info" variant="info">
I think it makes sense to have it as info on DEX, because it just says that KYC is not required. In other cases I agree that it's more of a warning

2024-10-29 15:22 UTC, enjojoy approved these changes
LGTM, only please fix "Confirmed on Trezor" part mentioned by Tom, seems to be still broken

2024-10-29 17:41 UTC, adderpositive approved these changes
Please use fixups next time, it is easier to check the changes. 🙃

2024-10-29 17:42 UTC, adamhavel commented
> Please use fixups next time, it is easier to check the changes. 🙃

Sorry, the changes were minimal (change in one prop:) and I was lazy:D

2024-10-30 08:47 UTC, tomasklim approved these changes

2024-10-30 08:47 UTC, merged

2024-11-05 07:56 UTC, bosomt commented
**QA OK**

**Info:**
 - Suite version: web 24.11.0 (c58454703ba01107ffa6e7938e1608354342b26a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision 31d228a325b5968a2f3565b803818aaf7fa29bbb)
 - Transport: WebUsbTransport