fix(suite-common): add check for bitcoin-only firmware type
trezor/trezor-suite pull request #15139
Opened 2024-10-31 11:06 UTC by enjojoy

## Description

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10612

## Screenshots:

2024-10-31 11:58 UTC, Lemonexe approved these changes

2024-10-31 11:58 UTC, Lemonexe commented on suite-common/wallet-core/src/device/deviceReducer.ts
> +                device?.firmwareType === 'bitcoin-only' &&
Nit: you can use [hasBitcoinOnlyFirmware](https://github.com/trezor/trezor-suite/blob/bef8f3c4378237d4cf63580d4ab50756f56e3ec1/packages/device-utils/src/firmwareUtils.ts#L41)

2024-10-31 12:28 UTC, tomasklim requested changes

2024-10-31 12:28 UTC, tomasklim commented on suite-common/wallet-core/src/device/deviceReducer.ts
> +            if (hasBitcoinOnlyFirmware(device) && !['btc', 'test', 'regtest'].includes(symbol)) {
please try to reuse `['btc', 'test', 'regtest']` it is used on more places in codebase
look for `['btc', 'test', 'regtest']`, `['btc', 'test']`

2024-10-31 15:00 UTC, enjojoy commented
@trezor/qa Please test on different devices with different versions, both bitcoin only and universal

2024-11-02 10:22 UTC, tomasklim approved these changes

2024-11-04 04:43 UTC, merged