chore(suite): refactor coinmarket sections
trezor/trezor-suite pull request #15136
Opened 2024-10-31 10:39 UTC by adamhavel

## Screenshots:

### Before
<img width="1185" alt="Screenshot 2024-10-31 at 11 38 51" src="https://github.com/user-attachments/assets/3eade8d7-7e87-411f-b4ce-eb702a55ccb5">
<img width="452" alt="Screenshot 2024-10-31 at 11 38 31" src="https://github.com/user-attachments/assets/03e82bcc-b643-494c-a33f-75f725425c6f">

### After
<img width="1184" alt="Screenshot 2024-10-31 at 11 34 37" src="https://github.com/user-attachments/assets/f7779937-ae59-4be3-b9e9-06fb855064fa">
<img width="452" alt="Screenshot 2024-10-31 at 11 35 17" src="https://github.com/user-attachments/assets/f5d27f66-b872-4abe-ba12-06daa3b15ab8">

2024-10-31 11:02 UTC, peter-sanderson commented on packages/components/src/components/Card/Card.tsx
> +const Container = styled.div<{ $fillType: FillType } & TransientProps<AllowedFrameProps>>`
nit: export to type, sometimes this does issues on VSCode, but its not a big deal

2024-10-31 11:05 UTC, peter-sanderson commented on packages/components/src/components/form/SelectBar/SelectBar.tsx
> +const Options = styled.div<{
nit: export type

2024-10-31 11:05 UTC, peter-sanderson commented on packages/components/src/components/form/SelectBar/SelectBar.tsx
> +const Puck = styled.div<{ $optionsCount: number; $selectedIndex: number; $elevation: Elevation }>`
nit: export type

2024-10-31 11:07 UTC, peter-sanderson commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCurrency.tsx
> -    .react-select__value-container {
:clap:  :clap:  :clap: 
 
![image](https://github.com/user-attachments/assets/bb51b547-5ba0-4492-b032-b58c49b2bb64)

2024-10-31 11:16 UTC, peter-sanderson approved these changes
:clap: good job

2024-10-31 12:05 UTC, enjojoy commented
nit: I would add a line break after the first sentence 
![image](https://github.com/user-attachments/assets/59ecb91a-4e6c-4860-bd7b-7bf74af4396e)

2024-10-31 13:49 UTC, enjojoy approved these changes
Nice, so much custom styles eliminated

2024-10-31 14:23 UTC, adderpositive requested changes
Some details.

1. Is this expected? 

![obrazek](https://github.com/user-attachments/assets/e92c83b2-239a-4092-bade-11de67765174)

---

2. Can you unify these two labels? And also fix the component's background in dark mode?

![obrazek](https://github.com/user-attachments/assets/399cdb02-0153-44fe-b207-27763d28b7f1)
![obrazek](https://github.com/user-attachments/assets/4fea9a79-e204-48c1-96e2-81e29cacaa56)
![obrazek](https://github.com/user-attachments/assets/89aa1356-cb02-4893-9de7-2250833afba4)

---

The slippage component is very nice! I love it. Thank you for the improvements.

2024-10-31 14:25 UTC, adamhavel commented
> Some details.
> 
> 
> 
> 1. Is this expected? 
> 
> 
> 
> ![obrazek](https://github.com/user-attachments/assets/e92c83b2-239a-4092-bade-11de67765174)
> 
> 
> 
> ---
> 
> 
> 
> 2. Can you unify these two labels? And also fix the component's background in dark mode?
> 
> 
> 
> ![obrazek](https://github.com/user-attachments/assets/399cdb02-0153-44fe-b207-27763d28b7f1)
> 
> ![obrazek](https://github.com/user-attachments/assets/4fea9a79-e204-48c1-96e2-81e29cacaa56)
> 
> ![obrazek](https://github.com/user-attachments/assets/89aa1356-cb02-4893-9de7-2250833afba4)
> 
> 
> 
> ---
> 
> 
> 
> 3. Fix the buy test please.
> 
> 
> 
> ---
> 
> 
> 
> The slippage component is very nice! I love it. Thank you for the improvements. 
> 
> 

You're right about the 2. I'm not sure about the 1, it's part of the issue this PR is linked to. @tomasklim what do you think?

2024-10-31 14:50 UTC, tomasklim commented
> @tomasklim what do you think?

@adamhavel 
How about allowing it to go to the next line? And also please add `isBalance={false}` to component with `data-testid` equal to `@coinmarket/offers/quote/crypto-amount`. That will remove `...` which does not make any sense here. The `formatCoinBalance` method is something random 😀 
![Screenshot 2024-10-31 at 15 48 21](https://github.com/user-attachments/assets/8ab8e6a2-b8a1-4fa9-ace1-32a929fa63b9)

2024-10-31 15:01 UTC, tomasklim commented
No sorry, it is `CoinmarketFormOfferCryptoAmount`, just remove `isBalance` there

2024-11-01 12:10 UTC, adderpositive commented on packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOffer.tsx
> +                        data-testid="@coinmarket/form/compare-button"
Adding type="button" will fix the test

2024-11-01 13:44 UTC, adderpositive approved these changes

2024-11-01 14:13 UTC, merged