feat(components): move getAssetLogoUrl to asset-utils
trezor/trezor-suite pull request #15130
Opened 2024-10-30 20:17 UTC by vytick

## Description

## Related Issue

Resolve 

## Screenshots:

2024-10-31 13:36 UTC, vytick commented
/rebase

2024-10-31 14:36 UTC, vytick commented
/rebase

2024-10-31 16:21 UTC, Nodonisko requested changes
You need to modify also generate icons script it expects token folder to be present.

2024-10-31 16:21 UTC, Nodonisko commented on suite-native/icons/src/CryptoIcon.tsx
> +        const formattedAddress = getContractAddressForNetwork(symbol, contractAddress);
UseMemo

2024-10-31 19:20 UTC, vytick commented
> You need to modify also generate icons script it expects token folder to be present.

I don't see any reference to tokenIcons other than in MD file

2024-10-31 19:20 UTC, vytick commented
> You need to modify also generate icons script it expects token folder to be present.

@Nodonisko I don't see any reference to tokenIcons other than in MD file

2024-10-31 19:23 UTC, vytick commented on suite-native/icons/src/CryptoIcon.tsx
> +        const formattedAddress = getContractAddressForNetwork(symbol, contractAddress);
6f073ad407

2024-11-01 09:10 UTC, Nodonisko approved these changes
Yea, sorry I forget that token icons was generated manually

2024-11-01 09:39 UTC, vytick commented
/rebase

2024-11-01 12:16 UTC, merged