chore: Upgrade ESLint and all plugis & revalidate the config and ALL of the rules
trezor/trezor-suite pull request #15287
Opened 2024-11-06 21:14 UTC by peter-sanderson

This is PR that upgrades the ESLint and all its plugins + does refactoring of the whole configuration.

- Configuration is now written in modern flat format.
- Configuration is separated in `@trezor/eslint` but its used globally.
- Some packages, if they need to define custom rules will require it in `package.json` and then they can define their own config.
- Most of the newly recommended rules were introduced in previous mini-PRs (see the list [here](https://github.com/trezor/trezor-suite/issues/15196)
- I had to remove `no-shadow` rule, as it start reporting insane amount of stuff and it was hard to configure. I think we can solve it [separately](https://github.com/trezor/trezor-suite/issues/15311) in future PR.
- `eslint` is no longer executable per-package with `nx` you have to run it from the root-level only
- This PR also put huge emphases on local configuration first. So all package-specific ESLint configuration is moved to the package from the global space.  

I have written a bunch of comments in the PR itself to explain stuff. I hope it help you to do code-review.

------------------------------

## Performance:

Outcome of the `reset && find . -type f -name ".eslintcache" -delete && time TIMING=1  yarn lint:js`

### This PR:
```
Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
@typescript-eslint/no-unused-vars |  6837.371 |    18.5%
import/namespace                  |  4396.600 |    11.9%
import/no-extraneous-dependencies |  4294.112 |    11.6%
import/named                      |  3034.458 |     8.2%
react/no-direct-mutation-state    |  2487.796 |     6.7%
import/order                      |  2483.343 |     6.7%
import/no-duplicates              |  2017.597 |     5.5%
react/require-render-return       |   697.603 |     1.9%
react/jsx-no-target-blank         |   518.672 |     1.4%
padding-line-between-statements   |   420.811 |     1.1%
TIMING=1 yarn lint:js  107,03s user 5,38s system 156% cpu 1:11,84 total

```

### `develop`

```
Rule                                     | Time (ms) | Relative
:----------------------------------------|----------:|--------:
import/order                             |  2306.349 |    21.9%
import/no-extraneous-dependencies        |  1772.432 |    16.9%
@typescript-eslint/no-unused-vars        |  1282.584 |    12.2%
import/no-duplicates                     |   409.478 |     3.9%
jest/no-standalone-expect                |   331.732 |     3.2%
react/jsx-no-target-blank                |   312.352 |     3.0%
mdx/remark                               |   295.082 |     2.8%
padding-line-between-statements          |   244.067 |     2.3%
@typescript-eslint/no-restricted-imports |   198.185 |     1.9%
react/no-render-return-value             |   187.968 |     1.8%
TIMING=1 yarn lint:js  44,93s user 1,74s system 172% cpu 27,112 total
```

I assume the much longer run is due to many more rules and files are being checked as I removed many of the `offs` we had and enabled many of the checks for most of the packages. Also I suppose with  `recommended` settings some of the rules were added on top of what we have.

2024-11-06 21:31 UTC, peter-sanderson commented on eslint.config.mjs
> +export default [...eslint];
Repository top-level config is now lust a link into package that contains all of the configuration.

2024-11-06 21:33 UTC, peter-sanderson commented on package.json
> +        "lint:js": "eslint . --cache --cache-strategy content --flag unstable_config_lookup_from_file",
This flag loads configuration which is closest to the checked file. This enables the overriding of the rules per package.

See: https://eslint.org/docs/latest/use/configure/configuration-files#experimental-configuration-file-resolution

2024-11-07 10:22 UTC, peter-sanderson commented on packages/components/.storybook/main.js
> -    babel: async options => {
I have tested the build of storybook and it works.

2024-11-07 10:27 UTC, peter-sanderson commented on packages/product-components/.storybook/main.js
> -    babel: async options => {
Tested the build of story book and it works.

2024-11-07 10:33 UTC, peter-sanderson commented on packages/transport/jest.config.js
> -    testEnvironment: 'node',
duplicate key

2024-11-07 22:36 UTC, peter-sanderson commented on packages/components/src/components/AutoScalingInput/AutoScalingInputExamples.stories.tsx
> -// eslint-disable-next-line local-rules/no-override-ds-component
When overwrite happens **inside** the `@trezor/components` it wont get reported. And now the ESLint complains about unused ignore. It is here multiple times.

2024-11-07 22:38 UTC, peter-sanderson commented on packages/connect-explorer/src/components/CommonParamsLink.tsx
> -// eslint-disable-next-line local-rules/no-override-ds-component
Incorrect `Link` is from `'next/link'` and not from `@trezor/components`. Now ESLint correctly raised error that this is unused ignore.

2024-11-07 22:39 UTC, peter-sanderson commented on packages/product-components/src/components/ConfirmOnDevice/ConfirmOnDeviceContent.tsx
> -// eslint-disable-next-line local-rules/no-override-ds-component
This is override inside of the `@trezor/produce-components` this wont be reported by the rule and therefore it is unused ignore.

2024-11-07 22:40 UTC, peter-sanderson commented on packages/schema-utils/src/codegen.ts
>  import * as Codegen from '@sinclair/typebox-codegen/typescript';
@martykan I am not sure how to solve this. Please take a look.

2024-11-08 10:11 UTC, peter-sanderson commented on packages/blockchain-link/src/workers/electrum/devrun.ts
> -/* eslint-disable @typescript-eslint/no-unused-vars */
@marekrjpolak approved that I can delete this file

2024-11-08 13:13 UTC, peter-sanderson commented on package.json
> +        "eslint": "^9.13.0",
Eslint must be here on global level. Otherwise you get `command not found: eslint`

2024-11-08 13:15 UTC, peter-sanderson commented on yarn.lock
> +"@storybook/theming@npm:^7.6.13":
Do we want this here? @adamhavel / @jvaclavik ? It was imported but probably not used or something.

2024-11-08 13:25 UTC, peter-sanderson commented on yarn.lock
> +"@storybook/theming@npm:^7.6.13":
For example in this file here: https://github.com/trezor/trezor-suite/pull/15287/files#diff-5f68bad9bd11d1e6bf99a4c6ccf8f12de9f0c2693b57a9a2d22454c2982494f8R1

2024-11-08 15:17 UTC, Lemonexe commented on package.json
> +        "lint:js": "eslint . --cache --cache-strategy content --flag unstable_config_lookup_from_file",
unstable or experimental is usually a red flag, but for dev dependency (one that's not related to build) I think it's fine

2024-11-08 15:21 UTC, Lemonexe commented on packages/eslint/package.json
> +        "typescript-eslint": "^8.12.2"
where did `eslint-plugin-cypress` go? :thinking:

2024-11-08 15:22 UTC, Lemonexe commented on packages/eslint/src/index.mjs
> +import jsxA11y from 'eslint-plugin-jsx-a11y';
I think you forgot `@types/eslint-plugin-jsx-a11y`

2024-11-08 16:24 UTC, Lemonexe commented on packages/eslint/eslint.config.mjs
> +export default [
I would add a comment explaining that this config is just for this package, not to be confused with `index.mjs` which is the export

2024-11-08 16:44 UTC, Lemonexe commented on packages/eslint/src/typescriptConfig.mjs
> +            '@typescript-eslint/triple-slash-reference': 'off', // Todo: solve before merge
reminder comment..

2024-11-08 17:10 UTC, peter-sanderson commented on packages/eslint/package.json
> +        "typescript-eslint": "^8.12.2"
https://github.com/trezor/trezor-suite/issues/15297 -> I have asked QA to finish it its 200 errors or something

2024-11-08 17:11 UTC, peter-sanderson commented on packages/eslint/src/index.mjs
> +import jsxA11y from 'eslint-plugin-jsx-a11y';
Its not needed. We have config for ESLint in pure javascript. When I added it, it produced error of unused dependency.

2024-11-08 17:12 UTC, peter-sanderson commented on packages/eslint/src/typescriptConfig.mjs
> +            '@typescript-eslint/triple-slash-reference': 'off', // Todo: solve before merge
Thanks, I probably just link issue to it https://github.com/trezor/trezor-suite/issues/15310

I believe it can be done later

2024-11-11 07:12 UTC, Lemonexe commented on packages/eslint/src/index.mjs
> +import jsxA11y from 'eslint-plugin-jsx-a11y';
oh right, sorry about that!

2024-11-11 07:17 UTC, Lemonexe commented on packages/components/src/components/AutoScalingInput/AutoScalingInputExamples.stories.tsx
> -// eslint-disable-next-line local-rules/no-override-ds-component
:tada: excellent, this rule doesn't make sense to me in `packages/components` and `product-components`, though this is concern of the usability team..

2024-11-11 07:58 UTC, Lemonexe approved these changes
Wow, great job, thank you! :tada: :rocket: 

I've randomly tried some bad code here and there to test that it still catches the errors. Seems to be working fine :heavy_check_mark:

2024-11-11 07:58 UTC, Lemonexe commented on packages/components/src/components/typography/typography.stories.tsx
> +                type=&#34;titleLarge&#34; <br />
I think this is better readable (and all other `&#34;` ocurrences as wel)
```suggestion
                type=&quot;titleLarge&quot; <br />
```

2024-11-11 07:58 UTC, Lemonexe commented on packages/suite-data/src/translations/list-unused.ts
> -// eslint-disable-next-line import/no-extraneous-dependencies
Oh no.. I saw the comment in `list-duplicates.ts` :see_no_evil: Quite a hack, but that's out of scope of this PR.
More importantly - isn't it an issue that eslint no longer gives you error? :thinking:

2024-11-11 10:14 UTC, peter-sanderson commented on packages/components/src/components/typography/typography.stories.tsx
> +                type=&#34;titleLarge&#34; <br />
fixed: https://github.com/trezor/trezor-suite/pull/15287/commits/e4bbc4687be479cc752e1243ebefbed1000a899b

2024-11-11 10:27 UTC, peter-sanderson commented on packages/eslint/src/index.mjs
> +            // 'packages/connect-examples', // Todo: fix or ignore locally in repo
- [x] Todo: solve

2024-11-11 13:22 UTC, peter-sanderson commented on packages/eslint/eslint.config.mjs
> +export default [
https://github.com/trezor/trezor-suite/pull/15287/commits/96b7aefd99cc4dfca798aa9423863cf382231d66

2024-11-11 13:28 UTC, peter-sanderson commented on eslint.config.mjs
> +                        ...globalNoExtraneousDependenciesDevDependencies,
This is a mechanism how to extend the shared  `devDependencies` for this rule.  Such a deep field is not merged together by the flat-config logic and therefore we have to spread it manually.

2024-11-11 13:29 UTC, peter-sanderson commented on nx.json
> -        "lint:js": {
Calling the `lint:js` for specific package in the workspace, would require that `EVERY` package has `eslint.config.mjs`

Maybe we will get there, but currently we only run it globally and there is no need for package-specific command to run it.

2024-11-11 13:33 UTC, peter-sanderson commented on packages/connect-examples/update-webextensions.js
> +    // const backgroundScriptPath = path.join(rootPath, 'background.js');
I left it here is it is probably meant as an example (but it reports unused variable)

2024-11-11 16:24 UTC, Lemonexe commented on nx.json
> -        "lint:js": {
Unfortunately, yeah :disappointed:

2024-11-11 16:27 UTC, Lemonexe commented on eslint.config.mjs
> +                        ...globalNoExtraneousDependenciesDevDependencies,
It's not pretty, but I don't have an idea for a better solution.

2024-11-11 16:27 UTC, Lemonexe approved these changes

2024-11-11 17:43 UTC, komret requested changes
When I run `yarn lint:js`, I get a bunch of errors from build files. One probably shouldn't have these files at all, but if they do exist, it is confusing. Can they be ignored?

How to reproduce:
`yarn workspace @trezor/components storybook-build`
`yarn workspace @trezor/product-components storybook-build`
`yarn lint:js`

`connect-examples` seem to be broken, I could not build them again 🤷‍♂️ 


connect-examples:
![Screenshot 2024-11-11 at 18 01 01](https://github.com/user-attachments/assets/4ccc02bf-6a57-4f9d-9e84-b74fac664d8c)
![Screenshot 2024-11-11 at 18 01 25](https://github.com/user-attachments/assets/765c5655-6445-4d85-88a5-1a1b9b968a25)
storybook:
![Screenshot 2024-11-11 at 18 02 41](https://github.com/user-attachments/assets/20472a4b-08e0-4ea1-b8fa-d220807c95e2)
![Screenshot 2024-11-11 at 18 02 20](https://github.com/user-attachments/assets/fe8739af-2db9-4e4d-bef4-7821303b169e)

2024-11-11 17:43 UTC, komret commented on packages/address-validator/eslint.config.mjs
> +            // This is a JS only codebase written in JS, wo we are not checking it
```suggestion
            // This is a JS only codebase written in JS, so we are not checking it
```

2024-11-11 17:43 UTC, komret commented on packages/connect-examples/webextension-mv2/src/background.js
>      const { type, data } = message;
```suggestion
    const { type } = message;
```

2024-11-11 17:43 UTC, komret commented on packages/connect/package.json
> +        "web3-utils": "^4.3.2",
I wonder why this was added?

2024-11-11 17:48 UTC, komret commented
I would also like to hear @Nodonisko's opinion on the removal of per-package execution via `nx`. It could mean slower CI and/or increase the costs. I believe it can be supported if each package uses `@trezor/eslint`.

If we indeed remove this option, `nx:lint:js` command should be removed as well.

2024-11-12 10:27 UTC, peter-sanderson commented on packages/connect-examples/webextension-mv2/src/background.js
>      const { type, data } = message;
This is example package, so I thought it is there for a demonstrative purpose

2024-11-12 10:29 UTC, peter-sanderson commented on packages/connect/package.json
> +        "web3-utils": "^4.3.2",
I is used in `packages/connect/src/api/ethereum/__tests__/ethereumSignTx.test.ts` and the ESlint correctly pointed that

2024-11-12 11:04 UTC, peter-sanderson commented on packages/address-validator/eslint.config.mjs
> +            // This is a JS only codebase written in JS, wo we are not checking it
https://github.com/trezor/trezor-suite/pull/15287/commits/39135d83f47c2541d624f8117aa39027db606f26

2024-11-12 11:59 UTC, Nodonisko commented
@komret We are not using `nx:lint:js` for last few months because full uncached run over whole repo is like 30s, so it doesn't make sense to have Nx. But we have to be careful when adding new rules, some rules are very very expensive mostly `import/*` rules and single rule here can easily add few minutes to run.

I just checked it and it runs about 1m30s which is still OK without Nx, but we should always measure performance of newly enabled rules.

2024-11-12 12:48 UTC, Lemonexe commented on packages/connect-examples/webextension-mv2/src/background.js
>      const { type, data } = message;
Yeah, there is really **a lot** of unused variables in that package, so it also seems to me it should be there. But it's a question for @trezor/suite-connect

2024-11-12 13:21 UTC, komret approved these changes
🚀 Great job!

2024-11-12 17:42 UTC, Nodonisko approved these changes
lgtm, great job upgrading to flag config!

2024-11-13 09:36 UTC, merged