feat(suite): add SegmentSlider component
trezor/trezor-suite pull request #15290
Opened 2024-11-06 23:29 UTC by izmy

## Description

Created a new slider component with segments.

## Related Issue

Resolve #11566

## Screenshots:

<img width="610" alt="segment-slider" src="https://github.com/user-attachments/assets/3e32aa67-1f06-4a34-b8d3-daa5f6382162">

2024-11-07 16:34 UTC, tomasklim requested changes
Hello @izmy, thanks for your contribution. 
I've added few change proposals.

And btw do you think that it would make sense to unify `SegmentSlider` with `Range`? 
Create just 1 component allowing features from both? It shares a lot of logic/styles

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.stories.tsx
> +        segments: {
Could you please add this?

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +
```suggestion
```
`width` set twice

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +          : 0;
Eslint error
`Do not nest ternary expressions.eslint[no-nested-ternary](https://eslint.org/docs/latest/rules/no-nested-ternary)`

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +const Segment = styled.div<{ $start: number; $end: number }>`
would be better to call it little bit differently so that it does not overlap with type `Segment`

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    };
nit: wrap it in `useCallback`

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +                    onKeyUp={e => e.key === 'Enter' && handleForceChange(segment.max)}
```suggestion
                    onKeyUp={e => e.key === KEYBOARD_CODE.ENTER && handleForceChange(segment.max)}
```

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +        `linear-gradient(90deg, ${disabled ? theme.backgroundNeutralDisabled : theme.backgroundPrimaryDefault} ${$filled}%, ${disabled ? theme.backgroundNeutralDisabled : theme.backgroundNeutralSubdu
how about a helper function to make this shorter?
```
        `linear-gradient(90deg, ${disabled ? theme.backgroundNeutralDisabled : theme.backgroundPrimaryDefault} ${$filled}%, ${disabled ? theme.backgroundNeutralDisabled : theme.backgroundNeutralSubdued} ${$filled}%)`};
```

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    segments: Array<{ max: number; name: string }>;
```suggestion
    segments: Segment[];
```

2024-11-07 16:34 UTC, tomasklim commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    disabled?: boolean;
```suggestion
    isDisabled?: boolean;
```

2024-11-08 16:55 UTC, adamhavel submitted a review, later dismissed

2024-11-08 16:55 UTC, adamhavel commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +const SegmentLabel = styled.div`
Use Text component instead of custom styles.

2024-11-08 16:55 UTC, adamhavel commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    padding: 10px 0;
Use values from spacings variable.

2024-11-08 16:55 UTC, adamhavel commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    margin-top: calc((${spacingsPx.xxs} - ${spacingsPx.xl}) / 2);
If it has to be 10px, just use that value, no need to calculate it from the spacings.

2024-11-08 16:55 UTC, adamhavel commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    padding: 10px 0;
Use value from spacings.

2024-11-08 16:55 UTC, adamhavel commented on packages/components/src/components/form/SegmentSlider/SegmentSlider.tsx
> +    left: ${({ $start }) => $start}%;
What about using transform? Should be more performant.

2024-11-08 16:56 UTC, adamhavel commented
> Hello @izmy, thanks for your contribution. I've added few change proposals.
> 
> And btw do you think that it would make sense to unify `SegmentSlider` with `Range`? Create just 1 component allowing features from both? It shares a lot of logic/styles

Agree with this:)

2024-11-11 15:27 UTC, izmy commented
> > Hello @izmy, thanks for your contribution. I've added few change proposals.
> > And btw do you think that it would make sense to unify `SegmentSlider` with `Range`? Create just 1 component allowing features from both? It shares a lot of logic/styles
> 
> Agree with this:)

Based on your feedback that SegmentSlider should be part of the existing Range component, I completely reworked it and integrated it into Range. I tried to maintain the same interface with labels to ensure nothing breaks.

2024-11-22 09:11 UTC, jvaclavik approved these changes
LGTM, I suggest just unify naming, otherwise ship it 🚢🇮🇹

Good job!

2024-11-22 09:11 UTC, jvaclavik commented on packages/components/src/components/form/Range/Range.tsx
> +    labels: Segment[];
Could we unify naming of labels and segments?

2024-11-22 09:11 UTC, jvaclavik commented on packages/components/src/components/form/Range/Range.tsx
> +    margin-inline: ${spacingsPx.xxxs};
Interesting :) I didn't know about existing `margin-inline`

2024-11-23 18:22 UTC, tomasklim approved these changes

2024-11-23 19:12 UTC, tomasklim commented
@izmy please check CI checks. Type and lint checks failed 🙏

2024-12-01 15:20 UTC, tomasklim commented
Closing in favor of #15540

2024-12-01 15:20 UTC, closed without merging