chore(suite): refactor staking
trezor/trezor-suite pull request #15391
Opened 2024-11-14 10:45 UTC by adamhavel

## Description

## Related Issue

Resolve 

## Screenshots:

2024-11-15 07:56 UTC, tomasklim requested changes
Claiming is usually not available, so most of the users will see it like this 
<img width="1116" alt="Screenshot 2024-11-15 at 8 51 31" src="https://github.com/user-attachments/assets/76c39ee5-41fd-4918-82ec-26b42c88e05c">

This banner looks weird in the bottom
At the top or better at the modal header as description, it would maybe look better?
<img width="635" alt="Screenshot 2024-11-15 at 8 47 40" src="https://github.com/user-attachments/assets/5c948846-d190-4728-a4c8-8d3c12bede0b">

Probably you removed it in the previous refactoring but the fee component had some sort of state that the previous gas limit and gas price was visible before the new one was composed. That was there to avoid this jumping

https://github.com/user-attachments/assets/fac9f013-b4d1-4e37-aeee-66d8fe7f9bd5

2024-11-15 08:00 UTC, adamhavel commented
> Claiming is usually not available, so most of the users will see it like this 
> 
> <img width="1116" alt="Screenshot 2024-11-15 at 8 51 31" src="https://github.com/user-attachments/assets/76c39ee5-41fd-4918-82ec-26b42c88e05c">
> 
> 
> 
> This banner looks weird in the bottom
> 
> At the top or better at the modal header as description, it would maybe look better?
> 
> <img width="635" alt="Screenshot 2024-11-15 at 8 47 40" src="https://github.com/user-attachments/assets/5c948846-d190-4728-a4c8-8d3c12bede0b">
> 
> 
> 
> Probably you removed it in the previous refactoring but the fee component had some sort of state that the previous gas limit and gas price was visible before the new one was composed. That was there to avoid this jumping
> 
> 
> 
> https://github.com/user-attachments/assets/fac9f013-b4d1-4e37-aeee-66d8fe7f9bd5
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Ok, I didn't know that, I thought there is always either claiming available or pending:) I'll fix that.

2024-11-15 16:58 UTC, tomasklim commented
/rebase

2024-11-15 17:06 UTC, tomasklim commented
@trezor/qa this PR should be just staking UI/UX changes, but please test it properly 🙏

2024-11-15 17:15 UTC, tomasklim approved these changes
LGTM

Would be nice to find a solution for this claiming banner as it is huge but I do not want to block merging to avoid conflicts
<img width="983" alt="Screenshot 2024-11-15 at 17 54 00" src="https://github.com/user-attachments/assets/3852c5ce-d14c-43f8-aa43-9172bfd59f75">

2024-11-18 10:30 UTC, jvaclavik approved these changes

2024-11-18 10:30 UTC, jvaclavik commented on packages/components/src/components/form/Select/Select.tsx
> -        hasBottomPadding?: boolean;
Are you sure about this change? We used both values.

2024-11-18 12:28 UTC, merged

2024-11-18 14:47 UTC, bosomt commented
**QA OK**

- stake
- unstake
- claim
- bump
- dark mode

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/de11db74-b731-479e-96cc-a00d524a97c0">

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/b821568d-4615-49fa-92fc-cf20b3de11f0">

<img width="609" alt="image" src="https://github.com/user-attachments/assets/e16c6856-71ba-41ac-8e0d-5b055aefbca9">

**Info:**
 - Suite version: web 24.12.0 (182d6b4026aad83ca7544ee77419624659308e35)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport