(WIP) Coins deprecation
trezor/trezor-suite pull request #15509
Opened 2024-11-21 19:43 UTC by MiroslavProchazka

Closed in favor of https://github.com/trezor/trezor-suite/pull/16131 

As of February 2025, Trezor Suite will discontinue support for Dash, Bitcoin Gold, DigiByte, Namecoin, and Vertcoin. Users are advised to migrate their funds to alternative wallets to ensure continued access and security. The coins will still be supported on the FW level, so users can still access them using third party wallets.

**Proposed Timeline:**

- February Suite Release: This version of Suite will no longer support the affected coins. However, users can still use older versions of Suite to access their coins.
- July 2025: The BEs will be turned off. From this point forward, third-party apps will be the only way to access the coins.

I will divide the commits by coin and by environment (desktop/native) to make code review easier.

**`Please read the following before conducting the code review:`**

- Since the coins will still be supported by the firmware and third-party apps, we should maintain support at the Connect level. Similarly, we will continue support in blockchain-link and utxo-lib.
- For now, we have decided to keep these coins in Trading (users will need to use external addresses for this), so we need to retain the Address Validator as well.
- We need to create a migration for users with remembered wallets.

Given the points above, I have prepared only basic deprecation that mainly affects NetworksConfig. Everything else (tests, icons, etc.) will remain unchanged until we decide to disable trading options and/or turn off the backends.

Todo:

- [x] In case that the coins will be still available for trading (to external wallets), can we delete their icons, names in `messages.ts` and other mentions in general files?
- [x] Should I also delete all tests mentioning those coins?
- [x] As some of the coins files needs to stay in the codespace (address validator, blockchain-link, connect etc.), it would be wise to determinate minimal scope for just Suite deprecation - will this be just `NetworksConfig`? 
- [ ] Create migration for users with remembered wallet
- [ ] Adjust coins.ts
- [ ] Adjust /trezor-suite/suite-common/suite-constants/src/protocol.ts

--------------------------------------------------------------------------------------------------------------------------

This pull request involves the removal of several cryptocurrency networks from the codebase. The changes span multiple files and aim to simplify the configuration and support for the remaining networks.

### Removal of cryptocurrency networks:

* [`suite-common/wallet-config/src/networksConfig.ts`](diffhunk://#diff-8275801eb25562af454cd9d02084b668b58a396ff45c85242da60e8a203c46fdL358-L466): Removed configurations for `dash`, `btg`, `dgb`, `nmc`, and `vtc` networks.
* [`suite-common/wallet-config/src/types.ts`](diffhunk://#diff-e942c6bc5783a94562dd2bd56503824d6ffb70f56a448befe895f978282ddc4eL11-L16): Removed `dash`, `btg`, `dgb`, `nmc`, and `vtc` from the `NetworkSymbol` type.
* [`suite-native/config/src/supportedNetworks.ts`](diffhunk://#diff-18a7d1f1fa86a4d94e72d161fb1360b56a33ce2c53226671efa9f224ca67d732L35-L48): Removed `dash`, `btg`, `dgb`, `nmc`, and `vtc` from the `networkSymbolsWhitelistMap` and related filtering logic. [[1]](diffhunk://#diff-18a7d1f1fa86a4d94e72d161fb1360b56a33ce2c53226671efa9f224ca67d732L35-L48) [[2]](diffhunk://#diff-18a7d1f1fa86a4d94e72d161fb1360b56a33ce2c53226671efa9f224ca67d732L83-R75)
* [`suite-native/discovery/src/discoveryThunks.ts`](diffhunk://#diff-d8f3726603386e13919e77b31f27567a44ebfae82d669e5a41b2f7cd9006ad08L61-L65): Removed batch size configurations for `dash`, `btg`, `dgb`, `nmc`, and `vtc`.
* [`suite-native/module-accounts-import/src/components/DevXpub.tsx`](diffhunk://#diff-c2a3696012163bcb8189861c1094d7fc61cf9249b701222e49ff5a321c343682L29-L30): Removed `btg` and `dgb` from the `devXpubs` configuration.
* [`suite-native/storage/src/migrations/account/v3.ts`](diffhunk://#diff-730dd673b574f8e6f6dfdf6883fb184a7c7163cf1df3093331c33181c5ce9b2aL21-L26): Removed `dash`, `btg`, `dgb`, `nmc`, and `vtc` from the `NetworkSymbol` type in migration script.

2024-11-22 08:34 UTC, MiroslavProchazka commented on packages/utxo-lib/src/networks.ts
Keep this

2024-11-22 08:37 UTC, MiroslavProchazka commented on packages/suite/src/storage/migrations/index.ts
Keep this

2024-11-22 08:39 UTC, martykan commented
What will happen if user has remembered accounts for these coins? Maybe a migration to delete them?

2024-11-22 08:58 UTC, tomasklim commented on packages/blockchain-link/src/ui/config.ts
> -    {
should this be deleted @mroz22?

2024-11-22 08:59 UTC, tomasklim commented on packages/product-components/src/components/CoinLogo/coins.ts
> -    dash: require('../../images/coins/dash.svg'),
it should stay here, right? @martykan

2024-11-22 09:14 UTC, martykan commented on packages/product-components/src/components/CoinLogo/coins.ts
> -    dash: require('../../images/coins/dash.svg'),
Connect Explorer doesn't need it

2024-11-25 15:37 UTC, mroz22 requested changes
please lets not do changes in blockchain-link and utxo-lib. Support can peacefully live there for some time.

2024-11-25 15:37 UTC, mroz22 commented on packages/blockchain-link/src/ui/config.ts
> -    {
I'd rather keep support in the under-suite layers. so no.

2024-12-27 13:51 UTC, MiroslavProchazka commented on packages/blockchain-link/src/ui/config.ts
> -    {
Solved

2024-12-27 13:51 UTC, MiroslavProchazka commented
> please lets not do changes in blockchain-link and utxo-lib. Support can peacefully live there for some time.

Solved

2025-01-02 08:16 UTC, MiroslavProchazka commented
Closed in favor of https://github.com/trezor/trezor-suite/pull/16131

2025-01-02 08:16 UTC, closed without merging