fix(suite): fix link in pass modal
trezor/trezor-suite pull request #15539
Opened 2024-11-23 16:27 UTC by MiroslavProchazka

Resolve https://github.com/trezor/trezor-suite/issues/15466
Before
![image](https://github.com/user-attachments/assets/ce72f126-44fa-460d-baab-073c8b8e2a2b)

After
![image](https://github.com/user-attachments/assets/b57d7ad9-2515-4ec5-a2c2-dc674945f569)

2024-11-23 16:35 UTC, tomasklim commented on packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PassphraseModal.tsx
> +                                                style={{ textDecoration: 'underline' }}
we dont use it like this

2024-11-23 16:52 UTC, tomasklim requested changes

2024-11-23 16:52 UTC, tomasklim commented on packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PassphraseModal.tsx
> -                                        a: chunks => (
Changes in this file are not needed. Just change text to `"It's important to first <a>learn how a passphrase works</a>."`

2024-11-23 19:22 UTC, tomasklim approved these changes
LGTM

2024-11-24 19:39 UTC, jvaclavik approved these changes
Nice!

2024-11-25 09:13 UTC, adamhavel approved these changes

2024-11-25 09:23 UTC, merged