Write unit tests for utils #31
trezor/trezor-suite pull request #157
Opened 2019-06-13 11:40 UTC by keip

close #31

2019-06-18 12:45 UTC, vladimirvolek commented
Added coverage, please cover all the test cases.

![image](https://user-images.githubusercontent.com/3112191/59682997-9e385980-91d7-11e9-9607-afb5d984aa8c.png)

2019-06-18 12:50 UTC, vladimirvolek requested changes
we need 100% coverage for utils

2019-06-19 10:06 UTC, slowbackspace approved these changes

2019-06-19 10:07 UTC, slowbackspace requested changes

2019-06-19 10:07 UTC, slowbackspace commented on packages/components/package.json
> +        "jest": "^24.8.0",
should be installed as devDep

2019-06-19 10:20 UTC, merged