fix(suite): Fix buy/sell/dca buttons
trezor/trezor-suite pull request #15795
Opened 2024-12-05 16:09 UTC by jvaclavik

## Description

## Related Issue

Resolve 

## Screenshots:

before
![image](https://github.com/user-attachments/assets/0f2d948f-ca40-4772-adf5-000e1e99d675)

after
<img width="758" alt="image" src="https://github.com/user-attachments/assets/fd2cb0e8-045b-45d8-8784-182202aab338">

2024-12-05 16:11 UTC, adamhavel commented
I don't think this is a good idea. Select bar is a form component, not a navigation one.

2024-12-10 14:20 UTC, adamhavel requested changes

2024-12-10 14:20 UTC, adamhavel commented on packages/components/src/components/form/SelectBar/SelectBar.tsx
> +    icon?: IconName;
iconName

2024-12-10 14:20 UTC, adamhavel commented on packages/components/src/components/form/SelectBar/SelectBar.tsx
> +export const fillTypes = ['none', 'default'] as const;
Perhaps we should create a common fill types like for other props, it's used in many components.

2024-12-10 14:20 UTC, adamhavel commented on packages/components/src/components/form/SelectBar/SelectBar.tsx
> +    background: ${({ $fillType, theme, $elevation }) =>
Do it the other way around, unset the background when fillType is none. Then you don't have to pass all the props to the mapElevationToBackground.

2024-12-13 12:56 UTC, jvaclavik commented
Already fixed in other PR

2024-12-13 12:56 UTC, closed without merging