chore(connect-common): add fw 2.8.6. for t3t1
trezor/trezor-suite pull request #15835
Opened 2024-12-09 12:17 UTC by MiroslavProchazka

Adding FW binaries for upcoming 2.8.6 FW release

2024-12-09 12:29 UTC, komret requested changes

2024-12-09 12:29 UTC, komret commented on packages/connect-common/files/firmware/t3t1/releases.json
> +        "min_bridge_version": [2, 0, 7],
Suite doesn't use this property, should be removed.

2024-12-09 12:29 UTC, komret commented on packages/connect-common/files/firmware/t3t1/releases.json
> +        "url": "data/firmware/t3t1/trezor-t3t1-2.8.6.bin",
The `data/` part of the path is only relevant for the data repo, should be removed.

2024-12-09 12:29 UTC, komret commented on packages/connect-common/files/firmware/t3t1/releases.json
> +        "url_bitcoinonly": "data/firmware/t3t1/trezor-t3t1-2.8.6-bitcoinonly.bin",
As above.

2024-12-09 13:03 UTC, komret approved these changes

2024-12-09 13:04 UTC, merged

2024-12-11 07:34 UTC, bosomt commented
**QA OK**

**Info:**
 - Suite version: desktop 24.12.1 (ec8321d0d17529ca77d8916e70158cecc469f863)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 17f2a3256b2631823c2bad1855fab61b27985fd2)
 - Transport: BridgeTransport 2.0.33