feat(suite-native): make device switcher work without devicestate
trezor/trezor-suite pull request #15844
Opened 2024-12-09 14:47 UTC by vytick

Make device switcher to show content even in case there is no deviceState for the device.

## Related Issue

Part of #15733

2024-12-09 15:21 UTC, Nodonisko requested changes, later dismissed

2024-12-09 15:21 UTC, Nodonisko commented on suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
> +            const d = deviceState ? selectDeviceByState(state, deviceState) : undefined;
same here

2024-12-09 15:21 UTC, Nodonisko commented on suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
> +                deviceState ? selectDeviceByState(state, deviceState)?.connected : undefined,
How does this make any difference? selectDeviceByState returns undefined anyway

2024-12-09 15:22 UTC, vytick commented on suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
> +                deviceState ? selectDeviceByState(state, deviceState)?.connected : undefined,
but it expects devicestate as defined

2024-12-09 15:38 UTC, vytick commented on suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
> +                deviceState ? selectDeviceByState(state, deviceState)?.connected : undefined,
this calls the selector in case deviceState (expected by selectDeviceByState) is defined or returns undefined otherwise

2024-12-10 15:17 UTC, Nodonisko commented on suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
> +                deviceState ? selectDeviceByState(state, deviceState)?.connected : undefined,
I think it might be fine to make selector to accept also undefined, WDYT? We will probably need it to use like this in more places no?

2024-12-11 21:10 UTC, vytick commented on suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
> +                deviceState ? selectDeviceByState(state, deviceState)?.connected : undefined,
Not that many places, actually. Right, it seems safe to change:

34f6539eb2

2024-12-13 10:00 UTC, Nodonisko approved these changes

2024-12-13 10:02 UTC, vytick commented
/rebase

2024-12-13 10:32 UTC, merged