fix(suite): Fix close button in suite desktop promo
trezor/trezor-suite pull request #15872
Opened 2024-12-10 13:22 UTC by jvaclavik

## Description

## Related Issue

Resolve 

## Screenshots:

before
![image](https://github.com/user-attachments/assets/24a822d1-9e69-45ed-a7a0-2adeb4207842)

after
<img width="720" alt="image" src="https://github.com/user-attachments/assets/90d88ed9-5828-43ad-97e2-903aff2b2f64">

2024-12-10 14:23 UTC, adamhavel requested changes

2024-12-10 14:23 UTC, adamhavel commented on packages/suite/src/views/settings/SettingsGeneral/DesktopSuiteBanner.tsx
> +const CloseButtonContainer = styled.div`
Use Box:D

2024-12-10 14:24 UTC, adamhavel commented
You should refactor the rest of the component, what do you think?:D

2024-12-11 09:13 UTC, jvaclavik commented
> You should refactor the rest of the component, what do you think?:D

Sorry, not this time 😅, we have to merge this soon and there are too many other issues

2024-12-11 09:15 UTC, jvaclavik commented on packages/suite/src/views/settings/SettingsGeneral/DesktopSuiteBanner.tsx
> +const CloseButtonContainer = styled.div`
Done

2024-12-11 09:54 UTC, adamhavel approved these changes

2024-12-11 15:08 UTC, merged

2025-01-02 10:28 UTC, bosomt commented
**QA OK**

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/2fccb10e-38f7-45ac-8f8b-5c6f29ac93a4" />

**Info:**
 - Suite version: web 25.1.0 (7748d59e23ecbafea9e6479d4551edcd6453e9f1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: WebUsbTransport