feat: cardano review modal with governance
trezor/trezor-suite pull request #16003
Opened 2024-12-17 11:45 UTC by vladimirvolek

Adding a new Cardano withdrawal modal.

![image](https://github.com/user-attachments/assets/2acfe885-d93a-4ab1-92e1-a01c10c7b4aa)

2024-12-18 23:03 UTC, mmahut commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                    defaultMessage="When withdrawing your rewards, you can choose to support the Cardano ecosystem by delegating your community voting rights. Your votes will be delegated to 5Binarie
```suggestion
                    defaultMessage="When withdrawing your rewards, you can choose to support the Cardano ecosystem by delegating your community voting rights. Your votes will be delegated to a representative of Five Binaries, the operators of Cardano staking in Trezor Suite. This helps strengthen the network's resilience, sustainability, and community-driven governance. If you prefer, you can easily opt out of governance."
```

Just a small text correction, to match the legal name of the company.

2024-12-30 16:17 UTC, tomasklim commented on packages/suite/src/hooks/wallet/useCardanoStaking.ts
> +    const cardanoNetwork = account.symbol === 'ada' ? 'mainnet' : 'preview';
please create util for this

2024-12-30 16:19 UTC, tomasklim commented on packages/suite/src/support/messages.ts
> +        defaultMessage: `When withdrawing your rewards, you can choose to support the Cardano ecosystem by delegating your community voting rights. Your votes will be delegated to 5Binaries, the oper
Is the company called `5Binaries` or `Five Binaries`? https://fivebinaries.com/

2024-12-30 16:22 UTC, tomasklim requested changes
Please improve commit texts

We do not use
`fix: modal heading`
`fix: text`

Maybe just squash it all into one. Thanks

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +`;
overrides like this are not allowed anymore right? cc @jvaclavik 
edit: haha, now I noticed the eslint-disable-next-line comment 👿

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                <FormattedMessage
I think this should use the "Translation" component instead

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
there is a lot of custum styling in this file. I would expect more reuse of standardized components.

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +    const account = useSelector(state => state.wallet.selectedAccount.account);
I don't care much about this, just that there are selectors for everything now. https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/reducers/wallet/selectedAccountReducer.ts#L33

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +        throw Error('CardanoWithdrawModal used for other network');
error text misleading since it throws also when for undefined account

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/hooks/wallet/useCardanoStaking.ts
> +    const { trezorDRep } = useSelector(state => state.wallet.cardanoStaking[cardanoNetwork]);
maybe line 70 + 69 (https://github.com/trezor/trezor-suite/pull/16003/files#r1899652157) could be a selector

2025-01-01 09:46 UTC, mroz22 commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                                <Link href={`https://gov.tools/drep_directory/${trezorDRepBech32}`}>
I am slightly unhappy about the fact that trezorDRepBech32 can be undefined per typescript. Do you think it would make sense to add an early return above to handle this case?

2025-01-02 13:10 UTC, enjojoy commented
Please use NewModal component instead of custom styling 

If you're not sure about what components are available you can run storybook locally 
`yarn nx run @trezor/components:storybook`

And see what's available

2025-01-02 13:26 UTC, enjojoy requested changes

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Row = styled.div`
use existing Row component

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Line = styled.div`
You can use Box or Row component here

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const LeftPadding10 = styled.div`
Try to use existing components, Row and Column have padding prop. Also use spacings values instead of hardcoded px amount. 

Example: `<Row padding={{ vertical: spacings.xs, horizontal: spacings.md }}>`

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Column = styled.div`
Use existing Column component

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Title = styled.div`
I think Text component in combination with Row component would do the work here.

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +    margin-bottom: 16px;
Don't hardcode the px values, use spacings variable

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Actions = styled.div`
Use existing Row component instead

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Text = styled.div`
Use existing Text component

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const Content = styled.div`
use either Row, Column, or Box

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                <FormattedMessage
Please use Translation component

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                            <FormattedMessage
Use Translation component

2025-01-02 13:26 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                    <FormattedMessage
Use Translation component.

2025-01-02 13:32 UTC, enjojoy commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +export const LeftPadding10 = styled.div`
Also Box can be used, depends on usecase

2025-01-02 13:35 UTC, enjojoy commented
Also I see that conventional commits check failed

We use it like that

For example 

fix(suite): desc of the change 
https://www.conventionalcommits.org/en/v1.0.0/

2025-01-02 17:04 UTC, adderpositive commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +import { HiddenPlaceholder } from '../../HiddenPlaceholder';
Please, use the absolute path.

2025-01-03 01:00 UTC, vladimirvolek commented on packages/suite/src/support/messages.ts
> +        defaultMessage: `When withdrawing your rewards, you can choose to support the Cardano ecosystem by delegating your community voting rights. Your votes will be delegated to 5Binaries, the oper
I think this is correct. @mmahut ?

2025-01-03 01:10 UTC, vladimirvolek commented
Next round please? ✨

2025-01-03 07:56 UTC, enjojoy commented
I think you shouldn't pass that big piece of text as a description, it meant to be rather a one sentence summary of the modal. 

As you can see it moves the close button down and it looks misaligned (1st pic)

Please pass this text as a child so it's aligned better (2nd pic). If you want to make the text secondary you can wrap it into Text component. 
``` js
<Text variant="tertiary">
    <Translation id="TR_CARDANO_WITHDRAW_MODAL_TITLE_DESCRIPTION" />
</Text>
```


<img width="719" alt="Screenshot 2025-01-03 at 08 49 00" src="https://github.com/user-attachments/assets/d47eb161-0e65-4589-a9d7-9824160e17a6" />

<img width="719" alt="Screenshot 2025-01-03 at 08 55 41" src="https://github.com/user-attachments/assets/65f75cfb-3210-4bbc-ab5d-ebdf11916509" />

2025-01-03 08:05 UTC, mroz22 commented on suite-common/wallet-types/src/account.ts
> +                  } | null;
🤔 this field is not optional. doesn't it require db migration?

2025-01-03 10:02 UTC, mmahut commented on packages/suite/src/support/messages.ts
> +        defaultMessage: `When withdrawing your rewards, you can choose to support the Cardano ecosystem by delegating your community voting rights. Your votes will be delegated to 5Binaries, the oper
`Five Binaries` is the correct name.

2025-01-03 14:22 UTC, vladimirvolek commented
Any idea why version 50 is skipped in develop?

https://github.com/trezor/trezor-suite/pull/16003/conflicts

2025-01-03 14:39 UTC, vladimirvolek commented
Anything else to improve or fix?

2025-01-03 15:09 UTC, mroz22 commented
should there be more changes to this branch, please stop using force pushes for each of them. It makes review slightly less enjoyable

2025-01-03 15:12 UTC, mroz22 commented on suite-common/wallet-types/src/account.ts
> +                  } | null;
I might not be seeing the full picture so I'd like to ask what the `staking` object was added to this type here https://github.com/trezor/trezor-suite/pull/16003/files#diff-590423282c67d295c7292f90e100f2863ea22b056e49ae02f135a5840475fb9bR172 (actually full `misc` object). was it a bug? how come anybody did not miss it there before?

2025-01-03 15:37 UTC, vladimirvolek commented on suite-common/wallet-types/src/account.ts
> +                  } | null;
Yes it was missing.

2025-01-03 20:09 UTC, adamhavel requested changes

2025-01-03 20:09 UTC, adamhavel commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +            <Row padding={{ top: spacings.xl }}>
Don't add buttons to the content, use bottomContent prop of the modal and populate with NewModal.Button components. You don't have to wrap them in Row, a fragment is enough.

2025-01-03 20:09 UTC, adamhavel commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +                    <Row padding={{ bottom: spacings.md }}>
Don't use Row for vertical spacing like this, just use gap prop on the parent Column

2025-01-03 20:09 UTC, adamhavel commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +            <Row padding={{ top: spacings.xl }}>
As in the other comment, don't use Row like this, just add a parent Column with gap for vertical spacing

2025-01-03 20:09 UTC, adamhavel commented on packages/suite/src/components/suite/modals/ReduxModal/CardanoWithdrawModal.tsx
> +            <Text variant="tertiary">
Use Paragraph component

2025-01-05 00:49 UTC, vladimirvolek commented
@adamhavel https://github.com/trezor/trezor-suite/pull/16003/commits/8b5cd37214d0dd4623e1432e52fdb49c7b158456

2025-01-05 13:14 UTC, adamhavel commented
> 8b5cd37

Thanks! One last thing, use NewModal.Button instead of Button in the bottomContent

2025-01-05 15:30 UTC, vladimirvolek commented
> > [8b5cd37](https://github.com/trezor/trezor-suite/commit/8b5cd37214d0dd4623e1432e52fdb49c7b158456)
> 
> Thanks! One last thing, use NewModal.Button instead of Button in the bottomContent

https://github.com/trezor/trezor-suite/pull/16003/commits/cdead7b034d7f0a72999e513f06cf01c8ff4430b

2025-01-06 09:39 UTC, mroz22 commented
not sure what about other guys think but I'd say that there should not be any "fix" commits for previous commits in the same PR. fix commit should be reserved for fixing anything that is already in develop. 

<img width="516" alt="image" src="https://github.com/user-attachments/assets/572ef890-d825-4955-b6a8-4dcee92d356b" />

doing it like this doesn't really help when writing changelogs - I don't want to state that I am fixing something which in fact hadn't been broken before this PR.

2025-01-07 09:45 UTC, vladimirvolek commented
> not sure what about other guys think but I'd say that there should not be any "fix" commits for previous commits in the same PR. fix commit should be reserved for fixing anything that is already in develop.
> 
> <img alt="image" width="516" src="https://private-user-images.githubusercontent.com/30367552/400379670-572ef890-d825-4955-b6a8-4dcee92d356b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNDMyNzIsIm5iZiI6MTczNjI0Mjk3MiwicGF0aCI6Ii8zMDM2NzU1Mi80MDAzNzk2NzAtNTcyZWY4OTAtZDgyNS00OTU1LWI2YTgtNGRjZWU5MmQzNTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDA5NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZWM2OGFhYzRmZTU2OGY0ODVjYjcyN2FhYzAzMDFhZDRhZDA4MjUyZWY5MmFlZGNhMGU1YWZiNzY1MGRmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fWSfnnqwnk5T0MJa0YR3w9AjVi087vdWGFVdvRtn_7c">
> doing it like this doesn't really help when writing changelogs - I don't want to state that I am fixing something which in fact hadn't been broken before this PR.
> 
> edit: lets please go with fix-ups for the purpose of review. they should be squashed later ofc.

The review is done, so I can squash this into one commit, right?

2025-01-07 09:52 UTC, tomasklim commented
@vladimirvolek

You can squash it but better is to separate it into some logical parts. Thanks!

e.g. blockchain-link changes in separate commit

2025-01-07 13:02 UTC, tomasklim approved these changes

2025-01-07 13:09 UTC, tomasklim commented
Closing in favor of #16228 to run CI and separate commits

2025-01-07 13:09 UTC, closed without merging