fix(suite-common): resolve formatAmount TODO in try catch block
trezor/trezor-suite pull request #16058
Opened 2024-12-19 14:24 UTC by izmy

## Description

`formatAmount` should not return "-1", it should just throw an error

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11450

2024-12-20 09:16 UTC, tomasklim approved these changes

2024-12-20 19:34 UTC, tomasklim requested changes
unit tests

2025-01-09 19:11 UTC, izmy commented
> Please fix unit tests

I had to change the method a little more because tests and the entire app code relied on that `formatAmount` to return some value. So I added `safeAmount` which sets '0' for undefined or empty string. The exception is thrown only if the value is not a number.

2025-01-20 12:49 UTC, tomasklim commented
/rebase

2025-01-20 12:56 UTC, tomasklim approved these changes

2025-01-22 11:34 UTC, merged