feat(suite): add posssibility to do a wallet backup before fw update
trezor/trezor-suite pull request #16094
Opened 2024-12-22 09:45 UTC by MiroslavProchazka

Adding the option to perform a wallet backup prior to a firmware update

2024-12-22 10:37 UTC, MiroslavProchazka commented on packages/connect-common/files/firmware/t2b1/releases.json
> +    {
This is here just for easier testing, needs to be deleted before merge!

2024-12-27 11:14 UTC, tomasklim requested changes

2024-12-27 11:14 UTC, tomasklim commented on packages/suite/src/support/messages.ts
> +        defaultMessage: 'CHeck backup!',
**Ch**eck backup

2024-12-27 11:14 UTC, tomasklim commented on packages/suite-data/files/translations/en.json
> +  "TR_BEFORE_ANY_FURTHER_ACTIONS": "Although unlikely, you may need to access your wallet backup in the event of a firmware update issue. If you’re uncertain about the accuracy of your backup, you ca
the copy seems too long. I would not read it. How about using yellow warning banner

2024-12-27 11:15 UTC, tomasklim commented on packages/suite/src/components/firmware/CheckSeedStep.tsx
> +    const handleCheckBackupClick = () => {
```suggestion
    const onCheckBackup = () => {
```

2025-01-02 13:46 UTC, MiroslavProchazka commented on packages/suite/src/support/messages.ts
> +        defaultMessage: 'CHeck backup!',
a2ddf5cae381d432682cf78f74f1f55ec70423a2

2025-01-02 13:47 UTC, MiroslavProchazka commented on packages/suite/src/components/firmware/CheckSeedStep.tsx
> +    const handleCheckBackupClick = () => {
a2ddf5cae381d432682cf78f74f1f55ec70423a2

2025-01-02 14:14 UTC, peter-sanderson approved these changes

2025-01-02 14:16 UTC, peter-sanderson commented
I am not sure about the order of the buttons (and variant)
![image](https://github.com/user-attachments/assets/b657157c-2e50-4590-a8f6-bd1155dc5180)

Th backup on the right with primary variant seems a bit odd (I would expect continue there).

:pray: check with product/design (if you already hadn't done that, in that case please ignore my comment)

2025-01-02 16:21 UTC, komret requested changes

2025-01-02 16:21 UTC, komret commented on packages/suite/src/components/firmware/CheckSeedStep.tsx
> +                    <Button onClick={onCheckBackup} variant="tertiary">
We should only display this if the device is backed up. Check for `isBackedUp`.

2025-01-02 16:21 UTC, komret commented on packages/suite/src/support/messages.ts
> +    TR_CHECK_BACKUP: {
Let's just use `TR_CHECK_RECOVERY_SEED`, I don't think we need a new string for this.

2025-01-02 17:05 UTC, komret commented on packages/suite/src/components/firmware/CheckSeedStep.tsx
> +        dispatch(goto('recovery-index'));
You'll also need to call `resetReducer` from `useFirmwareInstallation` here (before redirecting), otherwise the modal will reopen on this step instead of the first one when you open it next time.

2025-01-03 09:31 UTC, komret commented
Closing in favour of https://github.com/trezor/trezor-suite/pull/16144 🙃

2025-01-03 09:31 UTC, closed without merging