Refactor and add Receive
trezor/trezor-suite pull request #224
Opened 2019-07-08 10:16 UTC by vladimirvolek

2019-07-30 10:40 UTC, slowbackspace commented
css need some work to look like in the next wallet, otherwise ok!
<img width="856" alt="Screenshot 2019-07-30 at 12 36 33" src="https://user-images.githubusercontent.com/6961901/62122939-21fd5f80-b2c7-11e9-95d9-4ae7a642f054.png">

2019-07-30 10:41 UTC, slowbackspace approved these changes

2019-07-30 10:41 UTC, slowbackspace requested changes
tests failing https://gitlab.corp.sldev.cz/trezor/trezor-suite/pipelines/6650

2019-07-31 20:50 UTC, vladimirvolek commented
https://suite.corp.sldev.cz/suite-web/add-receive/wallet/account/receive/#/eth/0

2019-08-01 07:55 UTC, merged