Feat/fee box layout fix
trezor/trezor-suite pull request #2420
Opened 2020-09-23 14:10 UTC by robertbrada

Fix https://github.com/trezor/trezor-suite/issues/2360

2020-09-23 15:20 UTC, slowbackspace commented on packages/suite/src/views/wallet/send/components/Fees/index.tsx
> +        min-height: 55px;
ehhh that's hacky, approved! 😀

2020-09-23 15:26 UTC, slowbackspace commented on packages/suite/src/views/wallet/send/components/Fees/index.tsx
> +        min-height: 55px;
hmm maybe if would be a bit nicer if the crypto/fiat amount acted as a second column (first column being fee selector including text and input for custom fee below), DESIGN ATTACHED (red rectangles are representing columns)

<img width="438" alt="Screenshot 2020-09-23 at 17 26 11" src="https://user-images.githubusercontent.com/6961901/94034081-e292ac00-fdc1-11ea-8dba-0688ed3283d0.png">

2020-09-23 15:48 UTC, robertbrada commented on packages/suite/src/views/wallet/send/components/Fees/index.tsx
> +        min-height: 55px;
Nice design! I agree the layout logic could probably be redesigned as opposed to the current state. I will take a look at it

2020-09-24 12:12 UTC, slowbackspace requested changes

2020-09-24 12:12 UTC, slowbackspace commented on packages/suite/src/views/wallet/send/components/Fees/index.tsx
> -    @media all and (max-width: ${variables.SCREEN_SIZE.SM}) {
Some wrapping is still needed as the new layout won't work on smaller screens as the fee selector is taking too much space 
<img width="531" alt="Screenshot 2020-09-24 at 14 06 07" src="https://user-images.githubusercontent.com/6961901/94142785-1a0b6200-fe6f-11ea-9f8d-d89c1135abd7.png">


I would expect amounts move under the selector just like it used to be. Imo there is no need for grid as it should be easy job for flexbox.
<img width="592" alt="Screenshot 2020-09-24 at 14 10 00" src="https://user-images.githubusercontent.com/6961901/94143172-c2212b00-fe6f-11ea-90db-6080ea6957b5.png">

2020-09-24 12:16 UTC, slowbackspace commented on packages/suite/src/views/wallet/send/components/Fees/index.tsx
> -    @media all and (max-width: ${variables.SCREEN_SIZE.SM}) {
you can even render different layout for large and small screens and you don't have to rely just on media queries. There is useLayoutSize hook that will return a boolean if the mobile layout is active 
` const { isMobileLayout } = useLayoutSize();`. So you can conditionally render different component (or just pass some prop to it) to do necessary adjustments

2020-09-28 13:30 UTC, slowbackspace commented on packages/suite/src/views/wallet/send/components/Fees/index.tsx
> +            <></>
nitpick, just return null instead `... : null`

2020-09-28 13:33 UTC, slowbackspace approved these changes
that will work! (at least in most cases 😅)

2020-10-01 06:43 UTC, szymonlesisz commented
i think properly written `display: grid` will solve this "folding/overflowing" issue eventually :)
but for now it's better than it was :)

2020-10-01 06:44 UTC, merged