Desktop Titlebar - Fixes and improvements (functionality and style)
trezor/trezor-suite pull request #2733
Opened 2020-10-23 13:03 UTC by keraf

This change addresses the following issues:
- Buttons were not clickable (drag area was overlaying them).
- Maximize/Unmaximize state was properly set.

Also includes visual changes:
- Reduced height of the title bar from 40px to 28px.
- Win/Linux buttons get highlighted on hover and have a background (grey for all buttons except close which has a red background).
- Icons in Mac buttons get displayed on hover (mimic native system behaviour).
- Increased icon size for Mac.

Future improvements (not part of this PR):
- Mac specific icons for maximize/unmaximize buttons.

**Current**
![https://i.imgur.com/ZoVtrTJ.gif](Win/Linux)
![https://i.imgur.com/rLZysAe.gif](Mac)

**New**
![https://i.imgur.com/4ne2kLC.gif](Win/Linux)
![https://i.imgur.com/vWZYbDg.gif](Mac)

2020-10-23 15:00 UTC, tomexx requested changes
some cosmetics, otherwise I like it 👍

2020-10-23 15:00 UTC, tomexx commented on packages/suite-desktop/src-electron/electron.ts
> +    mainWindow.on('maximize', () => {
`resize` and `move` events were used to handle situations such as moving or resizing window after maximization (they are also triggered when maximizing and unmaximizing) (Mac only issue I guess)

2020-10-23 15:00 UTC, tomexx commented on packages/suite-desktop/src/support/DesktopTitlebar.tsx
> +const TITLEBAR_HEIGHT = 28;
this should be consulted with @matejzak, the original size matches the design, also applies for the size of Mac controls

2020-10-23 15:00 UTC, tomexx commented on packages/suite-desktop/src/support/DesktopTitlebar.tsx
> +                    {(!isMac || hover !== '') && (
maybe let's create a helper for this as it is used more times

2020-10-23 15:00 UTC, tomexx commented on packages/suite-desktop/src/support/DesktopTitlebar.tsx
> +                            color={!isMac && hover === 'close' ? colors.WHITE : iconColor}
let's also create a parametric helper for this

2020-10-26 09:07 UTC, keraf commented on packages/suite-desktop/src/support/DesktopTitlebar.tsx
> +                            color={!isMac && hover === 'close' ? colors.WHITE : iconColor}
Addressed in 4ae6b40

2020-10-26 09:07 UTC, keraf commented on packages/suite-desktop/src/support/DesktopTitlebar.tsx
> +                    {(!isMac || hover !== '') && (
Addressed in 4ae6b40

2020-10-26 09:07 UTC, keraf commented on packages/suite-desktop/src-electron/electron.ts
> +    mainWindow.on('maximize', () => {
Addressed in 4ae6b40

2020-10-26 09:13 UTC, keraf commented on packages/suite-desktop/src-electron/electron.ts
> +    mainWindow.on('maximize', () => {
I used the `moved` event instead. It should always be fired once after the window gets moved or resized on Mac.

2020-10-26 11:41 UTC, tomexx requested changes

2020-10-26 11:41 UTC, tomexx commented on packages/suite-desktop/src-electron/electron.ts
> +    mainWindow.on('maximize', () => {
Resize is still needed :(

It handles the case when you maximize and then resize the screen. Currently after you maximize and then resize the screen the restore button stays in "restore" mode and does nothing when you click on it (on Mac).

2020-10-26 11:51 UTC, matejzak commented on packages/suite-desktop/src/support/DesktopTitlebar.tsx
> +const TITLEBAR_HEIGHT = 28;
Thank you guys! The change is OK with me. We will enlarge the bar again, once search is included.. 🔜  🙏🏽 ☺️

2020-10-26 14:52 UTC, tomexx approved these changes

2020-10-26 15:10 UTC, merged

2020-10-26 15:10 UTC, tsusanka commented
Squashed on Raf's behalf and merged.

2020-10-26 18:59 UTC, tsusanka commented
Cherry-picked to `release/2020-10-beta`.