fix(google-provider): differences between web and desktop in google oauth
trezor/trezor-suite pull request #2753
Opened 2020-10-26 11:09 UTC by mroz22

If I am correct, google [does not allow](https://developers.google.com/identity/protocols/oauth2#clientside
) long-lived tokens on client side javascript in browser (without backend) 

It is actually  possible to use client_id for application of type iOS (which we use for [desktop](https://developers.google.com/identity/protocols/oauth2#clientside
)) for web on localhost. You can try it on current develop branch after flipping google feature flag to true but it fails for other hosts. 

So only way around this (and please correct me if I am wrong) is to support implicit grant for google/web and authorization code flow for google/desktop.

2020-11-06 12:44 UTC, mroz22 commented
Ok, mosty done here. I'd say it is ready to review, it just needs to add prober app id which is the last todo to do.

2020-11-06 12:45 UTC, mroz22 commented on packages/suite/src/actions/suite/constants/metadataConstants.ts
> +    '842348096891-efhc485636d5t09klvrve0pi4njhq3l8.apps.googleusercontent.com';
todo

2020-11-09 12:30 UTC, szymonlesisz requested changes

2020-11-09 12:30 UTC, szymonlesisz commented on packages/suite-data/files/oauth/oauth_receiver.html
> +            var message = window.location.hash || window.location.search;
use both in message (search and hash)

2020-11-09 12:30 UTC, szymonlesisz commented on packages/suite/src/services/google.ts
> +                process.env.SUITE_TYPE === 'web'
isWeb utility

2020-11-09 12:30 UTC, szymonlesisz commented on packages/suite/src/services/google.ts
>          const accessToken = await this.oauth2Client.getAccessToken();
? token validation discussion

2020-11-09 12:30 UTC, szymonlesisz commented on packages/suite/src/utils/suite/oauth.ts
> +    const dfd: Deferred<{ code?: string; access_token?: string }> = createDeferred();
?

2020-11-09 14:14 UTC, mroz22 commented
hmm one more todo: 
- [ ] providers that do not support token renewal should be periodically fetching data (and thus validate token under the hood). If it turns out that token is no logner valid, such provider should not react with displaying error but simply disconnect provider while keeping metadata in place? So that user will see all metadata even after provider has disconnected. Just won't be able to edit them without manual reauthentication.

2020-11-12 13:55 UTC, mroz22 commented on packages/suite/src/services/google.ts
>          const accessToken = await this.oauth2Client.getAccessToken();
Should be ok! From jsdoc definition: 
```
 /**
     * Get a non-expired access token, after refreshing if necessary
     *
     * @param callback Callback to call with the access token
     */
```

2020-11-13 09:40 UTC, mroz22 commented
Review requests addressed in 20d1af3010a97dfe6e374fd9784960b2a1705a4d

2020-11-16 10:17 UTC, szymonlesisz approved these changes

2020-11-16 17:33 UTC, merged