feat(suite-web-landing): Add OG meta tags
trezor/trezor-suite pull request #2806
Opened 2020-10-29 21:13 UTC by tomexx

- added social meta tags

2020-10-29 22:03 UTC, prusnak requested changes

2020-10-29 22:03 UTC, prusnak commented on packages/suite-web-landing/pages/_document.tsx
> +                    <meta property="og:url" content="https://metatags.io/" />
```suggestion
                    <meta property="og:url" content="https://suite.trezor.io/" />
```

2020-10-29 22:03 UTC, prusnak commented on packages/suite-web-landing/pages/_document.tsx
> +                    <meta property="twitter:url" content="https://metatags.io/" />
```suggestion
                    <meta property="twitter:url" content="https://suite.trezor.io/" />
```

2020-10-29 22:03 UTC, prusnak commented on packages/suite-web-landing/pages/_document.tsx
> +                        content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png"
replace with local copy of https://user-images.githubusercontent.com/29627086/97498925-4eda6f80-196d-11eb-8f54-ae8cfe76ce62.png

2020-10-29 22:03 UTC, prusnak commented on packages/suite-web-landing/pages/_document.tsx
> +                        content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png"
replace with local copy of https://user-images.githubusercontent.com/29627086/97498925-4eda6f80-196d-11eb-8f54-ae8cfe76ce62.png

2020-10-30 09:23 UTC, prusnak approved these changes

2020-10-30 09:43 UTC, keraf approved these changes

2020-10-30 09:43 UTC, merged