chore: cleanup Ticker and reuse current rate
trezor/trezor-suite pull request #3103
Opened 2020-12-01 15:29 UTC by slowbackspace

this should fix incorrect arrow color on price movements

2020-12-01 16:10 UTC, slowbackspace commented on packages/suite/src/actions/wallet/fiatRatesActions.ts
> +    const timestamps = [weekAgoTimestamp];
you may be wondering why I am keeping it as an array. 2 reasons:
1. it has always been an array and I don't want to write db migrations 😓 
2. I heard some plans that in the future we will again start showing graph for exchange rate, so I don't want to write migrations twice! (one for array -> number second for number -> array)

2020-12-03 16:08 UTC, mroz22 requested changes

2020-12-03 16:08 UTC, mroz22 commented on packages/suite/src/components/suite/Ticker/index.tsx
> +    const rateGoingUp = currentRate && lastWeekRate ? currentRate >= lastWeekRate : false;
what if bitcoin crashed to `0` last week and current rate is new ATH? Then you would fall into `false` which seems incorrect. Isn't that also case for `??`?

2020-12-03 16:09 UTC, mroz22 approved these changes

2020-12-03 16:09 UTC, merged