Feat/invity spend
trezor/trezor-suite pull request #3175
Opened 2020-12-11 18:08 UTC by vladimirvolek

2021-01-05 17:45 UTC, keraf requested changes

2021-01-05 17:45 UTC, keraf commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +        const template = this.applyTemplate(`
`applyTemplate` is not needed here as this method just takes the first parameter and puts it between valid HTML tags. As you provide valid HTML here, you can just add it to the response directly.

See `packages/suite-desktop/src-electron/libs/http-receiver.ts` line 135.

2021-01-05 17:45 UTC, keraf commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +        // eslint-disable-next-line no-useless-escape
Is this exception really needed?

2021-01-05 17:45 UTC, keraf commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +                        // eslint-disable-next-line no-useless-escape
Same exception comment here.

2021-01-05 23:23 UTC, martinboehm commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +        const template = this.applyTemplate(`
Done

2021-01-05 23:23 UTC, martinboehm commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +        // eslint-disable-next-line no-useless-escape
Done

2021-01-05 23:24 UTC, martinboehm commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +                        // eslint-disable-next-line no-useless-escape
Done

2021-01-07 13:57 UTC, szymonlesisz requested changes

2021-01-07 13:57 UTC, szymonlesisz commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +                        const urlParams = new URLSearchParams(window.location.search);
`URLSearchParams` may not work correctly in all browsers. (example IE)
since we dont know which browser will be used there should be a polyfill/fallback for that, or it should be replaced by some vanilla-js minified one-liner, like this: https://stackoverflow.com/a/3855394

2021-01-07 13:57 UTC, szymonlesisz commented on packages/suite/src/actions/suite/modalActions.ts
> +import { Route } from '@suite-constants/routes';
```suggestion
import { Route } from '@suite-types';
```
its already there

2021-01-07 17:26 UTC, martinboehm commented on packages/suite/src/actions/suite/modalActions.ts
> +import { Route } from '@suite-constants/routes';
Done

2021-01-12 13:31 UTC, martinboehm commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +                        const urlParams = new URLSearchParams(window.location.search);
According to caniuse URLSearchParams is not supported only by IE and Opera Mobile. I tested Bitrefill in IE11 and it does not really work anyway. It does not make sense to add messy polyfill in this case.

2021-01-13 15:07 UTC, szymonlesisz commented on packages/suite-desktop/src-electron/libs/http-receiver.ts
> +                        const urlParams = new URLSearchParams(window.location.search);
i was thinking more like:
`var params=function(r){if(""==r)return{};for(var e={},n=0;n<r.length;++n){var t=r[n].split("=",2);1==t.length?e[t[0]]="":e[t[0]]=decodeURIComponent(t[1].replace(/\+/g," "))}return e}(window.location.search.substr(1).split("&"));`

but i leave it to you to decide, maybe it's not worth it

2021-01-13 15:09 UTC, szymonlesisz approved these changes

2021-01-14 15:03 UTC, merged