add language picker to components
trezor/trezor-suite pull request #32
Opened 2019-05-20 10:32 UTC by mroz22

2019-05-22 10:47 UTC, keip approved these changes

2019-05-23 19:59 UTC, slowbackspace requested changes

2019-05-23 19:59 UTC, slowbackspace commented on packages/components/src/stories/components/other.js
> +import CoinLogo from 'components/CoinLogo';
we have to keep paths relative for now

2019-05-30 08:43 UTC, slowbackspace approved these changes

2019-05-30 13:34 UTC, merged