add few regression tests on routes
trezor/trezor-suite pull request #322
Opened 2019-07-30 12:07 UTC by mroz22

just visit all possible routes. might be useful for detecting breaking changes in next routing in the future :D

2019-07-30 17:59 UTC, vladimirvolek requested changes
404 also has html right?

2019-08-01 10:59 UTC, mroz22 commented
Hmm. we need emulator for this. All the routes (now) require connected device to display something different from the welcome screen. Even 404 page now does not show until you connect device.

2019-08-01 13:58 UTC, mroz22 commented
Imho it is all I can get with the current codebase now. Of course route '/bridge' and probably 404 should be accessible without connected device, but it is currently not. Created issue for this https://github.com/trezor/trezor-suite/issues/349

2019-08-08 11:18 UTC, vladimirvolek approved these changes

2019-08-08 11:18 UTC, merged