chore: upgrade react 17, next 10, react-native 0.63.4 and other deps
trezor/trezor-suite pull request #3259
Opened 2021-01-12 18:05 UTC by slowbackspace

react 17 next 10,  react native 0.63.4, storybook 6

some notes:
- bumped `next-transpile-modules` only to version 4, 4 => 6 contains more breaking changes and there is high probability of braking too many things at once https://github.com/martpie/next-transpile-modules/releases/tag/5.0.0
- replaced `next-images` with `next-optimized-images`, old package was no longer updated and for some reason it broke with nextjs 10. It would be nice to add plugin for actual img optimalization so I left a todo in the nextjs config.
- removed `next-plugin-custom-babel-config` as it doesn’t seem to be necessary
- kept `next-redux-wrapper` at older version for now => some hopefully easy refactor needed https://github.com/kirill-konshin/next-redux-wrapper/releases/tag/6.0.0
- kept `recharts` at 2.0.0-beta.1 due to types bug in stable 2.0.0 release (https://github.com/recharts/recharts/issues/2360)
- kept `pako` at 1.x.x due to runtime error with 2.x.x during setting a homescreen image on T2
- kept `ethereumjs-util` at 6, version 7 throws an error while validating string that doesn't start with 0x
- forced resolving @types/react to 17.0.0 in all packages. Many packages have still max allowed version of react set to 16. This is causing 2 different versions of @types/react being used which makes TS complain about type incompatibility. React 17 didn’t bring any new features so there was not much initiative in JS ecosystem to uprade. However this is changing as create-react-app started to include react 17 as default, now people are opening issues requesting maintainers to update their packages to support react 17.  🔜

2021-01-13 14:28 UTC, szymonlesisz requested changes

2021-01-13 14:28 UTC, szymonlesisz commented on packages/suite/src/hooks/suite/useAsyncDebounce.ts
> +            const newTimeout = (setTimeout(timeoutDfd.resolve, 300) as unknown) as TimeoutType; // needed with @types/react-native 0.63.45, could be a bug
don't be afraid to use ts-ignore with comment instead of this crazy syntax

2021-01-13 16:16 UTC, szymonlesisz approved these changes

2021-01-14 10:27 UTC, keraf approved these changes

2021-01-14 11:03 UTC, szymonlesisz approved these changes

2021-01-14 11:04 UTC, merged