Add Changelog check to CI
trezor/trezor-suite pull request #3398
Opened 2021-02-12 15:56 UTC by tsusanka

This adds a [changelog reminder](https://github.com/marketplace/actions/changelog-reminder) into Github Actions which checks if CHANGELOG.md has been modified in the PR. If not the job fails. In case you wish not to add anything to Changelog (which should not be often) you can add the "no Changelog" label and the job passes then.

Examples:
- Success: https://github.com/tsusanka/trezor-suite/pull/3
- Fail: https://github.com/tsusanka/trezor-suite/pull/4
- Success thanks to label: https://github.com/tsusanka/trezor-suite/pull/5

2021-02-12 16:48 UTC, keraf reviewed
Looks good. We should communicate this on Slack and specify it in the documentation as well (how to ignore this, what format to use for the change log, etc...).

2021-02-13 11:23 UTC, slowbackspace approved these changes
🎉

2021-02-13 17:22 UTC, tsusanka commented
@keraf documentation added in b87635034fac63dee8737ae1bf64883f30a6a33c. I will post on Slack after this PR is being merged.

2021-02-13 17:24 UTC, keraf approved these changes

2021-02-14 20:44 UTC, keraf requested changes
Just remembered that the summary file needs to be updated in the docs to link to the new page.

2021-02-15 08:17 UTC, tsusanka commented
Good catch, added. @keraf please check.

2021-02-15 10:03 UTC, keraf approved these changes
All good now!

2021-02-15 10:03 UTC, merged