fix(account-navigation): post-merge fixes
trezor/trezor-suite pull request #3612
Opened 2021-04-07 20:54 UTC by tomexx

fixes #3607

1. Back button is visible in Settings for a short time after coming from Send/Receive etc. - **I was not able to reproduce this**
2. User is redirected to Overview after signing the transaction
3. Header in detail is not duplicated anymore
4. Active tab states in settings fixed
5. Padding added to tab content
6. Tabs vs Back button height fixed

2021-04-08 10:53 UTC, szymonlesisz requested changes

2021-04-08 10:53 UTC, szymonlesisz commented on packages/suite/src/actions/wallet/sendFormActions.ts
> +        dispatch(routerActions.goto('wallet-index', undefined, true));
this action is shared between send/rbf/invity forms so redirection should be done from send component/hook instead.
another important fact is that there should be a result check before redirection, there could be an error (failed to send...)

move it to `useSendForm` hook [sign method](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/hooks/wallet/useSendForm.ts#L224) pls

2021-04-09 07:41 UTC, tsusanka commented
Could we finish this today so I can pass a new release candidate? :)

2021-04-09 08:32 UTC, tomexx commented
> Could we finish this today so I can pass a new release candidate? :)

I had some troubles with updating unit tests, but @szymonlesisz helped me with that. It should be ready to go now. 👍

2021-04-09 09:22 UTC, goodhoko approved these changes

2021-04-09 09:58 UTC, szymonlesisz approved these changes
approving changes in send, didn't test actual UI

2021-04-09 10:08 UTC, merged