feat(suite): btn to dump reducer's data from debug settings
trezor/trezor-suite pull request #3720
Opened 2021-05-06 10:16 UTC by slowbackspace

close https://github.com/trezor/trezor-suite/issues/3719

no data censoring, just for QA purposes (that's why it is hidden in debug settings).
I would really like to see this as a public facing feature after implementing bulletproof censoring of sensitive data (balances, addresses, txids, xpubs,...).

2021-05-11 11:00 UTC, keraf requested changes
I think this approach is alright but could be better. Ideally we should have a QA/tools overlay to do this at any point in the application, without having to navigate away from what we were doing.

2021-05-11 11:00 UTC, keraf commented on packages/suite/src/actions/suite/suiteActions.ts
> +    saveAs(b, `suite_reducers_${process.env.VERSION}_${timestamp}.txt`);
Should probably be saved as `.json`. And maybe worth adding a content header as well.

2021-05-18 23:18 UTC, tomexx commented
We discussed it in QA Slack channel and they can simply run `JSON.stringify(__NEXT_REDUX_STORE__.getState())` directly from console (we should document it somewhere maybe).

But I think we still can proceed with Maros' PR and make the dump tool more accessible later on.

2021-07-20 13:43 UTC, matejkriz commented
feel free to reopen...

2021-07-20 13:43 UTC, closed without merging