fix(suite): link to the issue
trezor/trezor-suite pull request #3896
Opened 2021-06-14 09:51 UTC by pingpwned

fix #3886

2021-06-15 10:50 UTC, goodhoko approved these changes
LGTM

2021-06-16 07:07 UTC, tomasklim requested changes

2021-06-16 07:07 UTC, tomasklim commented on packages/suite/src/constants/suite/urls.ts
> +    'https://trezor.io/support/technical/i-cannot-access-the-wallet/';
```suggestion
export const WALLET_ACCESS_URL =
    'https://trezor.io/support/technical/i-cannot-access-the-wallet/';
```
All other variables have `URL` in its name. I would keep it consistent

2021-06-18 05:59 UTC, tomasklim approved these changes
LGTM, please squash it

2021-06-18 08:48 UTC, merged