Unify link components
trezor/trezor-suite pull request #4231
Opened 2021-09-06 05:39 UTC by ravinalamada

Hi all,

Changes for the unify-link-component branch are made in this branch. Please have a look at it ([(issue  #3633).](https://github.com/trezor/trezor-suite/issues/3633))

2021-09-07 12:50 UTC, tomasklim requested changes
+ I would change the commit message https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

chore(suite): replace externalLink component by trezorLink component

2021-09-07 12:50 UTC, tomasklim commented on packages/suite/src/components/settings/SettingsMenu/index.tsx
> +const StyledLink = styled(TrezorLink)`
It should not be underlined.
![Screenshot 2021-09-07 at 14 27 58](https://user-images.githubusercontent.com/33235762/132344520-69d4a4b3-3722-49fc-abcd-865d5241c53d.png)
![Screenshot 2021-09-07 at 14 28 04](https://user-images.githubusercontent.com/33235762/132344532-e750da4f-2a46-43c3-94f3-39e5bbf69638.png)

2021-09-07 12:50 UTC, tomasklim commented on packages/suite/src/components/suite/modals/AddAccount/components/AccountTypeDescription.tsx
> +            <TrezorLink href={url} size="small">
Icon is missing in your implementation

![Screenshot 2021-09-07 at 14 31 37](https://user-images.githubusercontent.com/33235762/132344981-36751083-aa34-4ba9-a3b5-0a2e4c600646.png)
![Screenshot 2021-09-07 at 14 31 41](https://user-images.githubusercontent.com/33235762/132344986-4cbdf3d0-e61e-4602-95f4-19a844e61b7a.png)

2021-09-07 12:50 UTC, tomasklim requested changes

2021-09-07 12:50 UTC, tomasklim commented on packages/suite/src/views/settings/index.tsx
> -                                                <VersionLink
Underline should not be there
![Screenshot 2021-09-07 at 14 35 48](https://user-images.githubusercontent.com/33235762/132345594-005d9adb-9e6b-4bd2-829d-07025d5d6c72.png)
![Screenshot 2021-09-07 at 14 35 55](https://user-images.githubusercontent.com/33235762/132345597-bbfa4fd0-7a9f-4a84-a1dc-0c17a37e3ff3.png)

2021-09-08 06:16 UTC, ravinalamada commented
> * I would change the commit message https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
> 
> chore(suite): replace externalLink component by trezorLink component

Ok, thanks for the advice

2021-09-09 09:05 UTC, tomasklim requested changes

2021-09-09 09:05 UTC, tomasklim commented on packages/suite/src/components/settings/SettingsMenu/index.tsx
> +const StyledLink = styled(TrezorLink)`
❌ @ravinalamada Did you test it?

2021-09-09 09:05 UTC, tomasklim commented on packages/suite/src/views/settings/index.tsx
> -                                                <VersionLink
❌ @ravinalamada There is also version of app in settings where it is still underlined

2021-09-28 08:53 UTC, closed without merging