fix(contenteditable): recalculate caret after click & add onPaste event
trezor/trezor-suite pull request #4340
Opened 2021-10-06 08:32 UTC by pingpwned

fix #3153 
also paste was not working properly, not sure if there's an issue

2021-10-06 09:43 UTC, mroz22 requested changes

2021-10-06 09:43 UTC, mroz22 commented on packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx
> +            window.addEventListener(
this listener should be deregistered on component unmount also

2021-10-06 09:52 UTC, mroz22 commented
also it makes cursor jumping to the end everytime I click somewhere within the label. Feels maybe even more confusing than current behavior :smile_cat:

2021-10-06 10:36 UTC, pingpwned commented
> also it makes cursor jumping to the end everytime I click somewhere within the label. Feels maybe even more confusing than current behavior smile_cat

yeah, but you can use arrows for navigating within the label. Currently if you  click anywhere, even input field, it becomes inactive

2021-10-06 10:36 UTC, pingpwned commented on packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx
> +            window.addEventListener(
54657bd

2021-10-12 05:43 UTC, mroz22 approved these changes
works correctly.

2021-10-13 14:27 UTC, merged