feat(suite): e2e test tooltip & guide
trezor/trezor-suite pull request #4346
Opened 2021-10-06 16:47 UTC by dimasivan

- [x] Move Guide IndexNode initialization to reducer
- [x]  Test Tooltips
- [x] Test Guide

part of #3992

2021-10-12 06:00 UTC, mroz22 commented
I am only in process of reviewing yet. Just saw this error when running this on my machine 
![image](https://user-images.githubusercontent.com/30367552/136900144-6f38adff-6019-4ecd-a2a3-b6a990904b40.png)

2021-10-12 06:15 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/tooltip.test.ts
> +        // eslint-disable-next-line @typescript-eslint/naming-convention
probably unneeded eslint ignore?

2021-10-12 06:24 UTC, mroz22 requested changes

2021-10-12 06:24 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/tooltip.test.ts
> +            .getTestElement('@switch-device/add-hidden-wallet-button')
better then waiting is to change it like this: 
```
cy.getTestElement('@switch-device/add-hidden-wallet-button', { timeout: 20000 })
```
this increases the period cypress is retrying getTestElement command before it fails. It is better because you are saying: "you can wait" instead "you must wait"

2021-10-12 06:25 UTC, mroz22 requested changes
also when navigating through guide, I am seeing some errors. 
![image](https://user-images.githubusercontent.com/30367552/136902994-ae71933d-a37f-41ae-9af8-24c813dd82e5.png)

this is only because it does not exist in 'cs' variant? I still think we should somehow handle this. Expected errors should not print errors. Maybe it is configured not to print in production mode already? :thinking:

2021-10-12 08:37 UTC, dimasivan commented
> also when navigating through guide, I am seeing some errors. ![image](https://user-images.githubusercontent.com/30367552/136902994-ae71933d-a37f-41ae-9af8-24c813dd82e5.png)
> 
> this is only because it does not exist in 'cs' variant? I still think we should somehow handle this. Expected errors should not print errors. Maybe it is configured not to print in production mode already? thinking

@mroz22 In code, it is try catch block inside another try catch block. If first try (the one with language settings) fails, catch block logs error and trying default language, if fails again, logging second error. Honestly, don't know if there's an issue with that, maybe if it fails with language settings, logging can be changed from error to info?

2021-10-15 08:01 UTC, dimasivan commented on packages/integration-tests/projects/suite-web/tests/suite/tooltip.test.ts
> +        // eslint-disable-next-line @typescript-eslint/naming-convention
854f944  fixed also in `guide.test.ts`

2021-10-18 13:40 UTC, mroz22 approved these changes
lgtm now :rocket:

2021-10-19 08:39 UTC, merged