fix: make use of tor settings in news feed
trezor/trezor-suite pull request #4362
Opened 2021-10-11 19:33 UTC by mroz22

Hello, I am opening this PR to resolve #3793

cce61c6 implements suite.settings.torOnionLinks in dashboard news feed 
92794ea makes an attempt to refactor duplicated logic between NewsFeed and TrezorLink component by introducing useTorUrl hook. I have always hard time deciding if I actually like these hook-like solutions, so your input is welcome here definitely
b76f451 turning tor off should probably also turn suite.settings.torOnionLinks off.

2021-10-12 12:32 UTC, tomasklim requested changes

2021-10-12 12:32 UTC, tomasklim commented on packages/suite/src/views/settings/index.tsx
> +                                            // does not make sense to use onion links if tor is being disabled
_I am not Tor professional._

Does it make sense to disable it? Maybe someone wants to open onion links even when Suite Tor is disabled, because he has some kind of Tor for the whole system. 
But it looks like that when you have Tor disabled, but onion links enabled, it does not respect it.

Another problem is that if you disable Tor, it takes some time for the switch to move to the left, but onion links switch moves instantly. Maybe we should wait for Tor to be properly disabled and then disable onion links?

2021-10-12 12:32 UTC, tomasklim commented on packages/suite/src/hooks/suite/useTorUrl.ts
> +export const useTorUrl = (originalUrl?: string) => {
I dont like the name of hook. It sounds like that it always returns Tor URL. 

What about `useExternalLink`, `useExternalLinkUrl` or something similar?

In message system config we use `external-link` and `internal-link`.

2021-10-12 12:32 UTC, tomasklim commented on packages/suite/src/hooks/suite/useTorUrl.ts
> +export const useTorUrl = (originalUrl?: string) => {
When talking about Messaging system, could you please use your hook in `MessageSystemBanner` component, line 36? We do not use onion link there. I am not sure if we can use Tor URL for links which are not `trezor.io` but at least we can do it for `trezor.io` links?

2021-10-13 14:11 UTC, mroz22 commented on packages/suite/src/hooks/suite/useTorUrl.ts
> +export const useTorUrl = (originalUrl?: string) => {
added in 39d4834 
also needed to make tor domain handling more generic which you can see here 
3c2a737

2021-10-14 07:35 UTC, tomasklim requested changes

2021-10-14 07:35 UTC, tomasklim commented on packages/suite-web-landing/pages/_document.tsx
> +                        />
Does it make sense to have onion meta tag on landing page? Landing page is not in desktop app

2021-10-14 07:35 UTC, tomasklim commented on packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx
> +                window.open(tor && torOnionLinks ? getTorUrlIfAvailable(link) : link, '_blank');
We cannot use `useExternalLink` hook here right? 😞  So we duplicate the logic again

2021-10-14 07:35 UTC, tomasklim commented on packages/suite/src/views/dashboard/components/NewsFeed/index.tsx
> +import { ArrayElement } from '@suite/types/utils';
```suggestion
import type { ArrayElement } from '@suite/types/utils';
```

2021-10-14 07:37 UTC, mroz22 commented on packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx
> +                window.open(tor && torOnionLinks ? getTorUrlIfAvailable(link) : link, '_blank');
we can, but does it make sense? does it help imporve readabilit? using externalLink hook for general link which might be of type internal or external? not sure  about that.

2021-10-14 07:38 UTC, mroz22 commented on packages/suite/src/views/settings/index.tsx
> +                                            // does not make sense to use onion links if tor is being disabled
@alex-jerechinsky ? product? heeelp

2021-10-19 13:53 UTC, tomasklim approved these changes

2021-10-20 06:32 UTC, merged