Fix/3153 Labelling - Cursor dismissed when clicking account title during editing label
trezor/trezor-suite pull request #4389
Opened 2021-10-19 08:31 UTC by pingpwned

fix caret and its position:
labeling wallet :white_check_mark:  
labeling account :white_check_mark: 
labeling transaction :white_check_mark: 

fix #3153

2021-10-21 14:10 UTC, tomasklim requested changes
I would change the cursor to `cursor: text` when editing of the label is enabled. 🔴 

- Transactions ✅ 
- Received address ✅ 
- Account ✅ 
- Switch wallet ✅

2021-10-21 14:17 UTC, tomasklim commented on packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx
>      color: ${props => (!props.touched ? props.theme.TYPE_LIGHT_GREY : 'inherit')};
```suggestion
    color: ${props => (!props.touched ? props.theme.TYPE_LIGHT_GREY : 'inherit')};
    
    ${props =>
        props.value &&
        css`
            position: unset;
        `}
        
    ${props =>
        !props.value &&
        css`
          left: ${props.isButton ? '22px' : '0px'}
          right: 0;
          position: absolute;`}

```

2021-10-25 10:55 UTC, dimasivan commented on packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx
>      color: ${props => (!props.touched ? props.theme.TYPE_LIGHT_GREY : 'inherit')};
45460d0

2021-10-27 12:27 UTC, tomasklim requested changes
- [x] Is it possible to add e.preventDefault to the whole rectangle? I missed the ✅  button by 1px and it closed the modal. I also clicked on disabled `[Loader] Edit Label` and `[Check] Renamed` buttons and it closed the modal 😢
![Screenshot 2021-10-27 at 14 22 42](https://user-images.githubusercontent.com/33235762/139064834-c4d40534-dbe7-4f71-85df-60c533970e9e.png)

- [x] Cursor was not changed in the previous review. I would like to have `cursor: text` over the input when editing of the label is active. 
(e.g. when mouse cursor is over `Bitcoin #1` input)
![Screenshot 2021-10-27 at 14 26 31](https://user-images.githubusercontent.com/33235762/139065193-2edf3f7a-6611-45b2-ac29-6bbadc298831.png)

2021-10-29 08:05 UTC, dimasivan commented
>     * [x]  Is it possible to add e.preventDefault to the whole rectangle? I missed the white_check_mark  button by 1px and it closed the modal. I also clicked on disabled `[Loader] Edit Label` and `[Check] Renamed` buttons and it closed the modal cry
>       ![Screenshot 2021-10-27 at 14 22 42](https://user-images.githubusercontent.com/33235762/139064834-c4d40534-dbe7-4f71-85df-60c533970e9e.png)
> 
>     * [x]  Cursor was not changed in the previous review. I would like to have `cursor: text` over the input when editing of the label is active.
>       (e.g. when mouse cursor is over `Bitcoin #1` input)
>       ![Screenshot 2021-10-27 at 14 26 31](https://user-images.githubusercontent.com/33235762/139065193-2edf3f7a-6611-45b2-ac29-6bbadc298831.png)

@tomasklim 674c0e6e522ab1cc48540f7ae73f95122ef75ea7

`cursor: text` is already presented on your screenshot, but it was missed in the account select modal

2021-10-29 13:24 UTC, tomasklim approved these changes

2021-11-01 14:18 UTC, merged