feat: guide links between articles
trezor/trezor-suite pull request #4425
Opened 2021-10-26 08:10 UTC by pingpwned

should fix #4412 

using markdown links as `[text](NODE_ID)` e.g. `[some text](/security/pin.md)`

also fixing minor bug when linking between articles or open an article through tooltip when another is opened and scroll position is not top, it should scroll to top on new content

2021-10-27 20:03 UTC, tomasklim requested changes
Works great! You will probably have conflicts with https://github.com/trezor/trezor-suite/pull/4426

2021-10-27 20:03 UTC, tomasklim commented on packages/suite/src/views/guide/GuidePage.tsx
> +
nit: no space required

2021-10-27 20:03 UTC, tomasklim commented on packages/suite/src/views/guide/GuideMarkdown.tsx
> +                        href.startsWith('//') ? (
```suggestion
                        href.startsWith('https://') ? (
```
I think this should be the one we are looking for?

2021-10-27 20:03 UTC, tomasklim commented on packages/suite/src/views/guide/GuideMarkdown.tsx
> +                            </a>
Looks like that we miss `tor onion` links here. If you want, fix it or create an issue please.

I think you can use `<TrezorLink>` component which should solve it for you.

2021-10-29 06:51 UTC, dimasivan commented on packages/suite/src/views/guide/GuideMarkdown.tsx
> +                        href.startsWith('//') ? (
there's a http:// url in `privacy/tor.md` and links could also start with `//` to let browser to choose the protocol, but it seems we not using it. So maybe just `http` or `http:// || https://` is enough

2021-10-29 06:57 UTC, dimasivan commented on packages/suite/src/views/guide/GuidePage.tsx
> +
removed in 387a080

2021-10-29 06:58 UTC, dimasivan commented on packages/suite/src/views/guide/GuideMarkdown.tsx
> +                            </a>
387a080

2021-10-29 06:59 UTC, dimasivan commented on packages/suite/src/views/guide/GuideMarkdown.tsx
> +                        href.startsWith('//') ? (
I used `http` in 387a080 but we can discuss it later

2021-10-29 08:56 UTC, tomasklim approved these changes

2021-11-01 07:44 UTC, merged