Feat/3994 guide search
trezor/trezor-suite pull request #4426
Opened 2021-10-26 10:07 UTC by marekrjpolak

Could resolve #3994.
Preview here: https://suite.corp.sldev.cz/suite-web/feat/3994-guide-search/web/
Design: https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=7785%3A77266

2021-10-26 11:53 UTC, tomasklim requested changes

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/components/guide/GuideNode.tsx
> +    className?: string;
probably never used

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/views/guide/OpenGuideFromTooltip.tsx
> +import { useGuideOpenNode } from '@guide-hooks/useGuideOpenNode';
I would add index.ts into hooks/guide folder to import it like this
```suggestion
import { useGuideOpenNode } from '@guide-hooks';
```

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +const MIN_QUERY_LENGTH = 3;
Do we need this limit?

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +const max = (value: number, min: number) => (value < min ? min : value);
`Math.max()`?

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +        .trim();
![Screenshot 2021-10-26 at 12 28 48](https://user-images.githubusercontent.com/33235762/138869503-53ffab58-5d81-4e83-8d8b-9a0796e1969a.png)
Maybe we should also do something with this?

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +                          .then(md => searchInFile(url, querySanitized, md)),
```suggestion
                          .then((md: string) => searchInFile(url, querySanitized, md)),
```

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideLoadPage.ts
> +            });
😔😔😔 async/await 😭😭😭

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/components/guide/GuideSearch.tsx
> +    className,
`<GuideSearch />` never used with `className`

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/components/guide/GuideSearch.tsx
> +    className?: string;
move it to separate type variable

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/components/guide/GuideSearch.tsx
> +                    {searchResult.map(({ page, preview }) => (
missing types

2021-10-26 11:53 UTC, tomasklim commented on packages/suite/src/components/guide/GuideSearch.tsx
> +                <PageFoundList>
Is there a design? Maybe there is too little spacing between Input and results?
![Screenshot 2021-10-26 at 12 37 04](https://user-images.githubusercontent.com/33235762/138872393-3a8c336b-16fa-4fad-acb4-f243f2834a52.png)

2021-10-26 15:03 UTC, marekrjpolak commented on packages/suite/src/components/guide/GuideSearch.tsx
> +                <PageFoundList>
Sorry, I totally forgot, design is here: https://www.figma.com/file/pIibgxmxD0jrAa9UGJd9da/Neue-Desktop-1.5?node-id=7785%3A77266

2021-10-26 15:11 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +const MIN_QUERY_LENGTH = 3;
Do you mean `MIN_QUERY_LENGTH`? In my opinion yes, as there is no use in searching one or two character long strings in whole Guide.

2021-10-26 15:15 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +const max = (value: number, min: number) => (value < min ? min : value);
Too easy! Ok, at first it was 'clamp' function, then I simplified it, then renamed it and then forgot that there already is a function for that. 😅

2021-10-26 15:28 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +        .trim();
Something like `replace(/\[([^\[\]]*)\]\([^()]*\)/g, '$1')`? But there may be even more .md syntax to solve.

2021-10-26 15:32 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +                          .then(md => searchInFile(url, querySanitized, md)),
Why? My linter is happy with this as both promise and catch above return string value. Yours isn't?

2021-10-26 15:33 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideLoadPage.ts
> +            });
Over my dead body!

2021-10-26 20:04 UTC, marekrjpolak commented on packages/suite/src/views/guide/OpenGuideFromTooltip.tsx
> +import { useGuideOpenNode } from '@guide-hooks/useGuideOpenNode';
https://github.com/trezor/trezor-suite/pull/4426/commits/a8c88dd861508dd477a8cefeb0cf7ea7e2a4e53e

2021-10-26 20:05 UTC, marekrjpolak commented on packages/suite/src/components/guide/GuideNode.tsx
> +    className?: string;
https://github.com/trezor/trezor-suite/pull/4426/commits/ec5d67852014e62cd1def942f4e75f0fde609acd

2021-10-26 20:05 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +        .trim();
https://github.com/trezor/trezor-suite/pull/4426/commits/ec5d67852014e62cd1def942f4e75f0fde609acd

2021-10-26 20:05 UTC, marekrjpolak commented on packages/suite/src/components/guide/GuideSearch.tsx
> +    className,
https://github.com/trezor/trezor-suite/pull/4426/commits/ec5d67852014e62cd1def942f4e75f0fde609acd

2021-10-26 20:05 UTC, marekrjpolak commented on packages/suite/src/components/guide/GuideSearch.tsx
> +    className?: string;
https://github.com/trezor/trezor-suite/pull/4426/commits/ec5d67852014e62cd1def942f4e75f0fde609acd

2021-10-26 20:07 UTC, marekrjpolak commented on packages/suite/src/components/guide/GuideSearch.tsx
> +                    {searchResult.map(({ page, preview }) => (
Again, how is that possible? I have no problem here regarding types.

2021-10-27 10:17 UTC, matejkriz commented on packages/suite/src/hooks/guide/useGuideLoadPage.ts
> +            });
let's briefly discuss in person after next standup?

2021-10-27 10:28 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideLoadPage.ts
> +            });
Gladly. Just for the record, this is approximately what the equivalent code with async/await looks like:
```
const func = async () => {
    try {
        const res = await loadPageMarkdownFile(currentNode.id, language);
        setMarkdown(res);
    } catch (e) {
        try {
            const res = await loadPageMarkdownFile(currentNode.id);
            setMarkdown(res);
        } catch (e) {
            console.error(`Loading of ${currentNode.id} page failed: ${e}`);
            setHasError(true);
        }
    }
}
func();
```

2021-10-27 10:35 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +const MIN_QUERY_LENGTH = 3;
If you set it to 1, then it can work as an autocomplete. But okay, leave it like this.

2021-10-27 10:58 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +                          .then(md => searchInFile(url, querySanitized, md)),
My linter was not happy yesterday, but it looks like that he is happy now 😆

2021-10-27 11:02 UTC, tomasklim commented on packages/suite/src/components/guide/GuideSearch.tsx
> +                    {searchResult.map(({ page, preview }) => (
My linter was probably sick yesterday. It is okay now

2021-10-27 11:20 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +        .trim();
Still there. Everything else is okay I think. Only links are problem.
![Screenshot 2021-10-27 at 13 19 10](https://user-images.githubusercontent.com/33235762/139055907-022682cc-5aa9-460d-838b-fe6c1a9a5d37.png)

2021-10-27 11:25 UTC, tomasklim commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +        .trim();
Your regex is okay. I do not know why it does not work.
![Screenshot 2021-10-27 at 13 24 51](https://user-images.githubusercontent.com/33235762/139056659-e927ed7f-b6f3-4431-a438-22c3931a3a1c.png)

2021-10-27 11:27 UTC, marekrjpolak commented on packages/suite/src/hooks/guide/useGuideSearch.ts
> +        .trim();
Do you test it locally? Because build in sldev is probably outdated because of this fixup commit.

2021-10-27 11:57 UTC, tomasklim approved these changes
LGTM, squash please

2021-11-01 10:55 UTC, merged