fix(invity): coinmarket set full width for exchange form
trezor/trezor-suite pull request #4498
Opened 2021-11-12 15:29 UTC by LukasRada

@tomasklim reported this behavior when resizing width of browser:
![image](https://user-images.githubusercontent.com/7394177/141490787-9cc0c03b-9723-44c5-9b57-fe435581d1fa.png)

Solution is to set `width: 100%` to the `form`

2021-11-15 14:04 UTC, tomasklim requested changes

2021-11-15 14:04 UTC, tomasklim commented on packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/index.tsx
> +                <FullWidthForm onSubmit={handleSubmit(onSubmit)} style={{ width: '100%' }}>
```suggestion
                <FullWidthForm onSubmit={handleSubmit(onSubmit)}>
```

2021-11-15 14:09 UTC, tomasklim requested changes

2021-11-15 14:09 UTC, tomasklim commented on packages/suite/src/views/wallet/coinmarket/index.tsx
> +export const FullWidthForm = styled.div`
```suggestion
export const FullWidthForm = styled.form`
```

otherwise nothing happens on `Enter` key

2021-11-15 15:23 UTC, LukasRada commented
Done. (Haste makes waste🙄, sorry.)

2021-11-24 13:12 UTC, tomasklim approved these changes
🎈 Please squash and rebase to current develop to fix CI

2021-11-25 11:52 UTC, merged