[wip] feat: clear user data on app restart
trezor/trezor-suite pull request #4547
Opened 2021-11-23 20:47 UTC by mroz22

2021-12-15 13:22 UTC, mroz22 commented
@alex-jerechinsky I think we need some design input here.

2021-12-16 14:08 UTC, mroz22 commented
While we are blocked by product decision here I moved "wipe button" into debug settings.

2022-01-12 10:06 UTC, tomasklim requested changes
It works on Mac 💪

2022-01-12 10:06 UTC, tomasklim commented on packages/suite/src/views/settings/debug/index.tsx
> +                            description="Clicking this button restarts your application and wipes all your data including labels."
Maybe we should start translating texts in Debug settings?

2022-01-12 10:06 UTC, tomasklim commented on packages/suite/src/views/settings/debug/index.tsx
> +                                Wipe data!
```suggestion
                                Wipe data
```

2022-01-12 10:06 UTC, tomasklim commented on packages/suite/src/views/settings/debug/index.tsx
> +                {!isWeb() && (
Would be nice to have a confirmation modal. (I also miss this modal on `Reset app` button.)

It would be nice if this modal contains a location where the files are deleted, in case a user wants to check it.
For me, it is `/Users/tom/Library/Application Support/@trezor/suite-desktop`

2022-01-12 10:07 UTC, tomasklim commented on packages/suite/src/views/settings/debug/index.tsx
> +                            description="Clicking this button restarts your application and wipes all your data including labels."
local labels, it does not delete google/dropbox

2022-01-14 18:15 UTC, mroz22 commented on packages/suite/src/views/settings/debug/index.tsx
> +                {!isWeb() && (
Iam not doing modal now but I have added info about user foldrer in this commit c4ccc03fbccf4b2430dc84725cde983d16678353

2022-01-14 18:15 UTC, mroz22 commented on packages/suite/src/views/settings/debug/index.tsx
> +                            description="Clicking this button restarts your application and wipes all your data including labels."
c4ccc03fbccf4b2430dc84725cde983d16678353

2022-01-14 18:15 UTC, mroz22 commented on packages/suite/src/views/settings/debug/index.tsx
> +                                Wipe data!
c4ccc03fbccf4b2430dc84725cde983d16678353

2022-01-18 14:05 UTC, tomasklim approved these changes
squash and rebase please

2022-01-18 14:26 UTC, merged

2022-01-24 14:12 UTC, bosomt commented
**QA OK**

**Info:**
 - Suite version: desktop 22.1.0 (c56c2c0094ff74ad45e9afde46cc79637891c855)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular