Refactor/notifications
trezor/trezor-suite pull request #4589
Opened 2021-12-01 19:30 UTC by marekrjpolak

Bigger refactoring of notifications, mostly replacing HOCs with renderer components. Now should be easier to implement more complex notifications, read redux data from them etc.

2022-01-12 08:45 UTC, tomasklim requested changes

2022-01-12 08:45 UTC, tomasklim commented on packages/suite/src/components/suite/NotificationRenderer/index.tsx
> +    ) => simple('info', messageId, values);
Probably it would be better to put this outside the `NotificationRenderer` to avoid unnecessary initialisations

2022-01-12 08:45 UTC, tomasklim commented on packages/suite/src/components/suite/NotificationRenderer/renderers/UriSchemeRenderers.tsx
> +            onCancel={() => resetProtocol()}
nit:
```suggestion
            onCancel={resetProtocol}
```

2022-01-12 08:45 UTC, tomasklim commented on packages/suite/src/components/suite/NotificationRenderer/renderers/UriSchemeRenderers.tsx
> +            onCancel={() => resetProtocol()}
nit:
```suggestion
            onCancel={resetProtocol}
```

2022-01-14 13:18 UTC, marekrjpolak commented on packages/suite/src/components/suite/NotificationRenderer/renderers/UriSchemeRenderers.tsx
> +            onCancel={() => resetProtocol()}
https://github.com/trezor/trezor-suite/pull/4589/commits/711bd66e10bf89166ef7b7e0b1035daa79aa8d72

2022-01-14 13:18 UTC, marekrjpolak commented on packages/suite/src/components/suite/NotificationRenderer/renderers/UriSchemeRenderers.tsx
> +            onCancel={() => resetProtocol()}
https://github.com/trezor/trezor-suite/pull/4589/commits/711bd66e10bf89166ef7b7e0b1035daa79aa8d72

2022-01-14 13:21 UTC, marekrjpolak commented on packages/suite/src/components/suite/NotificationRenderer/index.tsx
> +    ) => simple('info', messageId, values);
It's a bit more repetitive without the closure, but https://github.com/trezor/trezor-suite/pull/4589/commits/6d04f6686750974a90cf8431a11f3f02d2761d39

2022-01-14 21:09 UTC, tomasklim approved these changes

2022-01-17 08:52 UTC, tomasklim commented
Please squash it @marekrjpolak

2022-01-17 10:00 UTC, merged