feat(invity): sell crypto alternative flow
trezor/trezor-suite pull request #4980
Opened 2022-02-22 19:43 UTC by martinboehm

This PR add a new provider (Banxa) for the sell crypto functionality. The new provider uses one different step in the sell process - the user is redirected to the Banxa's checkout site to do part of the flow and then is redirected back to the Suite to complete it.

This PR contains two additional minor changes not directly related to the changes of the sell process:
1) buy and sell crypto for Suite Desktop: changed the way how the return from the partner's checkout site to Suite is handled - instead of reloading the Suite to the right place (which is slow and requires to reenter the pin/passphrase), we leave the Suite in the right place when redirecting to the partner and set focus to the Suite app on return from the partner. It assumes that the user in the meantime has not navigated somewhere else, which is a reasonable assumption as the user is redirected to the partner's checkout site. Even in the case the user did navigate out, nothing serious happens. Buy trade is completed at this moment and there is nothing to resume, the sell trade would have to be resumed manually from the trade history or created again without any financial loss.
2) when changing in the debug settings Invity API server, the Suite is automatically reloaded - the functionality without the reload was not always correct as Suite had cached some previous request from now deselected API server.

2022-02-25 12:22 UTC, tomasklim requested changes
+ irrelevant css issues

![Screenshot 2022-02-25 at 13 21 45](https://user-images.githubusercontent.com/33235762/155714482-2a52a874-0a9b-45ac-ac14-64cb3c2432b6.png)

2022-02-25 12:22 UTC, tomasklim commented on packages/suite-desktop/src-electron/modules/http-receiver.ts
> +            // It is enough to set focus to the Suite, the Suite should be on a page with info about the trade status,
Just an idea...
<img width="1227" alt="Screenshot 2022-02-25 at 11 59 51" src="https://user-images.githubusercontent.com/33235762/155704189-65b23888-46d7-40fa-aa68-0b17d593ac88.png">

We can warn the user that he has a transaction in progress and recommend him not to leave this page?

2022-02-25 12:22 UTC, tomasklim commented on packages/suite/src/views/settings/debug/InvityApi.tsx
> +                        if (typeof window !== 'undefined') {
What is the benefit of this check? `window` object should be always available in browser/electron renderer process

2022-02-25 12:22 UTC, tomasklim commented on packages/suite/src/utils/wallet/coinmarket/sellUtils.ts
> +    if (orderId) {
Cannot suggest change.

Would be more clear if you move this condition before `if (request.amountInCrypto) {` and change this `if (request.amountInCrypto) {` condition to `else if`

2022-02-25 12:22 UTC, tomasklim commented on packages/suite/src/hooks/wallet/useCoinmarketSellOffers.ts
> +import { TradeSell } from '@suite/types/wallet/coinmarketCommonTypes';
nit
```suggestion
import type { TradeSell } from '@suite/types/wallet/coinmarketCommonTypes';
```

2022-02-25 12:22 UTC, tomasklim commented on packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/SelectedOffer/components/SendTransaction/index.tsx
> +                            values={{ provider: providerName }}
nit: 

use `providerName` in translation string

2022-02-25 12:42 UTC, martinboehm commented on packages/suite/src/utils/wallet/coinmarket/sellUtils.ts
> +    if (orderId) {
It adds order id to the URL if `orderId` exists regardless of the value of `request.amountInCrypto`

2022-02-25 12:44 UTC, martinboehm commented on packages/suite-desktop/src-electron/modules/http-receiver.ts
> +            // It is enough to set focus to the Suite, the Suite should be on a page with info about the trade status,
Thank you, I will pass you suggestions to our product team. However we will not be resolving then in this PR.

2022-02-25 12:45 UTC, tomasklim commented on packages/suite/src/utils/wallet/coinmarket/sellUtils.ts
> +    if (orderId) {
```
if (orderId) {
    hash = `p-${hash}/${orderId}`;
} else if (request.amountInCrypto) {
    hash = `qc/${request.country}/${request.fiatCurrency}/${request.cryptoStringAmount}/${request.cryptoCurrency}`;
} else {
    hash = `qf/${request.country}/${request.fiatCurrency}/${request.fiatStringAmount}/${request.cryptoCurrency}`;
}
```

2022-02-25 12:51 UTC, martinboehm commented on packages/suite/src/views/settings/debug/InvityApi.tsx
> +                        if (typeof window !== 'undefined') {
You are using it in other places (for example packages/suite/src/storage/index.ts), just following your practice.

2022-02-25 12:58 UTC, martinboehm commented on packages/suite/src/utils/wallet/coinmarket/sellUtils.ts
> +    if (orderId) {
Your proposed change does not produce the same result our code.

2022-02-25 14:54 UTC, martinboehm commented on packages/suite/src/hooks/wallet/useCoinmarketSellOffers.ts
> +import { TradeSell } from '@suite/types/wallet/coinmarketCommonTypes';
Done.

2022-02-25 14:54 UTC, martinboehm commented on packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/SelectedOffer/components/SendTransaction/index.tsx
> +                            values={{ provider: providerName }}
Done.

2022-02-28 07:39 UTC, tomasklim commented on packages/suite/src/views/settings/debug/InvityApi.tsx
> +                        if (typeof window !== 'undefined') {
Ah, okay. Probably it is there because of compatibility with mobile app. Resolving

2022-02-28 07:39 UTC, tomasklim commented on packages/suite/src/utils/wallet/coinmarket/sellUtils.ts
> +    if (orderId) {
I am blind, sorry 🙈 Resolving

2022-02-28 07:40 UTC, tomasklim approved these changes
👍🏿 Please squash it

2022-02-28 09:00 UTC, martinboehm commented
Squashed, thank you!

2022-02-28 10:09 UTC, merged

2022-03-04 18:14 UTC, bosomt commented
@martinboehm can we move it from needs QA or is there anything that needs to be tested on our side ?