Update libs
trezor/trezor-suite pull request #5057
Opened 2022-03-07 07:38 UTC by mroz22

casual libs update. only minor and patch versions.

2022-03-07 14:59 UTC, tomasklim requested changes

2022-03-07 14:59 UTC, tomasklim commented on docker/test-runner/Dockerfile
> +FROM ${CI_DOCKER_PROXY}cypress/included:1
`9.5.1`?

2022-03-07 17:04 UTC, mroz22 commented on docker/test-runner/Dockerfile
> +FROM ${CI_DOCKER_PROXY}cypress/included:1
huh

2022-03-08 08:51 UTC, mroz22 commented on docker/test-runner/Dockerfile
> +FROM ${CI_DOCKER_PROXY}cypress/included:1
fixed

2022-03-08 09:21 UTC, tomasklim approved these changes

2022-03-08 12:00 UTC, merged