chore(ci): check branch name for '@'
trezor/trezor-suite pull request #5163
Opened 2022-03-21 16:42 UTC by mroz22

2022-03-21 16:55 UTC, prusnak commented on ci/environment.yml
> +    - ci/scripts/check_branch_name.sh
Shouldn't we pass `"$CI_COMMIT_BRANCH"` as first argument to the script here?

2022-03-21 16:55 UTC, prusnak commented on ci/scripts/check_branch_name.sh
> +name=$(git rev-parse --abbrev-ref HEAD)
We don't need to do this if we pass `"$CI_COMMIT_BRANCH"` as argument.

2022-03-21 16:55 UTC, prusnak commented on ci/scripts/check_branch_name.sh
> +echo $name
We can drop these 5 lines, no?

2022-03-21 20:53 UTC, prusnak requested changes, later dismissed

2022-03-21 20:53 UTC, prusnak commented on ci/environment.yml
> +    - ci/scripts/check_branch_name.sh ${CI_COMMIT_BRANCH}"
Typo:
```suggestion
    - ci/scripts/check_branch_name.sh ${CI_COMMIT_BRANCH}
```

2022-03-21 20:53 UTC, prusnak commented on ci/scripts/check_branch_name.sh
> +if [[ "$1" == *"@"* || "$name" == *"#"* ]]; then
```suggestion
if [[ "$1" == *"@"* || "$1" == *"#"* ]]; then
```

2022-03-21 20:53 UTC, prusnak commented on ci/scripts/check_branch_name.sh
> +echo $1
```suggestion
echo "$1"
```

2022-03-22 09:08 UTC, matejkriz approved these changes
let's squash and merge

2022-03-22 11:23 UTC, vdovhanych reviewed
Looks ok but wouldn't it be better to have it in git hooks also?

2022-03-22 13:24 UTC, mroz22 commented
> Looks ok but wouldn't it be better to have it in git hooks also?

I think we are only bother by these symbols in gitlab jobs (deploys, tests), it shouldn't be breaking anything in github jobs.

2022-03-22 14:44 UTC, matejkriz commented
> > Looks ok but wouldn't it be better to have it in git hooks also?
> 
> I think we are only bother by these symbols in gitlab jobs (deploys, tests), it shouldn't be breaking anything in github jobs.

I think @vdovhanych meant git commit hook (precommit/prepush) and it could make sense but I believe this gitlab check is really sufficient for us especially because the fix is very easy (just renaming the branch). So the whole point is to get some reasonable message what is wrong and why pipelines are failing...

2022-03-22 15:06 UTC, vdovhanych approved these changes

2022-03-22 20:54 UTC, merged