fix: show guide in the firmware modal, refactor modal header
trezor/trezor-suite pull request #5265
Opened 2022-04-13 17:02 UTC by dahaca

fix the second bug https://github.com/trezor/trezor-suite/issues/4739#issuecomment-1095153000

2022-04-14 07:34 UTC, tomasklim requested changes
<img width="718" alt="Screenshot 2022-04-14 at 9 34 08" src="https://user-images.githubusercontent.com/33235762/163336702-c16587d9-7620-40dc-9635-7f2ad2c19082.png">

2022-04-16 15:07 UTC, Nodonisko commented on packages/suite/src/views/firmware/index.tsx
> +const Wrapper = styled.div<{ withTopPadding: boolean }>`
I would prefer `hasTopPadding` or `isWithTopPadding`

2022-04-18 21:53 UTC, dahaca commented on packages/suite/src/views/firmware/index.tsx
> +const Wrapper = styled.div<{ withTopPadding: boolean }>`
done

2022-04-20 14:36 UTC, tomasklim approved these changes

2022-04-20 15:54 UTC, merged

2022-04-21 12:06 UTC, STew790 commented
**QA OK**

Guide is shown in the firmware modal.

![image](https://user-images.githubusercontent.com/48477147/164454646-db3e84c3-41b3-4461-aac4-59c5fa8b1134.png)

**Info:**
 - Suite version: web 22.5.0 (bf0e4020dc1344c179501fcb5f57d9c4039c8bf0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: bridge 2.0.31