Feat/guide images
trezor/trezor-suite pull request #5270
Opened 2022-04-19 13:27 UTC by tomasklim

closes #5206, #4414

2022-04-21 14:43 UTC, karliatto requested changes
Looks good to me and it works as expected in browser as electron app.

2022-04-21 14:43 UTC, karliatto commented on packages/utils/src/resolveStaticPath.ts
> +    `${process.env.ASSET_PREFIX || ''}/static/${path.replace(/^\/+/, '')}`;
I do not think it is a good idea to use a process env variable in utils package, why not adding it as function argument?

The idea of utils package is that is "independent" of the context where it is run, so I rather would suggest a more pure function approach.

2022-04-22 09:37 UTC, tomasklim commented on packages/utils/src/resolveStaticPath.ts
> +    `${process.env.ASSET_PREFIX || ''}/static/${path.replace(/^\/+/, '')}`;
58ba96db11b38d38d821ac54060a9b1f0646ed8f

I agree. However, `resolveStaticPath` is used on 50 places around the monorepo, so I would add `process.env.ASSET_PREFIX` as a fallback for the prefix param.

2022-04-22 09:38 UTC, tomasklim commented on packages/utils/src/resolveStaticPath.ts
> +    `${process.env.ASSET_PREFIX || ''}/static/${path.replace(/^\/+/, '')}`;
58ba96db11b38d38d821ac54060a9b1f0646ed8f I renamed it to `pathPrefix`

2022-04-22 10:00 UTC, karliatto approved these changes
:+1:

2022-04-25 06:47 UTC, merged