Fix/modal guide followup
trezor/trezor-suite pull request #5366
Opened 2022-05-10 11:45 UTC by marekrjpolak

Fixes regarding #5313:

https://github.com/trezor/trezor-suite/commit/2af8f5d6e548123b866c5ee46f9150cccbbd778a - guide panel width and scrollbars fix (please check it on Mac, @tomasklim)
https://github.com/trezor/trezor-suite/commit/e5b44294ccb771171ecf9565284a622cbe675522 - guide article fade-in removed as it caused ugly flashing when opening/closing modal next to opened guide and wasn't working as intended anyway (when the articles loaded slowly, the animation had usually ended before the text appeared)
https://github.com/trezor/trezor-suite/commit/ee7abfd4baf813904dc979eee9c5a26ea93bbe0b - click detection for anchor removal moved one level up (as it was before the previous PR)
https://github.com/trezor/trezor-suite/commit/ec4a2b1d1e40a453c5ee797952a103ba398bdfd8 - guide button and guide panel are now wrapped in `FreeFocusInside` which should hopefully resolve the refocus-to-the-first-modal-input-when-guide-is-opening issue (cc: @dahaca)

2022-05-11 08:44 UTC, tomasklim requested changes, later dismissed
<img width="991" alt="Screenshot 2022-05-11 at 10 44 21" src="https://user-images.githubusercontent.com/33235762/167808590-28076b19-08cf-4df0-a9e0-173d17f8c971.png">
I am getting this error when I open `Support & Feedback` tab in Guide

2022-05-11 11:37 UTC, marekrjpolak commented
> I am getting this error when I open `Support & Feedback` tab in Guide

Should be fix'n'squashed.

2022-05-13 12:18 UTC, dahaca approved these changes

2022-05-13 12:18 UTC, dahaca commented on packages/suite/src/components/guide/GuidePanel.tsx
> +    overflow-x: hidden;
A TIP: you can use the [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#-webkit-scrollbar) selector to remove annoying scrollbars (not in Firefox)

2022-05-13 12:19 UTC, dahaca approved these changes

2022-05-13 12:38 UTC, merged