feat: Implement custom switch button
trezor/trezor-suite pull request #5471
Opened 2022-05-24 10:32 UTC by juriczech

2022-05-24 14:20 UTC, Nodonisko requested changes

2022-05-24 14:20 UTC, Nodonisko commented on packages/atoms/src/Switch.tsx
> +const SWITCH_CIRCLE_SIZE = 20;
empty line after pls

2022-05-24 14:20 UTC, Nodonisko commented on packages/atoms/src/Switch.tsx
> +        <Pressable onPress={handlePress} style={applyStyle(wrapperStyle, { isChecked })}>
TouchableOpacity or Highlight please

2022-05-25 08:17 UTC, juriczech commented on packages/atoms/src/Switch.tsx
> +const SWITCH_CIRCLE_SIZE = 20;
[d2ab08d](https://github.com/trezor/trezor-suite/pull/5471/commits/d2ab08dc48c5b8e22186429b3116b2b858480ce9)

2022-05-25 08:17 UTC, juriczech commented on packages/atoms/src/Switch.tsx
> +        <Pressable onPress={handlePress} style={applyStyle(wrapperStyle, { isChecked })}>
[d2ab08d](https://github.com/trezor/trezor-suite/pull/5471/commits/d2ab08dc48c5b8e22186429b3116b2b858480ce9)

2022-05-25 09:04 UTC, bouchja1 approved these changes

2022-05-25 10:02 UTC, Nodonisko approved these changes

2022-05-26 09:22 UTC, merged