feat(fastlane) build and publish RN app to beta testing
trezor/trezor-suite pull request #5622
Opened 2022-06-15 16:23 UTC by bouchja1

Implement fastlane for publishing apps to Google Play and App store using our CI.

closes https://github.com/trezor/trezor-suite/issues/5521

2022-06-21 21:12 UTC, Nodonisko requested changes

2022-06-21 21:12 UTC, Nodonisko commented on packages/suite-native/fastlane/README.md
> +fastlane documentation
we don't want to use nested READMEs, I would place it to global docs or create Distribution section in suite-native/README.md

2022-06-21 21:12 UTC, Nodonisko commented on packages/suite-native/ios/fastlane/Fastfile
> +IOS_APP_ID = 'org.reactjs.native.example.TrezorSuite'.freeze
probably should be changed?

2022-06-21 21:12 UTC, Nodonisko commented on packages/suite-native/android/app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
I am still not sure about this `google-services`. Can you do some research what will happen when installed on device without google play? Maybe it will work because I am not sure what is difference between google-play-services and just google-services.

2022-06-22 10:43 UTC, bouchja1 commented on packages/suite-native/fastlane/README.md
> +fastlane documentation
Moved to suite-native and custom section

2022-06-22 12:19 UTC, Nodonisko approved these changes

2022-06-22 16:21 UTC, bouchja1 commented on packages/suite-native/android/app/build.gradle
> +if (getGradle().getStartParameter().getTaskRequests().toString().contains("firebaseDevelop")){
@Nodonisko FYI This should ensure that the google service only goes into test builds.

2022-06-23 07:51 UTC, juriczech approved these changes

2022-06-23 09:01 UTC, merged