WIP: Test/database migration
trezor/trezor-suite pull request #5983
Opened 2022-08-12 06:34 UTC by ondracja

Adding a new test case verifying database migration.

2022-08-12 07:28 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +            cy.task('setupEmu', { mnemonic: 'all all all all all all all all all all all all' });
I'd pass `{passphrase_protection: true}` to simplify it a bit. Aspects of auto-turning passphrase on don't need to be tested here

2022-08-12 07:29 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +                    .should('eq', this.firstTxLabel);
+ add something that works with keys. for example show address on device. it should not trigger passphrase dialog

2022-08-12 07:31 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +    const testUrls = ['/release/22.7/web', '/develop/web'];
I'd keep `Cypress.env('TEST_URLS')` in place in the end. If you want to make local docker/non-docker way of running it more user friendly, we should address this separately.

2022-08-12 07:33 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +         * 1. in in the older version of the app navigate to settings/device and verify settings state
maybe change instead of verify?

2022-08-12 07:35 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +         * 9. click on the Send btn and verify that the form is not broken (visually?)
I think that some of the form values should be saved into db as well, so you can verify this also

2022-08-12 07:38 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +            cy.visit(baseUrl + testUrl, {
Please add comment like this:
// This test is not intended to run against local dev server. Yoy should change base url to sldev 
// For docker, go to `docker-compose.suite-test.yml` and set `CYPRESS_baseUrl=https://suite.corp.sldev.cz/suite-web/` env variable

2022-08-18 14:06 UTC, mroz22 commented
@ondracja inspiration for what to cover in https://github.com/trezor/trezor-suite/pull/6039 (db migration inbound)

2022-08-20 16:29 UTC, mroz22 requested changes

2022-08-20 16:29 UTC, mroz22 commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +const to = '/test/databaseMigration/web';
rm line 7 and uncomment line 6

2022-08-22 05:30 UTC, ondracja commented on packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
> +const to = '/test/databaseMigration/web';
fixed.

2022-08-22 07:38 UTC, mroz22 approved these changes
looks helpful, altough some of the comment lines in tests description are not implemented yet, for example 

```
* 9. click on the Send btn and verify that the form is not broken
* 10. verify that a dark theme is still applied
```

2022-08-22 07:53 UTC, merged