Feat/intercept requests
trezor/trezor-suite pull request #6015
Opened 2022-08-16 09:05 UTC by karliatto

Interceptor that wraps all the network connection methods from nodejs that allows to see all the requests that are generated from electron nodejs main process.

## Description

* c38ddf59b4d8a8d41aafd42615dca5d08ff25de5 - extends package request-manager with an interceptor that wraps all the network connect methods from nodejs and does not modify any thing, it only provides some information to the listener.
* 367f842ccfc3eff5fded67a27b4c83a4297249c6 -  new module `request-logger` that allows us to log most of the requests that are happening in the electron main process.

There are still requests like the one happening for auto-update that is not logged here.

## Related Issue
https://github.com/trezor/trezor-suite/issues/5527

2022-08-18 09:44 UTC, mroz22 reviewed
Just one observation

1. start app with tor
2. discovery etc,..
3. then go to settings, disable tor

logger prints
```
2022-08-18T09:41:40.775Z - DEBUG(request-logger): net.Socket.connect - undefined

```
while debugging it, I found out that `options` value in `packages/request-manager/src/interceptor.ts` line 12 is set to 33147. Do you have any idea why?

2022-08-18 09:52 UTC, mroz22 requested changes
I would just somehow handle this `undefined` thingy. Imho it does not make sense to have sense to have human readable logs with undefined? Otherwise I think it makes sense altogether, always good to have some extra logs

2022-08-22 07:05 UTC, karliatto commented
> while debugging it, I found out that `options` value in `packages/request-manager/src/interceptor.ts` line 12 is set to 33147. Do you have any idea why?

Yes, When Tor is enable it uses `net.Socket.prototype.connect` to create a socks5 connection and options is the port of Tor, that is what you see `33147`.

The type of `options` argument in `net.Socket.prototype.connect` changes depending on how it is used, when WebSocket and Http, it contains an array with an object that includes all the http headers and options (including agent).

2022-08-22 08:19 UTC, karliatto commented
> I would just somehow handle this `undefined` thingy. Imho it does not make sense to have sense to have human readable logs with undefined? Otherwise I think it makes sense altogether, always good to have some extra logs

Yes, I added 4a52960ded01b6ba02ddd948e363ab859e163a05 to log properly that situation where you could see `undefined` and solo added a check to the logger to avoid printing those 7ec9b2fff2baa95f392c9a2c15e2fe382bee563c

2022-08-22 12:08 UTC, mroz22 approved these changes
ok, please squash and merge :pray:

2022-08-22 13:35 UTC, merged