chore(mobile): simplify qr code scanner
trezor/trezor-suite pull request #6438
Opened 2022-10-01 12:46 UTC by Nodonisko

Not tested yet on real device.

2022-10-01 12:47 UTC, Nodonisko commented on suite-native/module-accounts-import/src/components/Camera.tsx
> +    onResult: (qrCodeValue: string) => void;
Since user can scan any kind of QR code I would rather not imply it always xpub

2022-10-05 08:45 UTC, juriczech approved these changes
Apart from Dan's comment its fine. One nitpick I would suggest is to add comment to this: 
Just comment why you pick the first item in array just so developer doesn't event have to think about it. But it's just a suggestion and maybe it's unnecessary.
`const barcode = barcodes?.[0]?.displayValue;`

2022-10-05 09:54 UTC, bouchja1 commented
FYI @Nodonisko, @juriczech It is not working on a real device... :( I just tried it.

2022-10-05 09:55 UTC, bouchja1 requested changes
It is not working on a real device. Please, fix it.

2022-12-02 12:37 UTC, closed without merging