feat(components): add TooltipButton
trezor/trezor-suite pull request #6490
Opened 2022-10-05 17:55 UTC by dahaca

## Description

Added a TooltipButton component for situations when a button needs to have a tooltip.

## Screenshots:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/45338719/194128510-b8738bd6-6dd5-46c1-b107-05a98a93b168.png">

2022-10-05 17:56 UTC, dahaca commented
Also to be used here @komret 


![image](https://user-images.githubusercontent.com/45338719/194128904-87b20c37-bdc3-4ce7-9d5a-35cc6971f9bc.png)

2022-10-06 12:20 UTC, komret requested changes
Good idea, there is a couple spots where I can use this.

2022-10-06 12:20 UTC, komret commented on packages/components/src/components/buttons/TooltipButton.tsx/index.stories.tsx
> +storiesOf('TooltipButton', module).add('TooltipButton', () => {
Storybook [docs](https://storybook.js.org/docs/react/api/csf) recommend using the Component Story Format over the `storiesOf` way. Also, Knobs have been deprecated in favour of [Controls](https://storybook.js.org/docs/react/essentials/controls). An example of the newer syntax is in `Range.stories.tsx`.

2022-10-06 12:20 UTC, komret commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +    padding: 9px 32px;
Just to be consistent in case top/bottom `padding` changes on `Button`:

```suggestion
    padding-left: 32px;
    padding-right: 32px;
```

2022-10-06 12:20 UTC, komret commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +        <Tooltip maxWidth={285} content={tooltipMessage} cursor="not-allowed">
Is it intentional for the `Tooltip` not to disappear on hover? It could have `interactive` prop set to `false` or it could be controlled via `TooltipButton` props. There is currently no way to pass props to the tooltip, but I guess that's fine until we need it.

2022-10-06 12:20 UTC, komret commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +        <Tooltip maxWidth={285} content={tooltipMessage} cursor="not-allowed">
I think `cursor="not-allowed"` should be set only when the `button` is `disabled`.

2022-10-06 12:20 UTC, komret commented on packages/components/src/components/buttons/TooltipButton.tsx/index.stories.tsx
> +    const isDisabled = boolean('Disabled', false);
The main use case seems to be showing the tooltip when the `button` is `disabled` so the default state could be `disabled` and the message shown conditionally - just to make the use case clearer.

2022-10-06 12:20 UTC, komret commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +    tooltipMessage,
What about naming it `tooltipContent`? To be consistent with the original `content` prop.

2022-10-06 13:29 UTC, dahaca commented on packages/components/src/components/buttons/TooltipButton.tsx/index.stories.tsx
> +    const isDisabled = boolean('Disabled', false);
I was not sure about that, maybe there will be cases when it's still clickable. 🤷‍♂️

2022-10-06 16:56 UTC, dahaca commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +    tooltipMessage,
af0ef391c5c409353f2c89a8ebd2cac54d6c4aa7

2022-10-06 16:56 UTC, dahaca commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +        <Tooltip maxWidth={285} content={tooltipMessage} cursor="not-allowed">
I was just testing it, should be removed completely.

af0ef391c5c409353f2c89a8ebd2cac54d6c4aa7

2022-10-06 16:56 UTC, dahaca commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +        <Tooltip maxWidth={285} content={tooltipMessage} cursor="not-allowed">
af0ef391c5c409353f2c89a8ebd2cac54d6c4aa7

2022-10-06 16:56 UTC, dahaca commented on packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
> +    padding: 9px 32px;
af0ef391c5c409353f2c89a8ebd2cac54d6c4aa7

2022-10-06 16:56 UTC, dahaca commented on packages/components/src/components/buttons/TooltipButton.tsx/index.stories.tsx
> +storiesOf('TooltipButton', module).add('TooltipButton', () => {
af0ef391c5c409353f2c89a8ebd2cac54d6c4aa7

2022-10-07 09:54 UTC, komret approved these changes

2022-10-07 14:44 UTC, merged