Fix/long token names
trezor/trezor-suite pull request #6562
Opened 2022-10-13 16:23 UTC by komret

Fixes bug reported on [Slack](https://satoshilabs.slack.com/archives/CKZHV2G13/p1665665529471299)

## Description

- fix long token name/symbol balance breaking layout
- add bottom margin to the container
- hide the hyphen after token symbol along with the name on narrow screens
- refactor

The affected users reported that they could not see the whole table after they have been sent a scam token with long name and symbol. They did not see a scroll bar. This can be caused by OS settings (on a Mac, "Show scroll bars" can be set to "When scrolling", which hides the scroll bar in this case and only allows navigation by keyboard. Plus most of the table was overflowing and hidden beyond max width anyway, even if they could use the scroll bar.

To avoid potential problems with scrolling, I applied `word-break: break-all` to the table. Now, everything should be visible (potentially on multiple lines) without scrolling.

## Screenshots (if appropriate):
Before (long token name and missing scrollbar):
![Screenshot 2022-10-13 at 18 03 58](https://user-images.githubusercontent.com/42465546/195650824-ac84d436-bd26-45ae-aaba-886cbca769e0.png)
Before (extra hyphen when token name is hidden and missing `margin-bottom`):
![Screenshot 2022-10-13 at 18 05 37](https://user-images.githubusercontent.com/42465546/195650840-4a1340fb-f412-48c2-b917-8358755b4b1a.png)

After (no hyphen):
![Screenshot 2022-10-13 at 17 51 55](https://user-images.githubusercontent.com/42465546/195650802-bf1625cd-8f48-4ccb-82df-a2137fdd0cbd.png)
After:
![Screenshot 2022-10-13 at 18 21 19](https://user-images.githubusercontent.com/42465546/195651814-fb401409-f4de-46f5-ab40-430f18352a97.png)

**QA:** This is the token causing the problem with scrolling: https://etherscan.io/token/0xc9da518db3abdb90a82c4d1838b7cf9b0c945e7e

2022-10-13 19:56 UTC, tomasklim requested changes
The gap between blocks is too small in comparison with `Overview` section. 

![Screenshot 2022-10-13 at 21 57 04](https://user-images.githubusercontent.com/33235762/195697010-77727f49-d70c-42b3-a3e3-dbab19b35e90.png)

I see this page in this state for first time and imho it does not make sense. I do not see reason to have the `No transactions... yet.` block here in tokens.

![Screenshot 2022-10-13 at 21 53 13](https://user-images.githubusercontent.com/33235762/195696255-1acd5094-df47-45ef-bad7-6bb9a4cbf881.png)

2022-10-13 20:01 UTC, tomasklim commented
Does it make sense to add this to this release?

2022-10-14 08:31 UTC, sime commented
This behaviour is wrong and already documented here: https://github.com/trezor/trezor-suite/issues/6346#issue-1380493615

If it's a trivial fix, I vote for its removal. cc: @bosomt

2022-10-14 10:32 UTC, komret commented
@tomasklim I removed the "No transactions" card from the "Tokens" tab. 215d600e7d28d35570afd11d756a5da7bb3e0c71

2022-10-16 19:04 UTC, tomasklim approved these changes
Looks good.

Found this, but it is not part of this issue. It is already in staging, but not on production.
![Screenshot 2022-10-16 at 21 02 41](https://user-images.githubusercontent.com/33235762/196053251-af0822e9-b0b1-493d-a826-929198a42781.png)

2022-10-17 09:55 UTC, sime commented
> Found this, but it is not part of this issue. It is already in staging, but not on production.

What is this coming from?

2022-10-17 09:59 UTC, bosomt commented
@sime @tomasklim easy to reproduce , see my issue ;) https://github.com/trezor/trezor-suite/issues/4465

2022-10-17 11:14 UTC, merged

2022-10-17 18:42 UTC, tomasklim commented
@bosomt I meant the `Account does not exist` bubble in the middle of the screen and not at the top

2022-11-01 13:15 UTC, STew790 commented
**QA OK**

Token is showing correctly now.

![image](https://user-images.githubusercontent.com/48477147/199241588-8dc4ae38-7c52-470f-8811-620145e58d22.png)

**Info:**
 - Suite version: web 22.11.0 (20159af6c91247d769232aa257ec10cd741d1426)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32