feat(suite): Empty Coinjoin account screen
trezor/trezor-suite pull request #6602
Opened 2022-10-19 14:49 UTC by dahaca

## Description

Added empty coinjoin account screen

## Related Issue

Resolve [#6217](https://github.com/trezor/trezor-suite/issues/6217)

## Screenshots

<img width="500" alt="image" src="https://user-images.githubusercontent.com/45338719/196698767-ffd3a6d4-e996-4ece-8a1a-b23c2cfdc74b.png">

2022-10-20 09:18 UTC, komret requested changes

2022-10-20 09:18 UTC, komret commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +                    id="TR_RECEIVE_NETWORK"
The design has "Receive funds". This change is reasonable, but has it been discussed?

2022-10-20 09:18 UTC, komret commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +            <AccountDescriotion>
typo

2022-10-20 09:18 UTC, komret commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +            <Image image="COINJOIN_MESS" width={300} />
Not a fan of how the image looks in dark theme. Can we have a reversed variant of it (with dark background)?

2022-10-20 09:19 UTC, dahaca commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +                    id="TR_RECEIVE_NETWORK"
I decided to use the same wording as in all other accounts :)

2022-10-20 09:21 UTC, dahaca commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +            <Image image="COINJOIN_MESS" width={300} />
I can probably use `invert()` filter ;D

2022-10-21 11:27 UTC, matejkriz commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +            <Image image="COINJOIN_MESS" width={300} />
I believe the image is not final 🚧

2022-10-24 12:37 UTC, dahaca commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +            <AccountDescriotion>
b9651841a401e448bd1c7d05f695c6b104bbf621

2022-10-24 12:37 UTC, dahaca commented on packages/suite/src/views/wallet/transactions/components/CoinjoinAccountEmpty.tsx
> +            <Image image="COINJOIN_MESS" width={300} />
Yes, confirmed by Ondra, already requested a better one.

2022-10-24 12:38 UTC, komret approved these changes

2022-10-25 12:42 UTC, merged