chore(connect): disable experimental_features in atuhorizeCoinjoin
trezor/trezor-suite pull request #6736
Opened 2022-11-01 12:32 UTC by szymonlesisz

`experimental_fetaures` are no longer required by TrezorConnect.authorizeConjoin

2022-11-01 12:38 UTC, mroz22 approved these changes

2022-11-01 17:37 UTC, mroz22 commented
with latest available master in trezor-user-env ([6e36f479db50ddb1452bcf06a67961a802f340d6](https://github.com/trezor/trezor-firmware/commits/6e36f479db50ddb1452bcf06a67961a802f340d6)) it returns 

```
{
        id: 2,
        success: false,
        payload: {
            error: 'Failed to decode message: Experimental features are disabled.',
            code: 'Failure_DataError',
        },
    };
```

2022-11-02 08:16 UTC, mroz22 requested changes
wait until really supported

2022-11-02 16:15 UTC, szymonlesisz commented
just tested on revision: '3d645d609a3f20bd88b8c44e969b9e4489c496d0' (current 2-master) and it passes.

idk how long will it take to propagate to user-env

2022-11-02 18:11 UTC, mroz22 commented
should be there tomorrow

2022-11-02 18:11 UTC, mroz22 approved these changes

2022-11-02 18:11 UTC, merged

2022-11-05 06:23 UTC, bosomt commented
I still see EXPERIMENTAL MODE on TT display /even before i enable debug mode and add CJ account/ with latest version of 22.11.1 that we received yesterday evening. I hope this PR will remove this warning.

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32