feat(suite): update the empty coinjoin account screen
trezor/trezor-suite pull request #7410
Opened 2023-01-18 11:31 UTC by dahaca

## Description

* Update the empty coinjoin account screen

## Related Issue

Resolve [#7012](https://github.com/trezor/trezor-suite/issues/7012)

## Screenshots:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/45338719/213157681-6a4a2796-bc5c-4891-8a68-8cc636c00e6a.png">

2023-01-18 16:41 UTC, dahaca commented
Handling of coinjoin settings would also be relevant for [#7168](https://github.com/trezor/trezor-suite/issues/7168)

2023-01-19 13:06 UTC, komret requested changes

2023-01-19 13:06 UTC, komret commented on packages/suite/src/components/wallet/CoinjoinExplanation.tsx
> +const Step = ({ number, image, title, description }: StepProps) => (
Could be a separate file.

2023-01-19 13:06 UTC, komret commented on packages/suite/src/middlewares/wallet/storageMiddleware.ts
> +                    const isWalletRemembered = api.getState().suite.device?.remember;
~~This is checked even for cases it is not relevant to. I think it would be cleaner to have special handling for "SHOW_COINJOIN_EXPLANATION".~~
Aren't the settings wiped any time the coinjoin account is forgotten? If so, it can be safely saved here. Not only is that logic simpler, but it allows the user to 1) hide explanation, then 2) remember the wallet => the setting will be remembered.

2023-01-19 13:55 UTC, dahaca commented on packages/suite/src/components/wallet/CoinjoinExplanation.tsx
> +const Step = ({ number, image, title, description }: StepProps) => (
3c42aab28

2023-01-19 13:55 UTC, dahaca commented on packages/suite/src/middlewares/wallet/storageMiddleware.ts
> +                    const isWalletRemembered = api.getState().suite.device?.remember;
3c42aab28

2023-01-19 14:02 UTC, komret commented
/rebase

2023-01-19 14:10 UTC, komret approved these changes

2023-01-19 14:32 UTC, merged