fix(suite): coinjoin setup skip rounds
trezor/trezor-suite pull request #7423
Opened 2023-01-20 10:52 UTC by szymonlesisz

## Description

`customSkipRounds` is set to true by default but should set to true **only** when entering "custom" setup and set to false when leaving "custom" setup

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7421

2023-01-20 11:26 UTC, komret requested changes
@szymon, please use the alternative variant without `useEffect`, it is simpler and it is what I had in mind when writing it, but failed to deliver.

2023-01-20 17:03 UTC, dahaca commented
@komret f495887ad

2023-01-20 17:20 UTC, komret commented
/rebase

2023-01-25 10:58 UTC, komret approved these changes

2023-01-25 10:58 UTC, merged