feat(suite-native): copy clipboard hook
trezor/trezor-suite pull request #7462
Opened 2023-01-26 12:31 UTC by PeKne

The `useClipboard` hook added. 

This hook returns three values:
`isCopied` - boolean indicating if value was already copied or not. 
`copiedValue` - string value saved in clipboard.
`onCopy` - callback function which executes copy functionality.

On successful copy is user notified by toast message.

closes #7331

### DEMO
https://user-images.githubusercontent.com/26143964/214835854-1a828c22-0e39-4f22-9ca9-1241ce5da7e1.mov

2023-01-26 13:00 UTC, Nodonisko requested changes

2023-01-26 13:00 UTC, Nodonisko commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +    const onCopy = async (value: string, toastMessage?: string) => {
I would name this `copyToCliboard` idk why but onCopy sounds strange

Also please always use `useCallback` in these general use hook that could be used anywhere.

2023-01-26 13:00 UTC, Nodonisko commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +    const [copiedValue, setCopiedValue] = useState('');
Do we need this? Seems kind of useless. Value that you are copying is always avaiable in place where you used `onCopy` anyway.

2023-01-26 13:00 UTC, Nodonisko commented on suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx
> -    const handleClickCopy = () => Clipboard.setStringAsync(transaction.txid);
Please keep it here, it easier to wrap it in useCallback later if it will necessary for example.

2023-01-26 13:00 UTC, Nodonisko commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +export function useClipboard() {
This hook has very strange API. Let's imagine this use case. I have screen where I want to copy more than one value, how would I do that? I can use `onCopy` multiple times, but then `isCopied` and `copiedValue` will lie to me.

I would suggest two possible solution to this:
1. Don't use `isCopied` and `copiedValue` and just have `copyToClipboard` function
2. Make this more like `useState` so if you will have more than values to copy you will have to use hook multiple times and usage will look like this:

```tsx
const [isAdressCopied, copyAddressToClipboard] = useCopyToCliboard(address, { message: "whatever"});
const [isNameCopied, copyNameToClipboard] = useCopyToCliboard(name);

// later
<Button onPress={copyAddressToClipboard} />
<Botton onPress={copyNameToClipboard />
```

2023-01-26 13:00 UTC, Nodonisko commented on suite-native/qr-code/src/components/QRCode.tsx
> +    onClose: () => void;
This component should has no idea that something will close after click on copy and I think there will be usages where it should only copy and not close. I would keep previous name.

2023-01-26 13:10 UTC, Nodonisko commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +        Toast.show(toastMessage ?? 'Value copied.');
`'Copied to clipboard.'`

2023-01-26 13:35 UTC, PeKne commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +    const onCopy = async (value: string, toastMessage?: string) => {
fixed in 2b0833c07

2023-01-26 13:36 UTC, PeKne commented on suite-native/qr-code/src/components/QRCode.tsx
> +    onClose: () => void;
fixed in 2b0833c07

2023-01-26 13:36 UTC, PeKne commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +        Toast.show(toastMessage ?? 'Value copied.');
fixed 2b0833c07

2023-01-26 13:37 UTC, PeKne commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +export function useClipboard() {
Removed `isCopied` and `copiedValue` in 2b0833c07.

2023-01-26 13:39 UTC, PeKne commented on suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx
> -    const handleClickCopy = () => Clipboard.setStringAsync(transaction.txid);
Fixed in 2b0833c07.

Does it mean that using arrow functions directly in JSX is considered forbidden in this project? Should I always define `handleFunction`? Or are trivial calls like `onClick={()=> setState(<SOMETHING>)` ok?

2023-01-26 13:39 UTC, PeKne commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +    const [copiedValue, setCopiedValue] = useState('');
2b0833c07

2023-01-26 16:02 UTC, Nodonisko requested changes

2023-01-26 16:02 UTC, Nodonisko commented on suite-native/qr-code/src/components/QRCode.tsx
> +        // await Clipboard.setStringAsync(data);
Remove comment

2023-01-26 16:02 UTC, Nodonisko commented on suite-native/qr-code/src/components/QRCode.tsx
> +        await copyToClipboard(data, 'Address copied.');
nit: `Address copied to clipboard`

2023-01-26 16:02 UTC, Nodonisko commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +export function useClipboard() {
Please rename this to `useCopyToClipboard` since it's now only thing that it is doing

2023-01-27 07:14 UTC, PeKne commented on suite-native/qr-code/src/components/QRCode.tsx
> +        // await Clipboard.setStringAsync(data);
fixed 42c5f4c75

2023-01-27 07:14 UTC, PeKne commented on suite-native/qr-code/src/components/QRCode.tsx
> +        await copyToClipboard(data, 'Address copied.');
fixed 42c5f4c75

2023-01-27 07:14 UTC, PeKne commented on suite-native/helpers/src/hooks/useClipboard.tsx
> +export function useClipboard() {
fixed 42c5f4c75

2023-01-27 11:36 UTC, Nodonisko commented on suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx
> -    const handleClickCopy = () => Clipboard.setStringAsync(transaction.txid);
It's not enforced but it's preferred most of times, at least do not delete it if it's already here. No strong rule about this one.

2023-01-27 11:37 UTC, Nodonisko approved these changes

2023-01-27 12:58 UTC, PeKne commented
/rebase

2023-01-27 13:44 UTC, merged