chore: redux update
trezor/trezor-suite pull request #7634
Opened 2023-02-14 19:13 UTC by dahaca

## Description

* updated  `react-redux`, `redux`, `redux-thunk`, `immer` and `@reduxjs/toolkit` to latest versions
* properly typed `useDispatch`
* removed the `redux-thunk` patch 🔪 
* some random files changed because of `lint --fix`

## Related Issue 

Resolve https://github.com/trezor/trezor-suite/issues/4651

2023-02-15 08:11 UTC, tomasklim requested changes
Good job 🥳 

Please run `yarn dedupe`

I am getting those `type-check` errors 
```
    ✖  nx run @trezor/suite:type-check
       src/middlewares/suite/__tests__/buttonRequestMiddleware.test.ts(86,9): error TS2578: Unused '@ts-expect-error' directive.
       src/middlewares/suite/__tests__/buttonRequestMiddleware.test.ts(88,9): error TS2578: Unused '@ts-expect-error' directive.
```

2023-02-15 08:11 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDispatch.ts
> +import { useDispatch as useReduxDisparch } from 'react-redux';
```suggestion
import { useDispatch as useReduxDispatch } from 'react-redux';
```

2023-02-15 08:11 UTC, tomasklim commented on packages/suite/src/hooks/suite/useDispatch.ts
> +export const useDispatch: () => ThunkDispatch<AppState, any, Action> = useReduxDisparch;
```suggestion
export const useDispatch: () => ThunkDispatch<AppState, any, Action> = useReduxDispatch;
```

2023-02-15 09:06 UTC, matejkriz commented
@dahaca Have you checked this comment?
https://github.com/trezor/trezor-suite/pull/4711#issue-1098109503
> removed react-redux from suite-web package.json and pinned its version to 7.2.2. 7.2.3 contains a bug fix that is a breaking change for us - runtime looks fine BUT useDiscovery tests were relying on the old behavior and I am not 100% sure whether simply adjusting test fixtures is proper fix here.

2023-02-15 09:09 UTC, dahaca commented
> @dahaca Have you checked this comment?
> 
> https://github.com/trezor/trezor-suite/pull/4711#issue-1098109503

No I haven't :( But I noticed something is up with the tests, will look into it.

2023-02-15 13:29 UTC, dahaca commented on packages/suite/src/hooks/suite/useDispatch.ts
> +import { useDispatch as useReduxDisparch } from 'react-redux';
cd97cd0ec5fc50380d74d894c3853cd0bc5930f1

2023-02-15 13:29 UTC, dahaca commented on packages/suite/src/hooks/suite/useDispatch.ts
> +export const useDispatch: () => ThunkDispatch<AppState, any, Action> = useReduxDisparch;
cd97cd0ec5fc50380d74d894c3853cd0bc5930f1

2023-02-15 13:29 UTC, dahaca commented
@matejkriz @tomasklim test fixed e8cf055b2021e32810bf77f75047d10cecb38065

> Please run `yarn dedupe`

36a013f29005ceb60696c397e6c17302e86f352a

2023-02-16 20:31 UTC, tomasklim approved these changes
You're pro man. Awesome job 

![you-did-good-job-meme](https://user-images.githubusercontent.com/33235762/219480223-f7e997b9-fa2b-4393-b78c-0a89d2665dd9.jpg)

2023-02-18 14:07 UTC, Nodonisko commented
We merged some new packages in meantime, please rebase and fix version also in them. Thanks.

2023-02-21 20:18 UTC, merged