Z-index to DayHeader
trezor/trezor-suite pull request #7784
Opened 2023-03-06 18:02 UTC by komret

## Description
Bug was probably caused by applying `position: relative` to the icon wrapper.

## Screenshots:
before:
![Screenshot 2023-03-06 at 18 59 01](https://user-images.githubusercontent.com/42465546/223192681-17defaba-864a-49e1-be75-98467909aa96.png)
after:
![Screenshot 2023-03-06 at 18 58 12](https://user-images.githubusercontent.com/42465546/223192656-fe21e676-b804-4ed5-9078-f6fbb38fbdf1.png)

2023-03-07 12:44 UTC, tomasklim requested changes
![Screenshot 2023-03-07 at 13 44 23](https://user-images.githubusercontent.com/33235762/223425607-652c36da-b7dc-47c1-ac4b-e793eef3806e.png)

2023-03-07 13:46 UTC, komret commented
Fixed by d10fc5edb2e95e08d3fda1aaf84d51462b850dbb.

2023-03-08 10:52 UTC, tomasklim approved these changes

2023-03-08 10:54 UTC, komret commented
/rebase

2023-03-08 11:07 UTC, merged

2023-04-08 07:56 UTC, bosomt commented
**QA OK**


**Info:**
 - Suite version: desktop 23.4.1 (5044d02a986e634881bbc85393c2936dacdcb6ec)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32