chore(mobile): better dev xpubs
trezor/trezor-suite pull request #7831
Opened 2023-03-13 17:34 UTC by Nodonisko

Add some better xpubs for dev purposes.

## Description

## Related Issue

Resolve 

## Screenshots:

2023-03-13 17:42 UTC, PeKne requested changes

2023-03-13 17:42 UTC, PeKne commented on suite-native/module-accounts-import/src/components/DevXpub.tsx
> +    ada: 'addr1qxwy5p2kxd8xeclxxgx4lmhuae0knu762etrjgg8772gepp6sjecwjdttznf0hqxwc0suz8axtj3yjwzmnl99r9le56sc6hyez',
Have you tried the new key for ADA? I believe it is not a key, but a public address.

2023-03-13 20:23 UTC, juriczech approved these changes

2023-03-13 20:24 UTC, juriczech approved these changes

2023-03-13 20:24 UTC, juriczech commented on suite-native/graph/src/components/GraphDateFormatter.tsx
> +const millisecondsPerTwoWeek = 1209600000;
Should be SNAKE_CASE

2023-03-14 08:23 UTC, PeKne approved these changes

2023-03-14 08:23 UTC, merged