fix(coinjoin): allow coinjoin start with outdated FW
trezor/trezor-suite pull request #8124
Opened 2023-04-17 10:39 UTC by matejkriz

## Description

Currently if the FW version is not the latest available, coinjoin is blocked with tooltip message `Unavailable. Associated device is disconnected.` even though the FW supports coinjoin, it's just "outdated".

For now it will be resolved via message-system (coinjoin with FW 2.5.3) will be disabled. But this change still has to be merged for future FW releases.

## Related Issue

Resolve https://satoshilabs.slack.com/archives/C048XFAKL10/p1681717015830979

## Screenshots:
bug with FW 2.5.3 in Suite that has FW 2.6.0 available:
![image](https://user-images.githubusercontent.com/3729633/232460494-92af4432-2198-4cb3-b02d-e926b4fb72c7.png)

2023-04-17 11:35 UTC, komret requested changes
I think a different message should be provided in this case. Something like "You need to update firmware."

2023-04-17 15:21 UTC, matejkriz commented
> I think a different message should be provided in this case. Something like "You need to update firmware."

But this is a valid case and coinjoin is allowed even if you FW is outdated (if it supports coinjoin) - so there is no need for any extra message for that case.

2023-04-17 15:41 UTC, komret approved these changes
Got it...

2023-04-17 15:59 UTC, merged

2023-04-20 05:28 UTC, bosomt commented
Started latest develop version and it reports `Firmware update required to enable the coinjoin feature.`
Does it need to be enabled via message system too ?

<img width="349" alt="image" src="https://user-images.githubusercontent.com/31506317/233266517-0fa2d586-f7cd-43d8-880b-05c5cd194a25.png">

**Info:**
 - Suite version: desktop 23.5.0 (5285ae0d3488b207aeb85100815fd4d8e0d67707)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.33

2023-04-20 10:37 UTC, matejkriz commented
> Started latest develop version and it reports `Firmware update required to enable the coinjoin feature.` Does it need to be enabled via message system too ?

Sorry for confusing description, coinjoin is not supposed to be running with FW 2.5.3 anymore - 2.6.0 is required.

2023-04-20 10:42 UTC, matejkriz commented
Moved to Approved without QA, preparing special message system config for this is not worth the benefits of one more eyes checking it...