fix(suite-native): eth item layout without tokens
trezor/trezor-suite pull request #8238
Opened 2023-04-25 13:45 UTC by PeKne

## Description

- eth account list item has correct padding if does not  render tokens

## Screenshots:

https://user-images.githubusercontent.com/26143964/234296145-cbaa8caa-2f1b-4699-93ac-62a75804cee8.mov

2023-04-25 13:51 UTC, juriczech requested changes

2023-04-25 13:51 UTC, juriczech commented on suite-native/module-send-receive/src/screens/ReceiveAccountsScreen.tsx
> +            <AccountsList onSelectAccount={navigateToReceiveScreen} areTokensDisplayed={false} />
Why don't you use route to determine this instead of prop drilling?

2023-04-25 14:56 UTC, Nodonisko commented on suite-native/module-send-receive/src/screens/ReceiveAccountsScreen.tsx
> +            <AccountsList onSelectAccount={navigateToReceiveScreen} areTokensDisplayed={false} />
Why route? What if route changes? What if component is used in new screen?

2023-04-25 14:58 UTC, Nodonisko requested changes
I don't like route solution 😅

2023-04-25 14:59 UTC, juriczech commented on suite-native/module-send-receive/src/screens/ReceiveAccountsScreen.tsx
> +            <AccountsList onSelectAccount={navigateToReceiveScreen} areTokensDisplayed={false} />
Because the only place where it's not displayed is that route so it kind of makes sense.

2023-04-25 15:18 UTC, Nodonisko commented on suite-native/module-send-receive/src/screens/ReceiveAccountsScreen.tsx
> +            <AccountsList onSelectAccount={navigateToReceiveScreen} areTokensDisplayed={false} />
Never mess components and routes together, unless some very edge cases.

2023-04-26 08:50 UTC, PeKne commented
@Nodonisko Fixup reverted.

2023-04-26 15:46 UTC, PeKne commented
After discussion with the product, we don't want to hide ETH tokens in receive account list.

2023-04-26 15:46 UTC, closed without merging