fix(suite): upload same homescreen twice
trezor/trezor-suite pull request #8246
Opened 2023-04-26 09:11 UTC by tomasklim

## Description

- I am not sure why order matters here

## Related Issue

closes #5329

## Screenshots:

2023-04-26 14:17 UTC, komret approved these changes

2023-04-26 15:16 UTC, komret requested changes
This solves the problem of the ref value resetting when `applySettings` is called and thus fixes the bug, but the proper solution is to replace `createRef` with `useRef`. The `createRef` API should not be used in function components because it does not persist value between rerenders. Explanation: https://blog.bitsrc.io/react-useref-and-react-createref-the-difference-afedb9877d0f

2023-04-27 08:33 UTC, tomasklim commented
Fixed. We have 7 occurences of `createRef` in our codebase, so probably it would be great idea to get rid of it

2023-04-27 10:00 UTC, komret approved these changes

2023-04-28 16:27 UTC, merged