feat(suite-native): fee formatter
trezor/trezor-suite pull request #8418
Opened 2023-05-09 15:11 UTC by PeKne

## Description

- fee formatter component created

## Related Issue

Resolve #7385

2023-05-15 12:27 UTC, Nodonisko requested changes

2023-05-15 12:27 UTC, Nodonisko commented on suite-native/formatters/src/components/FeeFormatter.tsx
> +    const formattedValue =
We should `useMemo` this or whole component, these BigNumbers are quite slow on mobile.

2023-05-16 07:57 UTC, PeKne commented on suite-native/formatters/src/components/FeeFormatter.tsx
> +    const formattedValue =
`useMemo` applied in ff899c692.

2023-05-17 09:24 UTC, Nodonisko approved these changes

2023-05-17 10:42 UTC, merged