Electron bundling experiments
trezor/trezor-suite pull request #8842
Opened 2023-07-01 13:01 UTC by Nodonisko

## Pull Request Description

### Overview

This PR aims to address the recurring issue of unnecessary dependencies being included in the Electron app due to the deep nested dependency tree within our monorepo. The proposed solution is to adopt a similar approach for the Electron layer as we currently use for the UI layer of the app.

### Changes

The primary change is the creation of a new package, `@trezor/suite-desktop-core`, which is essentially a copy of the `src/` folder from `@trezor/suite-desktop` along with some necessary build scripts. The build output of this package is set to `dist/` in the existing `@trezor/suite-desktop`, and almost all dependencies from the `package.json` of the old `@trezor/suite-desktop` have been removed. The few remaining dependencies are native Electron ones that are not bundled, and these are defined as external dependencies in the build script `@trezor/suite-desktop-core/scripts/build` to prevent them from being bundled.

The `@trezor/suite-desktop` package now serves as a container for the generated/bundled code from the UI and Electron layers, and is responsible for creating the Electron app. No custom code should be added to this package, and no dependencies from the monorepo should be added to the `package.json` in `@trezor/suite-desktop`. Doing so would break this system.

### Benefits

1. App size reduction of ~6MB (measured against the latest production build .dmg file)
2. Elimination of the need to maintain an extensive files blacklist in `electron-builder-config.js`
3. Ability to use any package from the monorepo in `@trezor/suite-desktop-core` without needing to add `build:libs`
4. No need to worry about including unwanted dependencies in Electron's node_modules as the bundler will only include the code that is actually used
5. Additional layer to prevent protestware issues that we've encountered recently (styled-components, es5-ext)
6. Potential to eliminate most of the `build:libs` that were added solely for use in the Electron layer

### Drawbacks

1. Packages with binaries/node-gyp-build outputs that need to be included in the Electron app must be specifically defined. This was necessary for the `usb` package used in transport to start the app, and there may be other binaries that need to be added. If we need to add our own binaries, we should create a new package solely for binaries without any code that can be added to `@trezor/suite-desktop/package.json`.

### Next Steps

If we decide to proceed with this approach, further polishing of this PR and extensive testing will be required. I have not had the time to conduct in-depth testing, but I was able to reach the welcome screen without encountering any errors.

### Diagram

To better illustrate the changes, I will create a diagram using the Diagrams plugin. This will help to visualize the new structure and the relationship between the packages.

![Diagram](https://kroki.io/graphviz/svg/eNqFkEFLxDAQhe_9FUNP66GoZ6nIWvC0Vai3RSRNhm5ozIRJgqL0v5tti_TQrsfkffPmvVG6Y-FO8AQ_GbCwvdJcvu7vMrCkEI7-JByWLX29pS8f24mWJvqA_H5znjKiRVPmz0ZBEzjKEBnzREsyxGVrIqZHU8FxBh8C4zfxtY86YKHQ94FcfvZv1plRO_xpB7LE6AhehOxFh36araC4X1AVOrTKA9nZOqmLEPuoTVK1DTTqw0q720W7Gj_X2nWMaMftj5f7FTJlnoPWl1HYpWVXE7uBwq4RHzgzafXYrd4sl2z-IyaTzfMN2fALEpOzWg==)

2023-07-01 13:07 UTC, Nodonisko commented on packages/suite-desktop/package.json
>          "@sentry/electron": "^4.6.0",
could be probably removed too

2023-07-11 15:40 UTC, matejkriz commented
> P.S: This PR description was generated with big help of GPT4, let me know if you like it.

I like the description a lot! How exactly have you used GPT4 for it? Just for polishing language and wording or did you let it read something from the code changes?

2023-07-12 08:36 UTC, marekrjpolak commented
I report no problems with this branch on NixOS. cc: @matejkriz

2023-07-12 09:19 UTC, Nodonisko commented
@matejkriz I wrote some very brief description myself that looked horrible and let GPT4 rewrite it and add chart.

2023-07-12 11:29 UTC, tomasklim commented on packages/suite-desktop-core/package.json
> +        "electron-builder": "24.4.0",
windows desktop app will not work with this version right? @matejkriz

2023-07-12 11:38 UTC, tomasklim requested changes
just small things

2023-07-12 11:38 UTC, tomasklim commented on packages/suite-desktop-core/package.json
> +    "description": "Trezor Suite desktop application",
nit: Unnecessary description

2023-07-12 11:38 UTC, tomasklim commented on packages/suite-desktop-core/README.md
> +## Clearing Electron cache
old nit:
Should include some info about `suite-desktop`, `suite-desktop-dev` and `suite-desktop-local`

2023-07-12 11:38 UTC, tomasklim commented on packages/suite-desktop-core/package.json
> +        "electron-builder": "24.4.0",
windows desktop app will not work with this version right? @matejkriz so cannot be tested by qa

2023-07-12 12:00 UTC, matejkriz commented on packages/suite-desktop-core/package.json
> +        "electron-builder": "24.4.0",
No, electron-builder is not used in suite-desktop-core and should not be here as devDependency at all... In suite-desktop, there is correct version.

2023-07-24 12:36 UTC, matejkriz commented
QA task: https://www.notion.so/satoshilabs/Suite-Desktop-bundling-experiment-0c9a5632603443c98d6ff0ef6685d369?pvs=4

2023-07-25 09:47 UTC, matejkriz commented on packages/suite-desktop/package.json
>          "@sentry/electron": "^4.6.0",
yes, removed

2023-07-25 12:52 UTC, matejkriz commented on packages/suite-desktop-core/README.md
> +## Clearing Electron cache
460a69028227df7222f2b2ab4c99d5cad00b2945

2023-07-25 13:00 UTC, matejkriz commented
We had an issue with Tor toggling that has been solved by bundling also all native modules together 0ee21f47e285b3327c04d45b97afe86bf72c7bdd. There was no reason to keep them loaded dynamically and it causes some troubles probably because of multiple instances of those modules.

2023-07-25 14:05 UTC, matejkriz commented on packages/suite-desktop-core/package.json
> +        "electron-builder": "24.4.0",
ff11317e0f71e65f10f3622e5a2630a40028e188

2023-07-26 13:07 UTC, tomasklim requested changes
![Screenshot 2023-07-26 at 15 06 38](https://github.com/trezor/trezor-suite/assets/33235762/3c4d9244-f52d-4167-b8c2-fb1001bdb166)
Is it possible to include only required platform of `usb` in `app.asar.unpacked` in `node_modules`?

2023-07-26 13:48 UTC, matejkriz commented
> Is it possible to include only required platform of `usb` in `app.asar.unpacked` in `node_modules`?

I believe it is, but I spent more than hour trying that and found no nice solution. Worst case scenario, we can write some script that will delete other platforms, but the naming is not consistent across packages, check blake-hash...

Anyway, it's not a new issue, let's solve it separately.

2023-07-26 13:56 UTC, tomasklim approved these changes
LGTM

2023-07-26 14:05 UTC, matejkriz commented
/rebase

2023-07-27 15:36 UTC, merged

2023-07-27 15:39 UTC, matejkriz commented
@trezor/qa please test it again in develop, because there were some following changes in native modules, so would be nice to double check 
- that Tor is working properly now - also with little snitch, 
- that everything go through tor if it's enabled, 
- how it behaves when started with tor enabled and then disabled 
- how it behaves when started with tor disabled and then enabled 
🙏

2023-08-01 15:13 UTC, bosomt commented
**QA OK**

https://www.notion.so/satoshilabs/Suite-Desktop-bundling-experiment-volume-2-6b150084141542f3987d5dcd28dd02ec?pvs=4