Test/passphrase missmatch test
trezor/trezor-suite pull request #8851
Opened 2023-07-03 13:37 UTC by karliatto

## Description

Extend e2e tests for passphrase to address some of the situation mentioned https://github.com/trezor/trezor-suite/issues/8739  where 3rd party is reloaded and when it is not.

It also adds some helper function to make tests easier to write.

## Related Issue

Related https://github.com/trezor/trezor-suite/issues/8739

2023-07-04 13:30 UTC, mroz22 requested changes
also I pushed one fixup, I would like to have "passphrase mismatch" also covered, may I ask you to finish it please 🙏 
to learn more:
- https://docs.trezor.io/trezor-firmware/common/communication/passphrase.html
- https://docs.trezor.io/trezor-suite/packages/connect/methods/commonParams.html

2023-07-04 13:30 UTC, mroz22 commented on packages/connect-popup/e2e/support/helpers.ts
> +export const waitAndClickButtons = async (page: Page, buttons: string[]) => {
maybe `waitAndClick` or `waitAndClickElements` ? this makes one feel it need to be button elements

2023-07-04 15:39 UTC, karliatto commented on packages/connect-popup/e2e/support/helpers.ts
> +export const waitAndClickButtons = async (page: Page, buttons: string[]) => {
:+1:  Changed it to `waitAndClick`

2023-07-04 15:42 UTC, karliatto commented
> also I pushed one fixup, I would like to have "passphrase mismatch" also covered, may I ask you to finish it please pray to learn more:
> 
>     * https://docs.trezor.io/trezor-firmware/common/communication/passphrase.html
> 
>     * https://docs.trezor.io/trezor-suite/packages/connect/methods/commonParams.html

Thanks! I updated it to address the situations:
* getting error passphrase mismatch and accept the mismatched passphrase
* getting error passphrase mismatch and change it to the right one

2023-07-07 07:48 UTC, mroz22 approved these changes

2023-07-07 11:46 UTC, merged