chore (suite): bump supported browser versions
trezor/trezor-suite pull request #8980
Opened 2023-07-23 14:18 UTC by AdamSchinzel

Bumped supported browser version as per discussion on Slack

## Description

Supported versions are now `Chrome >= 92` and `Firefox >= 102`.

## Related Issue

Resolve #8832

2023-07-24 08:24 UTC, tomasklim requested changes
We should also update useragent in cypress tests. `e2e/tests/browser` 

maybe put somewhere a comment so that the next person, who updates browserslist / browser-detection, knowns about it

Have you considered adding `@babel/preset-env` or better plugin like https://www.npmjs.com/package/eslint-plugin-compat which will warn us, that we use unsupported features according to our browserslist

2023-07-24 08:28 UTC, AdamSchinzel commented
> We should also update useragent in cypress tests. `e2e/tests/browser`
> 
> maybe put somewhere a comment so that the next person, who updates browserslist / browser-detection, knowns about it
> 
> Have you considered adding `@babel/preset-env` or better plugin like https://www.npmjs.com/package/eslint-plugin-compat which will warn us, that we use unsupported features according to our browserslist

I will add there a comment. Good point 👍

Regarding the `@babel/preset-env` or plugin I think It should be resolved rather in this issue #8833

2023-07-24 10:02 UTC, tomasklim approved these changes

2023-07-25 07:08 UTC, tomasklim commented
/rebase

2023-07-25 07:23 UTC, merged