Add official and community label to languages
trezor/trezor-suite pull request #9030
Opened 2023-07-26 04:40 UTC by hrudolf

## Description

The languages appear under Settings - Application - Language. I've added labels (inline text) for the languages.

In languages.ts besides the optional "complete" key, I've added another optional key "official" and marked official languages as true, complete unofficial ones as false (could be optional) to be able to differentiate between languages.

These keys are used in Languages.tsx where the options are gathered instead of "onlyComplete", into "officialLanguage" and "communityLanguage". These are then passed into the options of the dropdown menu - first the official ones, then the community translations.
They also get a description in brackets "(Official language)" for official ones, "(Community translation)" for the others. These descriptions use localization / translationString. For these I've added two new values TR_LANGUAGE_OFFICIAL and TR_LANGUAGE_COMMUNITY.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7624

## Screenshots:

![image](https://github.com/trezor/trezor-suite/assets/79017980/dee6d25d-f215-44f9-949d-249a4f75fd3a)

2023-07-26 04:44 UTC, hrudolf commented
This is my first contribution to an open source project - besides doing the full Hungarian translation for Trezor Suite under the name Mario Goomba (changed my username on Crowdin since). I really want to ship the language to the Hungarian community, so I created a solution to this issue. Please let me know if it is acceptable or how else it could be completed. Cheers :) I've already made some adjustments since yesterday evening and this is a new PR.

2023-07-26 07:50 UTC, tomasklim requested changes

2023-07-26 07:50 UTC, tomasklim commented on packages/suite/src/config/suite/languages.ts
> +    cs: { name: 'Česky', en: 'Czech', complete: true, official: true },
```suggestion
    cs: { name: 'Čeština', en: 'Czech', complete: true, official: true },
```

2023-08-03 07:57 UTC, Hermez-cz commented
@hrudolf Thank you very much, this is excellent! We’ll give it a review and deploy it soon (October release most probably due to our release cycle, but no promises can be made due to our tight schedule). We will perhaps update the categorization from the brackets at every line to adding a label to the divider instead, but no worries, we’ll handle it.

2023-08-15 08:25 UTC, matejkriz commented
@hrudolf Thank you again for your contribution ❤️  We slightly reworked the UI [in other PR](https://github.com/trezor/trezor-suite/pull/9151), closing this now. The issue https://github.com/trezor/trezor-suite/issues/7624 is still not completely resolved, don't worry, we plan to add more languages including Hungarian.

2023-08-15 08:25 UTC, closed without merging