Fix: sendform compose transaction callback
trezor/trezor-suite pull request #9046
Opened 2023-07-27 12:39 UTC by szymonlesisz

## Description

Related to https://github.com/trezor/trezor-suite/issues/9045

- Remove flags used by useSendFrom hook and underlying sub-hooks from `UseSendFormState`
- Create composeRequestCallback and use it as dependency of useEffect
- Fix displaying message about missing amount to input when form has `isLoading` flag enabled

2023-07-27 15:31 UTC, szymonlesisz commented
fixed failing unit test and invalid fieldName used by Address input.

i want to believe that notes commented above `composeRequest` fn in useSendFormCompose are no longer valid (i didnt observe such behavior anymore)

2023-07-28 15:21 UTC, komret requested changes
Great improvements to both UX and code, the send hooks certainly benefit from any simplification. I found some problems, though:

2023-07-28 15:21 UTC, komret commented on packages/suite/src/hooks/wallet/useSendFormCompose.ts
> +            composeRequestRef.current = field;
The ref is not used anymore. Please remove all occurrences.

2023-07-28 15:21 UTC, komret commented on packages/suite/src/hooks/wallet/useSendFormCompose.ts
> +            processComposeRequest();
Not directly related, but `processComposeRequest` is only ever called from here. I suggest merging the two functions, I see no point in having them split.

2023-07-28 15:21 UTC, komret commented on packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
> -        onChange: () => composeTransaction(`outputs.${outputId}.amount`),
Upon further inspection, this appears to be intended. The compose errors are always associated with the amount. In case you change the address to a different address type and the result is a bigger transaction, you can get 'AMOUNT_IS_NOT_ENOUGH' error, which should appear under the amount field. I suggest reverting this change and adding a comment instead.

2023-07-31 08:54 UTC, szymonlesisz commented on packages/suite/src/hooks/wallet/useSendFormCompose.ts
> +            composeRequestRef.current = field;
thanks, fixed in d114884a194aa2ff3afc651bc5fb7d783ffd499c

2023-07-31 08:55 UTC, szymonlesisz commented on packages/suite/src/hooks/wallet/useSendFormCompose.ts
> +            processComposeRequest();
fun fact, i wanted to do it but i also know how hard is to get a review when i do too much changes :)
done in d114884a194aa2ff3afc651bc5fb7d783ffd499c

2023-07-31 08:56 UTC, szymonlesisz commented on packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
> -        onChange: () => composeTransaction(`outputs.${outputId}.amount`),
nice :+1: fixed in 2b8132847d37ce3a4091dd38529a7f1fc2c82fe4

2023-07-31 09:13 UTC, komret approved these changes

2023-08-01 08:11 UTC, szymonlesisz commented
/rebase

2023-08-01 09:52 UTC, merged