chore(suite-native): upgrade react native to 0.72.3
trezor/trezor-suite pull request #9071
Opened 2023-07-31 10:45 UTC by juriczech

## Description

## Related Issue

Resolve 

## Screenshots:

2023-07-31 14:22 UTC, Nodonisko requested changes

2023-07-31 14:22 UTC, Nodonisko commented on suite-native/app/jest.config.js
> +module.exports = {
We don't have any tests in `app` so we don't need this file.

2023-07-31 14:22 UTC, Nodonisko commented on suite-native/app/package.json
> +    "engines": {
this is handled in repo root, please delete

2023-07-31 15:45 UTC, PeKne approved these changes

2023-08-02 20:13 UTC, Nodonisko approved these changes

2023-08-02 20:13 UTC, Nodonisko commented on suite-native/app/pod
What is this file?

2023-10-13 11:49 UTC, closed without merging