Fix: rbf decreased outputs view
trezor/trezor-suite pull request #9193
Opened 2023-08-16 16:09 UTC by szymonlesisz

## Description

Another day, another cherry-picking from [coinjoin RBF branch](https://github.com/trezor/trezor-suite/pull/9040)

Fixing case when `DecreasedOutputs` view is unnecessarily shown if reducing output is not possible, or even blinks https://github.com/trezor/trezor-suite/issues/8742

How to test it?

- send yourself a small amount like 0.00008 test and be sure that this is the only utxo you have on that account
- next send this utxo somewhere else using send-max (without change output) with high (maximum possible) feeRate, like 60+ sat/b
- try to bump tx (this should not be possible, but also `DecreasedOutputs` view is not visible - it will on develop)

2023-08-16 17:30 UTC, szymonlesisz commented
back to draft, i've found another related issue

2023-08-18 09:30 UTC, AdamSchinzel requested changes

2023-08-18 09:30 UTC, AdamSchinzel commented on packages/suite/src/hooks/wallet/useRbfForm.ts
> +    const [decreasedOutputs, showDecreasedOutputs] = useState(false);
```suggestion
    const [showDecreasedOutputs, setShowDecreasedOutputs] = useState(false);
```

2023-08-18 11:17 UTC, szymonlesisz commented on packages/suite/src/hooks/wallet/useRbfForm.ts
> +    const [decreasedOutputs, showDecreasedOutputs] = useState(false);
[5ee79fc](https://github.com/trezor/trezor-suite/pull/9193/commits/5ee79fcdbd1ce4e134d5f8bc4d5182c38107df98)

2023-08-18 11:49 UTC, AdamSchinzel approved these changes
lgtm

2023-08-18 11:55 UTC, szymonlesisz commented
/rebase

2023-08-21 08:08 UTC, merged