fix(suite): device label input
trezor/trezor-suite pull request #9233
Opened 2023-08-23 10:27 UTC by AdamSchinzel

Device label input tweaks

## Description

Device label input has same width as button and also fixed mobile version.

## Screenshots:

<img width="516" alt="Screenshot 2023-08-23 at 10 01 23 AM" src="https://github.com/trezor/trezor-suite/assets/66002635/8a373423-2f32-496c-8c2d-5e4b7fb74b88">
<img width="195" alt="Screenshot 2023-08-23 at 12 26 51 PM" src="https://github.com/trezor/trezor-suite/assets/66002635/c5ef5fb1-abd5-4163-b611-36c15735946e">

2023-08-24 13:10 UTC, dahaca requested changes

2023-08-24 13:10 UTC, dahaca commented on packages/components/src/components/form/Input/Input.tsx
> +            alignInputRight={alignInputRight}
Please, do not introduce properties to global components which will only be used once. Create a SyledInput and apply alignment there if needed :)

2023-08-24 13:10 UTC, dahaca commented on packages/components/src/components/form/Input/Input.tsx
> +    @media (min-width: ${SCREEN_SIZE.SM}) {
Better use `SCREEN_QUERY`

2023-08-25 09:23 UTC, AdamSchinzel commented on packages/components/src/components/form/Input/Input.tsx
> +            alignInputRight={alignInputRight}
695eeef2c9bcbb469a40854c16adc4b9335722f4

2023-08-25 09:23 UTC, AdamSchinzel commented on packages/components/src/components/form/Input/Input.tsx
> +    @media (min-width: ${SCREEN_SIZE.SM}) {
695eeef2c9bcbb469a40854c16adc4b9335722f4

2023-08-25 11:33 UTC, dahaca approved these changes

2023-08-25 14:15 UTC, merged

2023-09-08 10:35 UTC, bosomt commented
**QA OK**


**Info:**
 - Suite version: desktop 23.9.1 (41a9c13bf28edf71fe629379288a5ad685f259d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.9.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33