Feat/models from submodules
trezor/trezor-suite pull request #9311
Opened 2023-08-30 12:08 UTC by tomasklim

## Description

- copy models info from firmware repo to connect
- use device display name from this models info
- prepare device color helper

## Related Issue

part of [#21](https://github.com/trezor/trezor-suite-private/issues/21)

## Screenshots:

2023-08-30 14:59 UTC, matejkriz commented on packages/device-utils/src/modelUtils.ts
> +    if (Object.prototype.hasOwnProperty.call(colors, deviceUnitColor)) {
why not just `if(deviceUnitColor in colors) {`?

2023-08-30 16:26 UTC, mroz22 requested changes

2023-08-30 16:26 UTC, mroz22 commented on packages/connect/src/exports.ts
> +export { models } from './data/models';
we talked about this in the office
I would prefer not re-exporting this and implement packages/device-utils/src/modelUtils.ts on connect level.

2023-09-05 11:51 UTC, mroz22 approved these changes
looks igelit

2023-09-05 12:14 UTC, merged