feat(components): add a Badge component
trezor/trezor-suite pull request #9328
Opened 2023-08-31 16:41 UTC by dahaca

## Description

* add a Badge component

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/9320

## Screenshots:

See Storybook

2023-08-31 16:55 UTC, mroz22 commented
rebase on this to fix type-check https://github.com/trezor/trezor-suite/pull/9327

2023-09-01 14:52 UTC, komret requested changes

2023-09-01 14:52 UTC, komret commented on packages/components/src/components/Badge/Badge.tsx
> +    ) : null;
nit: could be inside other JSX

2023-09-01 14:52 UTC, komret commented on packages/components/src/components/Badge/Badge.tsx
> +        onClick &&
```suggestion
        onClick && !isDisabled &&
```

2023-09-03 15:49 UTC, dahaca commented on packages/components/src/components/Badge/Badge.tsx
> +    ) : null;
aec732c43b

2023-09-03 15:49 UTC, dahaca commented on packages/components/src/components/Badge/Badge.tsx
> +        onClick &&
aec732c43b

2023-09-04 08:51 UTC, komret commented
Still needs rebasing, some unrelated commits got to the PR.

2023-09-04 12:13 UTC, komret approved these changes

2023-09-04 12:14 UTC, komret commented
Check validation check.

2023-09-04 17:39 UTC, merged