Fix FW update flow for BTC-only devices
trezor/trezor-suite pull request #9751
Opened 2023-10-25 17:28 UTC by komret

## Description

Bitcoin-only device with Universal firmware should offer updates for Universal firmware, not Bitcoin-only.

I also unified some copy, those two versions were nearly identical.

I don't know if it is possible to trigger firmware installation in the `unknown` state of `device.firmware`. If it is, Bitcoin-only device will always offer Bitcoin-only firmware in that state which may lead to the device being wiped.

**QA**: please test FW install, update and switch on a BTC-only TS3 (Universal firmware can be installed via custom firmware installation)

2023-10-25 20:00 UTC, tomasklim commented
### I also unified some copy, those two versions were nearly identical.

I separated it into two translation strings as both strings are for different cases. The text is identical now, but I expected that it will change in crowdin.

Thats why the description is different.
`Explanation of Bitcoin-only firmware in onboarding` vs `Explanation of Bitcoin-only firmware in onboarding for Bitcoin-only devices`

2023-10-25 20:06 UTC, tomasklim requested changes, later dismissed
I like the simplification of the condition. Thank you

2023-10-25 20:06 UTC, tomasklim commented on packages/suite/src/components/firmware/FirmwareInitial.tsx
> +        // installing an empty Bitcoin-only device
```suggestion
        // initialising an empty Bitcoin-only device
```

or installing fw on an empty ...

2023-10-25 20:06 UTC, tomasklim commented on packages/suite/src/components/firmware/FirmwareInitial.tsx
> -            : 'TR_FIRMWARE_SUBHEADING_UNKNOWN_BITCOIN_ONLY_DEVICE';
I would not do that, see comment above

2023-10-26 14:38 UTC, komret commented on packages/suite/src/components/firmware/FirmwareInitial.tsx
> -            : 'TR_FIRMWARE_SUBHEADING_UNKNOWN_BITCOIN_ONLY_DEVICE';
Ok, dropped.

2023-10-26 14:38 UTC, komret commented on packages/suite/src/components/firmware/FirmwareInitial.tsx
> +        // installing an empty Bitcoin-only device
Simplified further.

2023-10-27 14:17 UTC, matejkriz commented on packages/connect/src/device/Device.ts
> +        if (feat.fw_vendor === 'Trezor Bitcoin-only') {
I'd be inclined to define those possible headers into constants somewhere, but as long as it's a single use, it's probably OK to have strings.

2023-10-27 14:31 UTC, matejkriz approved these changes
nice 👍

2023-10-27 15:24 UTC, merged

2023-11-21 13:50 UTC, bosomt commented
**QA OK**

tested multiple/all device models and FW types combinations including BTC only device.