fix(suite): Custom backends are used in all urls
trezor/trezor-suite pull request #9757
Opened 2023-10-26 08:36 UTC by jvaclavik

## Description

## Related Issue

Resolve 

## Screenshots:

2024-01-05 15:32 UTC, tomasklim requested changes
Please remove `submodules/trezor-common` change

2024-01-05 15:35 UTC, tomasklim requested changes

2024-01-05 15:35 UTC, tomasklim commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/AnalyzeInExplorerBanner.tsx
> +    const explorerUrl = useSelector(state => state.wallet.blockchain[symbol].explorer.tx);
use `useExplorerTxUrl` hook

2024-01-05 15:35 UTC, tomasklim commented on packages/suite/src/hooks/suite/useExplorerTxUrl.ts
> +export const useExplorerTxUrl = (symbol: NetworkSymbol) => {
How about getting rid of this hook and changing it to selector?

2024-05-08 13:25 UTC, tomasklim commented
@jvaclavik lets finish this?

2024-05-08 18:59 UTC, jvaclavik commented
> @jvaclavik lets finish this?

yes 🫣😅

2024-07-16 12:49 UTC, komret commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/AnalyzeInExplorerBanner.tsx
> +                href: `${explorer?.address}${txid}`,
Should be `explorer.tx`.

![Screenshot 2024-07-16 at 14 45 31](https://github.com/user-attachments/assets/64f9ac0f-f042-4049-b8d1-e0360a11d646)

2024-07-16 12:50 UTC, komret commented on packages/suite-desktop/suite-desktop/releaseNotes/release-notes.md
Does this belong here?

2024-08-15 20:03 UTC, tomasklim approved these changes
LGTM

2024-08-16 06:59 UTC, merged

2024-08-16 07:03 UTC, tomasklim commented
@trezor/qa please test this together with https://github.com/trezor/trezor-suite/pull/13834