settings menu > stick to design better
trezor/trezor-suite pull request #978
Opened 2019-12-27 14:15 UTC by mroz22

2019-12-30 09:04 UTC, slowbackspace approved these changes
very nice

2019-12-30 09:06 UTC, slowbackspace requested changes
two little things:

"Settings" should be all caps and colors of icons and texts (for both selected and not selected items) are incorrect.

hmm maybe also paddings around icons are a bit off?
<img width="277" alt="Screenshot 2019-12-30 at 10 05 10" src="https://user-images.githubusercontent.com/6961901/71575086-deb05280-2aeb-11ea-9b4d-e6c274d00ce8.png">

2020-01-02 16:59 UTC, mroz22 commented
- rebased
- capitalized (just in messages, maybe it would be nice to have "Capitalize" component, but hmm.. maybe later
- icon moved by 2pxs
- colors of items adjusted to match design

2020-01-02 17:21 UTC, slowbackspace approved these changes

2020-01-02 18:36 UTC, merged