fix(suite): RBF use increased feeLevel instead of baseFee
trezor/trezor-suite pull request #9964
Opened 2023-11-15 18:50 UTC by szymonlesisz

## Description

Should fix https://github.com/trezor/trezor-suite/issues/9424

in new fee calculation using `baseFee` parameter returns invalid results when new utxo and new change output are added (described in the issue)

new feeRate for composeTransactions process can be easily taken from the useRbfForm state (increased levels old + new)
it wasn't done like this until now because there was a time when transactions received from the backend didnt have feeRate field, but they have it some time now (there are multiple fallbacks for missing feeRate accross the suite code)

`baseFee` is still used for overpaying related transaction (chainedTxs) 
NOTE: field name is ambiguous (rbfParams.baseFee !== baseFee param in Trezorconnect.composeTransaction) i will remove it completely from the rbfParams in upcoming PR

2023-11-16 12:04 UTC, marekrjpolak approved these changes
Looks good. I haven't checked the updated values in fixtures though.

2023-11-16 13:27 UTC, szymonlesisz commented
im waiting for @trezor/qa tests before the merge

2023-12-06 09:09 UTC, komret requested changes

2023-12-06 09:09 UTC, komret commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ChainedTxs.tsx
> +        ))}
There is some repeated code here, could be refactored into `ChainedTransactionList` or something.

2023-12-06 09:09 UTC, komret commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ChangeFee/AffectedTransactions.tsx
> +export const AffectedTransactionItem = ({
Could be a separate file. But not sure what is better.

2023-12-06 09:19 UTC, szymonlesisz commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ChainedTxs.tsx
> +        ))}
first loop creates list of `<ChainedTransactionItem>` second creates list of `<StyledAffectedTransactionItem>` 

so the only repeated code is the loop itself :)

therefor potential `ChainedTransactionList` should have additional condition which component to use, i dont see any benefit from it tbh

2023-12-06 09:26 UTC, szymonlesisz commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ChangeFee/AffectedTransactions.tsx
> +export const AffectedTransactionItem = ({
[7de8809](https://github.com/trezor/trezor-suite/pull/9964/commits/7de88096cdcf762238a57b01177518f0994b77f0)

2023-12-06 11:33 UTC, komret commented on packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ChainedTxs.tsx
> +        ))}
It could take `children`.

2023-12-06 11:36 UTC, komret approved these changes

2023-12-06 11:36 UTC, komret commented
/rebase

2023-12-06 11:48 UTC, merged